### ISSUE TITLE
64-bit Java should be preferred even if it's older than a 32-bit version

### ISSUE THREAD

**Issue by Slind14** [SKCraft/Launcher#10]
Hey,

we just noticed that the launcher always uses the java version with the latest version. So if 32bit is more up to date than 64bit it will use the 32bit version. Is it possible to change this ?

The main problem with it is, that the 32bit gets auto-updated and the 64bit not.

**Comment by GamesGamble** [comment]
Java now is updating both versions x32 and x64 with Java 8 Update 31 (maybe earlier [tested with Firefox 35.0.1] and is deinstalling old java installations)
Maybe this features is no longer needed.

**Comment by sk89q** [comment]
It should probably still prefer 64-bit.

**Comment by Slind14** [comment]
It's normal java behavior: latest > 64bit -> which kinda makes sense in general.

**Comment by hedgehog1029** [comment]
Java runtime searching has been reworked and this should now be the case.
