### ISSUE TITLE
Custom color scheme?

### ISSUE THREAD

**Issue by dj3520** [SKCraft/Launcher#100]
Hi. I've been using the fancy launcher to push mod updates to clients in a very nice way. I'm looking to customize it in any way possible, and have done a few things to achieve that. So far I've got to this point.
![image](https://cloud.githubusercontent.com/assets/8284194/11047393/272fb602-8700-11e5-9077-f98ed0a4ff07.png)

I've been looking for a way to change the colors for the buttons, backgrounds and such and can't make sense of [Colorscheme files](https://github.com/SKCraft/Launcher/tree/master/launcher-fancy/src/main/resources/com/skcraft/launcher/skin)

I could just change the values and watch for changes but I'd like some direction on this.

**Comment by sk89q** [comment]
Can't say I fully got the hang of how Substance applies colors, but what I did was finding a skin closest to what I wanted (from [their demos](https://insubstantial.github.io/insubstantial/substance/)) and used it as a starting point. If you want a dark/black scheme, then I think I already picked the best one for that.

The color scheme file doesn't cover everything of course. The button style and whatnot are controlled from [the skin class](https://github.com/SKCraft/Launcher/blob/master/launcher-fancy/src/main/java/com/skcraft/launcher/skin/LauncherSkin.java).

For example, the button style is set here:

```java
this.buttonShaper = new LauncherButtonShaper();
```

which is [my own class that you can find here](https://github.com/SKCraft/Launcher/blob/master/launcher-fancy/src/main/java/com/skcraft/launcher/skin/LauncherButtonShaper.java), which is based off of the `ClassicButtonShaper` class that comes with the skinning library. The only reason why I made my own was so I could make the buttons have more spacing.

I don't know how familiar you are with Java, or with using an IDE, but how I found, for example, alternative style classes that I could use was (1) [checking out the other skins](https://github.com/Insubstantial/insubstantial/tree/master/substance/src/main/java/org/pushingpixels/substance/api/skin) and (2) going to the parent class of one of them (such as `FlatDecorationPainter`) and then using "show hierarchy" (in IntelliJ IDEA, click a class name and then press `CTRL-H`) to see what other options there are:

![](http://i.imgur.com/Dqt0CdZ.png)

The "decorationPainter" determines how the window frame looks. From that screenshot above, you can see where the skin sets it:

```java
this.decorationPainter = new FlatDecorationPainter();
```

One of the options on the right list in that screenshot is `Glass3DDecorationPainter`, so you could try switching it like so:

```java
this.decorationPainter = new Glass3DDecorationPainter();
```

and then you get this hideous thing:

![](http://i.imgur.com/9NCNdbT.png)

But back to colors, it was pretty much trial and error for me.

The docs for the skinning library are here: https://insubstantial.github.io/insubstantial/substance/

**Comment by sk89q** [comment]
Also, if you're testing color schemes by running Gradle every time, you'll probably go mad.

I'd install IntelliJ or something to test.

**Comment by dj3520** [comment]
I'm not into Java unfortunetely, but as for changing how the buttons render
I think I'd leave it alone anyway. I was looking for just changing the
color schemes without getting deep in code since there seems to be a file
for it.
