### ISSUE TITLE
Help Cracked Account?

### ISSUE THREAD

**Issue by jtrent238** [SKCraft/Launcher#101]
Can I Use Cracked Accounts?

**Comment by sk89q** [comment]
The launcher is not made with it in mind.

**Comment by jtrent238** [comment]
Is There A Way To Use Cracked Accounts?

**Comment by sk89q** [comment]
No

**Comment by TheCherry** [comment]
Its Opensource, you have to edit 2 If's and if you want to add a individual username with the IdField, you have to add 2 code lines ...
