### ISSUE TITLE
Not Loading My Mods Why?

### ISSUE THREAD

**Issue by jtrent238** [SKCraft/Launcher#102]
It Just Loads The 3 Forge Mods

**Comment by ajthemacboy** [comment]
Did you read the Wiki on how to setup a modpack? Clearly you have no mods installed which means you didn't set it up correctly.

**Comment by jtrent238** [comment]
I Do Have Mods Installed
![image](https://cloud.githubusercontent.com/assets/10227394/11051015/3a5718e2-8719-11e5-917a-a1a9ea6fe12f.png)

**Comment by sk89q** [comment]
So the mods don't show up in game?

That might be because all your .jar files are corrupt because you may have not uploaded them correctly (especially if you're using FTP).

Try opening your .jar files using 7-zip, WinZip, or WinRAR. If they can't open the .jar files (which are just .zip files), the files are corrupt.

**Comment by jtrent238** [comment]
Why are They Corrupt?

**Comment by sk89q** [comment]
Did you use FTP? You might have used "ASCII mode", which makes FTP think your files are text files and will make changes to them. Switch to "binary mode".

**Comment by jtrent238** [comment]
Yes I Use FTP File Zilla

**Comment by jtrent238** [comment]
Oh And I Added An Examples Page To The Wiki

**Comment by jtrent238** [comment]
So I Need To Delete All Files And Re-upload In Binary?

**Comment by ajthemacboy** [comment]
Just a thought, could it be an issue in the folder name? It's rather long and has some strange chars.

**Comment by sk89q** [comment]
Well, did @jtrent238 try opening the .jar files in 7zip/WinZip/WinRAR? If he did and they couldn't be opened, then they are corrupt.

And if they are corrupt, yes, you have to re-upload everything.

**Comment by jtrent238** [comment]
Already Reuploading

**Comment by jtrent238** [comment]
I Got I Fixed!
