### ISSUE TITLE
Search Bar For ModPacks

### ISSUE THREAD

**Issue by jtrent238** [SKCraft/Launcher#107]
Is There A Way To Be Able To Add A Search Bar To Search For Certain ModPacks?

![image](https://cloud.githubusercontent.com/assets/10227394/11135571/56d60f8e-8974-11e5-8884-826e838f95f3.png)

**Comment by ajthemacboy** [comment]
Why Do You Talk Like This?

Why are you creating so many issues?

If you didn't have 15 modpacks in your launcher you wouldn't even need a search bar, and even though you do it's really not necessary.

**Comment by jtrent238** [comment]
I Plan On Having Hundreds!

**Comment by ajthemacboy** [comment]
That's wonderful. I'm sure they'll all be popular.

This is a ridiculous feature request. Your issues will be supported much more if you use the launcher in a practical way.

**Comment by dj3520** [comment]
You could split them up by using keys if your website supports php.

**Comment by jtrent238** [comment]
Im Not Sure?

**Comment by Leeo97one** [comment]
That Guy Is A Troll xD

**Comment by wizjany** [comment]
"Never attribute to malice that which is adequately explained by stupidity."

**Comment by ajthemacboy** [comment]
![This guy](http://i0.kym-cdn.com/photos/images/newsfeed/000/131/351/eb6.jpg?1307463786)

**Comment by dj3520** [comment]
Someone please close this

**Comment by jtrent238** [comment]
How would I add this?
