### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by jtrent238** [SKCraft/Launcher#108]
Can The Launcher Create A Directory Instead Of Just Dumping Files Every Where?
![image](https://cloud.githubusercontent.com/assets/10227394/11166696/1b595686-8b0f-11e5-815a-435e67021043.png)

**Comment by ajthemacboy** [comment]
Check the wiki before posting if you're going to make 10 issues. There are command line arguments you can use. 

Not that it really "dumps files everywhere" by default.

**Comment by jtrent238** [comment]
I Mean When You Launch A Mod Pack It Puts The Files Every Where!

**Comment by dj3520** [comment]
No? Everything is organized in its own folder for me. I don't think you're
doing something right.

**Comment by sk89q** [comment]
You can either

1. Put all the files in the current directory or
2. Put all the files in My Documents/Your Launcher

The wiki should tell you how to do both. You already got 1

**Comment by jtrent238** [comment]
Yea I Did Put The Launcher In Its Own Folder And Created A Shortcut.

**Comment by dj3520** [comment]
Funny enough my launcher file is on my desktop and my files in a folder in
my documents with my custom name on it.
