### ISSUE TITLE
Enhancement - Cache Sessions

### ISSUE THREAD

**Issue by Slind14** [SKCraft/Launcher#110]
It would be most helpful if sessions would be kept and reused as long as valid with loading up multiple instances during the same time. While this might be interesting for advanced users mainly (pack maintainer..) it could also allow for another feature of auto login (skip login popup), which quite some users showed interest for.

**Comment by ajthemacboy** [comment]
I'm not sure if this is even related, but currently, every time I use the launcher, the vanilla launcher's token breaks. Is this unavoidable?

**Comment by sk89q** [comment]
It's unavoidable. Mojang doesn't let you stay logged in at two different places. 

The launcher logs in with your username/password rather than a token for this reason.

**Comment by Slind14** [comment]
What I meant was SKCraft launcher only session caching. So that you can start two instances from it without destroying the session of the other instance.

**Comment by jtrent238** [comment]
So Your Saying Having two Minecraft's Open At The Same Time?

**Comment by hedgehog1029** [comment]
With the merging of the redesigned account support in #398 this should be fixed. The launcher now generates and persists a client token much like the vanilla launcher which should stop it invalidating existing sessions.
