### ISSUE TITLE
Error executing launcher-bootstrap-4.3-SNAPSHOT-all.jar

### ISSUE THREAD

**Issue by Stantastic** [SKCraft/Launcher#112]
States: Downloading latest Launcher till 100%
Then: The Launcher could not be downloaded.

To report this error, provide:

java.io.IOException: Failed to find launchable .jar
    at com.skcraft.launcher.Bootstrap.launchExisting(Bootstrap.java:140)
    at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:119)
    at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
    at java.lang.Thread.run(Unknown Source)

**Comment by ajthemacboy** [comment]
I can't find the wiki page on bootstrap launching, but I believe it requires properly setting up your .jar.pack.

Some help here: https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update

**Comment by sk89q** [comment]
Is this still an issue?

**Comment by Stantastic** [comment]
yep it is!

**Comment by StrayanDropbear** [comment]
Not sure if this was fixed but having the exact same issue.

**Comment by sk89q** [comment]
Can someone with the problem send me their files / URLs?

the.sk89q @ gmail

**Comment by StrayanDropbear** [comment]
I managed to fix this, i accidentally removed the '=' for 'selfUpdateUrl' in launcher properties. that's what caused it for me.
