### ISSUE TITLE
How to disable premium feature to non-premium users please help me!.

### ISSUE THREAD

**Issue by Bartixxx32** [SKCraft/Launcher#115]

**Comment by dj3520** [comment]
explain

**Comment by Bartixxx32** [comment]
sorry for my bad English I use Google Translate.
I was thinking about my launcher dish to my viewers, unfortunately, I know that a very small number of persons have minecraft premium over that I thought that in this launcherzer somehow disable the option premium players to be able to log in as user non-premium

**Comment by dj3520** [comment]
Have you tried "play offline?"

**Comment by Bartixxx32** [comment]
how to enable that i know. I must be logged 1 time to premium and when not have internet play offline is enabled.
How to enable play offline pernamently for non-premoim users?
