### ISSUE TITLE
how enable offline mode

### ISSUE THREAD

**Issue by bluesksksk** [SKCraft/Launcher#116]
hello how can i enable offline mode in launcher?

**Comment by 1n5aN1aC** [comment]
There is a "play offline" button on the bottom right of the login dialog that works if you have logged in once before.

If you mean for non-premium users, you can't.

**Comment by bluesksksk** [comment]
yes but look here http://customcraft.cz/wp-content/uploads/2015/09/Screenshot_2.png

they launcher have play offline(warez)

**Comment by 1n5aN1aC** [comment]
Yes, you are correct, it is relatively easy to modify the launcher to support playing "offline" without having played online first. (therefore cracked)   In fact, there's only a couple lines that need changed to make it do this.

However, no one on this GitHub repository is going to tell you what would need to be modified to do that.  Sorry :frowning:

**Comment by bluesksksk** [comment]
but why.? someone must know how to do that. and where can i find therefore cracked ?

**Comment by bluesksksk** [comment]
in what file i can change the lines?

**Comment by 1n5aN1aC** [comment]
Well, what I was trying to say is that I don't think anyone on this Github project is going to help you figure it out, because the majority of us don't want to promote piracy for either personal or legal reasons.

**Comment by bluesksksk** [comment]
and know someone who know modify that launcher?

**Comment by bluesksksk** [comment]
please help me i need it

**Comment by dj3520** [comment]
MagicLauncher lets you do this

**Comment by bluesksksk** [comment]
Its not funny i really need it

**Comment by codydbgt** [comment]
ill do it at some point since people are dicks

**Comment by James137137** [comment]
Its not because we are "dicks" codydbgt. I feel its because just most of us wouldn't want to support "cracked" launchers and I personally want us to maintain our high confidence SKCraft's Launcher

**Comment by codydbgt** [comment]
not my fault mojane became bann happy overnight i'm just taking precautions and making it available
