### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by bluesksksk** [SKCraft/Launcher#118]
HI

**Comment by Leeo97one** [comment]
What?

**Comment by dj3520** [comment]
File not found

**Comment by wizjany** [comment]
the manifest files are present in all build scripts and compiled jars. if you are missing it you need to provide more info like: where did you download the jar file? did you build it youself? if so, do you have log files? how are you running the jar? where does it say the file isn't found? (logs?) etc.

**Comment by dj3520** [comment]
Does this file exist? \instances\Light Modpack\manifest.json

**Comment by wizjany** [comment]
that's not an issue with the launcher, that's an issue with your modpack.

**Comment by bluesksksk** [comment]
i just need know how to edit this launcher for non-premium users

**Comment by dj3520** [comment]
no

**Comment by bluesksksk** [comment]
why?

**Comment by wizjany** [comment]
Non-premium accounts/servers aren't supported.

**Comment by dj3520** [comment]
Piracy is illegal. Buy the game or give up.
