### ISSUE TITLE
Optional Features Menu not Opening

### ISSUE THREAD

**Issue by rouing** [SKCraft/Launcher#120]
I have a mod-pack with various optional features but the launcher wont open the menu asking me which features I want to install. 

Launcher is here:
https://origin-modpack.rouing.lol/launcher/

**Comment by ajthemacboy** [comment]
I don't see any optional features in your release.json. In the creator GUI, it's under Modify > Optional features.

If you were using the CLI version I recommend the GUI, it's a lot easier.

**Comment by rouing** [comment]
It seems it didn't create the Optional Features inside the release.json even though I made them. I already have the Optional Features setup in the GUI.

**Comment by rouing** [comment]
http://i.imgur.com/dVO7m57.png

**Comment by ajthemacboy** [comment]
Make sure each optional feature has the right filepath. For example:

JourneyMap would be mods/journeymap-fairplay-xxx.jar

**Comment by rouing** [comment]
Ok, i figured out the issue. When adding mods to the modpack, don't add _SERVER or _CLIENT to the file path.
