### ISSUE TITLE
Could not reserve enough space for object heap

### ISSUE THREAD

**Issue by Stantastic** [SKCraft/Launcher#121]
The game is running. Please wait.
Error occurred during initialization of VM
Could not reserve enough space for 1505280KB object heap
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Process ended with code: 1

Java version 8 update 66
windows 7 x64

**Comment by Nincodedo** [comment]
How much RAM do you have available?

**Comment by dj3520** [comment]
This is a minecraft configuration problem, not an issue with the launcher.
You need to adjust your memory allocation settings.

**Comment by jtrent238** [comment]
on 32 bit systems The Max You Can Have is 1124MB

**Comment by sk89q** [comment]
Make sure the launcher is using 64-bit Java. If you have 64-bit Java installed, then you may have to uninstall the 32-bit versions or install a newer 64-bit version. Or instead, you can set the path to Java manually in the launcher options.

**Comment by ajthemacboy** [comment]
This software has helped me a lot before: https://singularlabs.com/software/javara/

It will find and remove ALL instances of Java, even old ones left in your registry. It could be that you are infact using 32 bit Java, even though you have 64 bit installed, even if 32 bit doesn't show up in your installed programs.
