### ISSUE TITLE
FML arguments not happening

### ISSUE THREAD

**Issue by budgej** [SKCraft/Launcher#124]
I am attempting to use a custom jar.  The following flags are set in modpack.json:
-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true

Here is the error in the log when I attempt a test launch:
The minecraft jar file:/N:/SKLauncher/modpacks/.modpacks/staging/launcher/instances/Forge%201.8.9/minecraft/custom_jar.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!

More information:
I am using a small test instance consisting of an unmodified Forge build 1688 installer jar and a 1.8.9 jar with the "META-INF" folder deleted (no other changes).  The flags set above don't seem to take.  I have done this test with 1.7.10, 1.8, and 1.8.9.  An older 1.0-based SKCraft launcher I was using previously worked with the exact same setup.  4.3-SNAPSHOT and 4.3.1 both are giving me this result.  Additionally, if I add a .class file to the jar, I get a patch discrepancy error.

I can't upload the modpack.json, so here's a dropbox link for it.  Thanks for any help you can provide.

https://www.dropbox.com/s/wep514qa1kmt44m/modpack.zip?dl=0

**Comment by ajthemacboy** [comment]
Send the log, it's likely that it really IS adding the flags but Forge is just so badly damaged they won't work.

**Comment by budgej** [comment]
Here's the log.

http://pastebin.com/qBaUBaFZ

**Comment by ajthemacboy** [comment]
Line 16 indicates that indeed, -Dfml.ignoreInvalidMinecraftCertificates=true is not being used. Try setting that argument in the launcher itself instead of the modpack.json.

If all else fails, recompile the launcher with those arguments hardcoded.

**Comment by budgej** [comment]
We're getting to the edge of my knowledge here.  Do you mind telling me what line to change in which file for that?  :D  Thanks

**Comment by ajthemacboy** [comment]
I believe you can add them in launcher.properties, if not you can probably change them here:

https://github.com/SKCraft/Launcher/blob/c1cbff754ef681a94150758a10327f8063737f1a/launcher/src/main/java/com/skcraft/launcher/launch/JavaProcessBuilder.java
