### ISSUE TITLE
Launch bug

### ISSUE THREAD

**Issue by FilipK-CZ** [SKCraft/Launcher#126]
Hi, in previous version works everything but after update (download new version) launch button stop work. When I want launch modpack must first click in modpack box and after launch button work. It is something for debug?

Sorry for my english

**Comment by sk89q** [comment]
It's likely caused by a change I made a while back that changed how the list was created (https://github.com/SKCraft/Launcher/commit/991d39ced61d445e4ba6c3a6c42accf5de1a6c6d).

Unless anyone has an objection, I will probably revert the change.

**Comment by gamecraft45** [comment]
Thank you for help.

**Comment by MJRamon** [comment]
I would rather have last played modpack being selected after starting launcher again.
If fresh start, first one must be selected.
