### ISSUE TITLE
Creating a 1.8.9 Forge pack. 

### ISSUE THREAD

**Issue by technostar98** [SKCraft/Launcher#128]
Using Forge 1.8.9-11.15.0.1710 and I end up with a Failure to download jline 2.13. I can launch and build a fresh and already made 1.7.10 instance. The only time I have a problem is when it comes to 1.8.9. So just looking to see what might be the problem here.

Link to pastebin. http://pastebin.com/zVt88hLQ

**Comment by wizjany** [comment]
see #122
