### ISSUE TITLE
Trouble making a modpack (cmd error inside)

### ISSUE THREAD

**Issue by Jeanzl** [SKCraft/Launcher#13]
Hello. I'm making a modpack using this guide: 
http://confluence.skcraft.com/display/LAUN/Generating+a+Package+Manifest

I'm all the way to compiling a build. I don't really know code but it seems that I did not download something. I do have the skcraft launcher but I probably missed something.

C:\Users\Jeanzl2000\Desktop\Wizards and Steam Compile>java -cp SKCraftLauncher.j
ar com.skcraft.launcher.builder.PackageBuilder  --version "0.9"  --manifest-dest
 "dist/manifest.json"  --objects-dest "dist/objects"  --files "src"  --config "m
odpack.json"  --objects-url "objects"  --version-file "version.json"
Error: Could not find or load main class com.skcraft.launcher.builder.PackageBui
lder

**Comment by sk89q** [comment]
Closing due to age.
