### ISSUE TITLE
Creator hangs indefinitely when trying to 'test' a mod pack with optional mods

### ISSUE THREAD

**Issue by kayila** [SKCraft/Launcher#135]
Everything was working well until I added an optional mod to my package. Since then, any time I click on the 'test' button in the creator tools it load up, pops up the dialog to choose optional mods, and then when I dismiss that dialog 90% of the time it hangs forever with the message "Reading package manifest..." Sometimes it will go through but those times are very very rare. This makes testing the pack before building the deployed version pretty difficult.

**Comment by kayila** [comment]
There appears to be an issue with `SwingUtilities.invokeAndWait` which sometimes comes up if an event gets on the stack before the function inside invokeAndWait returns.

Problem line appears to be here: https://github.com/SKCraft/Launcher/blob/24fddc42361025a69428f2cd306f4d6e50e6c2a7/launcher/src/main/java/com/skcraft/launcher/update/BaseUpdater.java#L111-L116

**Comment by sk89q** [comment]
Can you grab a thread dump of the whole application when it's stuck?

**Comment by kayila** [comment]
I'll try to grab it in the next day or two. In the mean time, this little hack is a workaround that does seem to avoid the problem. kayila/Launcher@97ade33e3a1c622f2386d10b0bb21feebd07de1c

**Comment by ajthemacboy** [comment]
This happens to one of my users as well.

**Comment by Sxw1212** [comment]
I am experiencing this problem too, on Linux. Here's a thread dump: http://pastebin.com/PSwWwC6X

**Comment by Routhinator** [comment]
Also seeing this issue on Linux. I can sometimes work around it by wiping my .modpacks folder.
