### ISSUE TITLE
File changes not being detected.

### ISSUE THREAD

**Issue by Slind14** [SKCraft/Launcher#141]
When updating a file but keeping the old name, it tends to happen that it is not being detected as different, needing the user to run a force or even hard-force update.

**Comment by jtrent238** [comment]
Did You Change The Name and Version In Gradle?

**Comment by Slind14** [comment]
With file I mean, the questing data from hqm for example.

**Comment by jtrent238** [comment]
So is Is the config for hqm?

**Comment by dj3520** [comment]
Files are considered different if their hash changes, which it should if you modify a file. In my experience this functions fine. Make sure the modpack generator doesn't include an exclude rule for this data. The only other thing I can think of is that the version number for your modpack isn't changing. That would explain why a force update fixes it. If current version = newest version there isn't any checking done.

**Comment by Slind14** [comment]
hmm might be the same hash. In many cases it is only an item reference that is changing or a small typo being corrected.

**Comment by dj3520** [comment]
You might be experiencing #58 then.

**Comment by Slind14** [comment]
yeah, I guess this is a duplicate of #58

**Comment by dj3520** [comment]
Might, not sure. Do you have a method of checking hashes?

**Comment by Slind14** [comment]
I'm quite certain it is the same thing as it does not happen when there were major changes, like a new quest.

**Comment by sk89q** [comment]
I don't think hashes are colliding. It's rare.

Honestly I might need a copy of the old and new file to see. Or if possible, links to package .json files of the old and new versions.

**Comment by Slind14** [comment]
Alright, I let you know and provide the files once it happens again. (happens once every 5th update)
