### ISSUE TITLE
Title name not working

### ISSUE THREAD

**Issue by smenes** [SKCraft/Launcher#143]
The launcher show only the directory name and not the optional name

launcher: http://i.imgur.com/CzBs34k.png

modpack.json: http://pastebin.com/raw/Rht6zKJ2

source: https://github.com/smenes/DowncubeLauncher

thanks !

**Comment by James137137** [comment]
optional name? the title?

**Comment by smenes** [comment]
yes the title

**Comment by sk89q** [comment]
Title comes from the package listing file (package.json/php).What does that look like?

**Comment by smenes** [comment]
package.php: http://pastebin.com/raw/VfYbMFMw

it seem ok to me

**Comment by Nincodedo** [comment]
I was having this issue on my launcher as well and fixed it by changing the toString in Instance to get the title instead of the name. https://github.com/Nincraft/Nincraft-Launcher/commit/b686a50239fa8ab18cbcb3d0dfaa9ddcd4f769ee

**Comment by smenes** [comment]
thanks Nincodedo
