### ISSUE TITLE
Login over proxy fails

### ISSUE THREAD

**Issue by octylFractal** [SKCraft/Launcher#147]
When using a proxy (currently my setup is using `stunnel4` and `squid3`) the launcher fails to create valid tokens. The Mojang launcher is fine over this proxy.

Note: I tested 1.9 on the Mojang launcher but 1.7.10 on the SKLauncher. I'll try out 1.7.10 on the Mojang launcher to remove potential version differences ASAP.

**Comment by kenzierocks** [comment]
1.7.10 is also fine on the Mojang launcher. So this is definitely a bug with SKLauncher.

**Comment by kenzierocks** [comment]
I think I've pinned it down with Wireshark. The Mojang launcher apparently bypasses the proxy, but I'm not sure how that effects things in the long term. Here's the two request logs: https://gist.github.com/kenzierocks/e3ff937d5fe562bab6b92deae152b76e

**Comment by kenzierocks** [comment]
Here's the request SKLauncher made without a proxy: https://gist.github.com/kenzierocks/29bb3ea404db0fcd1410c4964c07f9e1
