### ISSUE TITLE
Minecraft is not owned on that account

### ISSUE THREAD

**Issue by XxTheGamecraftxX** [SKCraft/Launcher#148]
When i try to launch any of my modpack after i enter my account info the launcher said me : 
Sorry, Minecraft is not owned on that account but i buy the game and with the official launcher it's work ...

I need help please

**Comment by Nincodedo** [comment]
Do you have a legit account?

**Comment by James137137** [comment]
screenshot?

**Comment by sk89q** [comment]
Reset your changes to the launcher.properties file and try again.
