### ISSUE TITLE
Autoupdate feature is broken

### ISSUE THREAD

**Issue by xion87** [SKCraft/Launcher#150]
I just tried to setup everthing, but when i launch bootstrap and i have a old version of the launcher (example i have 0.9.1 and the new version is 0.9.2) it don't donwload the new version of launcher and it keep to run the old version, also if i try to click check update it do nothing, showing the bar progress for 1 sec only.
Any clues?

**Comment by dscso** [comment]
Did you adjust the version in latest.json?

**Comment by xion87** [comment]
yep also tried 2 decimal like 0.1 instead 0.9.9, no success

**Comment by dscso** [comment]
did you create a .pack?

**Comment by xion87** [comment]
yeah, i told that if i run bootstrap on fresh pc, it download the latest release, but if i create a superior pack and update all, old launcher dont download the new one

**Comment by dscso** [comment]
That works for me:
`{
    "version": "4.3.1",
    "url": "http://domain.tld/path-to-launcher/launcher_v4.3.1.jar.pack"
}`

**Comment by xion87** [comment]
you mean autoupdater is working for you?

**Comment by xion87** [comment]
yeah bootstraper is working for me, too, update launcher don't

**Comment by xion87** [comment]
you can just share your source? if you fixed it (without your personal stuff)

**Comment by dscso** [comment]
haha. Fuck. It also don't works for me anymore.

**Comment by dscso** [comment]
Ah! I think I get it. If it updates, It's important that the version of the new launcher is the exactly same like the version in the latest.json file.

**Comment by xion87** [comment]
i know bootstrap don't update but launcher yes
in launcher.proprietes i got
version=${project.version}

**Comment by xion87** [comment]
i tried as you say, same issue :(

**Comment by dscso** [comment]
hm...
build.gradle replaces ${project.version} with the version which is defined in build.gradle... yes...
Did you tried to download the file on you own, unpack and launch it?
Don't you get anything in the log?

**Comment by xion87** [comment]
In log i got only this:
[informazioni] Enumerating instance list...
[informazioni] Available remote instance: 'Trollandia' at version 2016-05-26-17-47-48
[informazioni] Available remote instance: 'Pixelmon' at version 2016-05-26-17-47-56
[informazioni] 2 instance(s) enumerated.
[informazioni] Checking for update...
What you mean head version? the master one?

**Comment by dscso** [comment]
> What you mean head version? the master one?
Yes, master
If I start the Bootstrapper, I get

    [info] Found /home/z1/.density/launcher/1464966740758.jar...
    [info] Trying /home/z1/.density/launcher/1464966740758.jar...
    [info] Launcher loaded successfully.
    [info] Launching with arguments [--dir, /home/z1/.density, --bootstrap-version, 1]
    [info] Bootstrap version 1 detected
    [info] Using given base directory /home/z1/.density
    [info] Cleaning up temporary extracted files directory...
    [info] Checking for update...
    [info] Latest version is 4.3.3, while current is 4.3.3
    [info] No update required.
    [info] Enumerating instance list...
    [info] Density local instance found at /home/z1/.density/instances/Density
    [info] (Density).setManifestURL(http://density.***.***/resources/density.json)
    [info] 1 instance(s) enumerated.
Do you really start the Bootstrapper and not the Launcher?

**Comment by xion87** [comment]
i used bootstrap + fancy one, gonna try it again now

**Comment by xion87** [comment]
you got some warnings when compiling?

**Comment by xion87** [comment]
bootstrap not in conjuction with blabla with souce 1.6

**Comment by xion87** [comment]
tried again not working it stuck to
 [informazioni] Checking for update...

**Comment by dscso** [comment]
> bootstrap not in conjuction with blabla with souce 1.6

I get this too
> [informazioni] Checking for update...

Why do you have "informazioni" instead of "info" Launcher?

**Comment by xion87** [comment]
i am italian and i have translated it :)

**Comment by dscso** [comment]
Ok... So your problem is very strange. And I don't have any Idea why it doesn't work. I am sure its a small stupid error.
How did you get the log? Because in all logs you send me, is nothing I know thats "typical" Bootstrap. Are you REALY sure that you start the Bootstrap and not the Launcher directly? Maybe start the Bootstrap using the command line (`java -jar path-to-bootstrap.jar`).

**Comment by xion87** [comment]
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Administrator>cd C:\Documents and Settings\Administrat
or\Desktop\Launcher-master\launcher-bootstrap\build\libs

C:\Documents and Settings\Administrator\Desktop\Launcher-master\launcher-bootstr
ap\build\libs>java -jar launcher-bootstrap-1.1-all.jar
[informazioni] Found C:\Documents and Settings\Administrator\My Documents\Trolla
ndLauncher\launcher\1465038397515.jar...
[informazioni] Trying C:\Documents and Settings\Administrator\My Documents\Troll
andLauncher\launcher\1465038397515.jar...
[informazioni] Launcher loaded successfully.
[informazioni] Launching with arguments [--dir, C:\Documents and Settings\Admini
strator\My Documents\TrollandLauncher, --bootstrap-version, 1]
[informazioni] Bootstrap version 1 detected
[informazioni] Using given base directory C:\Documents and Settings\Administrato
r\My Documents\TrollandLauncher
[informazioni] Cleaning up temporary extracted files directory...
[informazioni] Checking for update...
[informazioni] Enumerating instance list...
[informazioni] Available remote instance: 'Vanilla 1.8' at version 1.8.1
[informazioni] 1 instance(s) enumerated.

**Comment by MiniDigger** [comment]
Windows XP... 
Do you realize that your os is obsolete for 15 years now?...

**Comment by dscso** [comment]
Yea but I don't think that could be a problem while using JDK/JRE

**Comment by dj3520** [comment]
A quick look at the log @xion87 posted in comparison to what @dscso has posted and I see two particular lines missing: 
`[info] Latest version is 4.3.3, while current is 4.3.3`
`[info] No update required.`

My guess is the update check itself fails, therefore the update is never done. You should check to see if the path to latest.json is correct by viewing it in your web browser.

**Comment by wizjany** [comment]
that's from the launcher, not the bootstrap.

**Comment by Nuc3** [comment]
Hi, I'm having the same problem...

Path to latest.json is correct.
When I run the bootstrap jar of my client for the first time it downloads the latest version. When I'm updating it with a never version (for example 0.0.6 to 0.0.7) ist just isn't updating... 

Log:

[information] Launcher loaded successfully.
[information] Launching with arguments [--dir, C:\Users\BlaBla\Documents\Launcher, --bootstrap-version, 1]
[information] Bootstrap version 1 detected
[information] Using given base directory C:\Users\BlaBla\Documents\Launcher
[information] Cleaning up temporary extracted files directory...
[information] Checking for update...
[information] Enumerating instance list...
[information] Modpack local instance found at C:\Users\BlaBla\Documents\Launcher\instances\GameGumba Modpack
[information] (Modpack).setManifestURL(REPLACED)
[information] 1 instance(s) enumerated.

I replaced some informations.
I'm on Windows 10 and using the latest github Version of SKCraft.

**Comment by Nuc3** [comment]
No ideas how to fix this? Is there no one else with that problem?

**Comment by sk89q** [comment]
Watch the launcher/ folder during an update. Does it download a new .jar file there? What are the names of the files in that folder?

**Comment by xion87** [comment]
It don't create any file for me

**Comment by xion87** [comment]
Any news about this issue?

**Comment by sk89q** [comment]
Can you run the launcher jar from the command line, run the update and save the messages. `java -jar launcher.jar` 

Send me the links to your update files.

**Comment by miiichael** [comment]
I'm experiencing the same issue too (which is a little bit problem for me, as the newer launcher has a different packageListUrl). I'd prefer to not tell my users that in order to update, they have to manually locate the downloaded copy of the launcher and delete it...

Looking at [Bootstrap.java](https://github.com/SKCraft/Launcher/blob/master/launcher-bootstrap/src/main/java/com/skcraft/launcher/Bootstrap.java#L84) it seems that if we already have any launcher jars at all in the binaries directory, then launchExisting() is invoked, and the Downloader never gets a look in.

When I run the bootstrap, I can see in my webserver access log three hits (latest.json, news.html, packages.json), which I believe to all be from the launcher rather than the bootstrap. When I invoke the launcher directly, I get the same three hits.

```
[info] Found /home/michael/.camelotlauncher/launcher/1466339250034.jar...
[info] Trying /home/michael/.camelotlauncher/launcher/1466339250034.jar...
[info] Launcher loaded successfully.
[info] Launching with arguments [--dir, /home/michael/.camelotlauncher, --bootstrap-version, 1]
[info] Bootstrap version 1 detected
[info] Using given base directory /home/michael/.camelotlauncher
[info] Cleaning up temporary extracted files directory...
[info] Checking for update...
[info] Enumerating instance list...
*snip instances found*
[info] 11 instance(s) enumerated.
```

As a test, I rendered the existing launcher inoperable (via `chmod 000`). This time the bootstrap fetched latest.json, and the launcher specified therein. Webserver logs show hits to latest.json and the new launcher, in addition to the usual three hits from the launcher itself. The _next_ time I launched the bootstrap, the older launcher was deleted.

**Comment by sk89q** [comment]
Let me know if this is still an issue.

**Comment by norfair00** [comment]
On my ide on launch bootstrap 
```
D:\language\javajdk\bin\java.exe -javaagent:D:\editor\IDEA\lib\idea_rt.jar=55385:D:\editor\IDEA\bin -Dfile.encoding=UTF-8 -classpath D:\language\javajdk\jre\lib\charsets.jar;D:\language\javajdk\jre\lib\deploy.jar;D:\language\javajdk\jre\lib\ext\access-bridge-64.jar;D:\language\javajdk\jre\lib\ext\cldrdata.jar;D:\language\javajdk\jre\lib\ext\dnsns.jar;D:\language\javajdk\jre\lib\ext\jaccess.jar;D:\language\javajdk\jre\lib\ext\jfxrt.jar;D:\language\javajdk\jre\lib\ext\localedata.jar;D:\language\javajdk\jre\lib\ext\nashorn.jar;D:\language\javajdk\jre\lib\ext\sunec.jar;D:\language\javajdk\jre\lib\ext\sunjce_provider.jar;D:\language\javajdk\jre\lib\ext\sunmscapi.jar;D:\language\javajdk\jre\lib\ext\sunpkcs11.jar;D:\language\javajdk\jre\lib\ext\zipfs.jar;D:\language\javajdk\jre\lib\javaws.jar;D:\language\javajdk\jre\lib\jce.jar;D:\language\javajdk\jre\lib\jfr.jar;D:\language\javajdk\jre\lib\jfxswt.jar;D:\language\javajdk\jre\lib\jsse.jar;D:\language\javajdk\jre\lib\management-agent.jar;D:\language\javajdk\jre\lib\plugin.jar;D:\language\javajdk\jre\lib\resources.jar;D:\language\javajdk\jre\lib\rt.jar;B:\lemoutonblanc\Launcher\launcher-bootstrap\out\production\classes;B:\lemoutonblanc\Launcher\launcher-bootstrap\out\production\resources;C:\Users\Nicolas\.gradle\caches\modules-2\files-2.1\com.googlecode.json-simple\json-simple\1.1.1\c9ad4a0850ab676c5c64461a05ca524cdfff59f1\json-simple-1.1.1.jar;C:\Users\Nicolas\.gradle\caches\modules-2\files-2.1\javax.xml.bind\jaxb-api\2.3.0\99f802e0cb3e953ba3d6e698795c4aeb98d37c48\jaxb-api-2.3.0.jar;C:\Users\Nicolas\.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.16.18\557d13dcb647038dc687390711ccb5c9b3ffbd60\lombok-1.16.18.jar;C:\Users\Nicolas\.gradle\caches\modules-2\files-2.1\junit\junit\4.10\e4f1766ce7404a08f45d859fb9c226fc9e41a861\junit-4.10.jar;C:\Users\Nicolas\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.1\860340562250678d1a344907ac75754e259cdb14\hamcrest-core-1.1.jar com.skcraft.launcher.Bootstrap
[infos] Found C:\Users\Nicolas\Documents\The White Sheep\launcher\1532813578307.jar...
[infos] Trying C:\Users\Nicolas\Documents\The White Sheep\launcher\1532813578307.jar...
[infos] Launcher loaded successfully.
[infos] Launching with arguments [--dir, C:\Users\Nicolas\Documents\The White Sheep, --bootstrap-version, 1]
[infos] Bootstrap version 1 detected
[infos] Using given base directory C:\Users\Nicolas\Documents\The White Sheep
[infos] Cleaning up temporary extracted files directory...
[infos] Checking for update...
[infos] Latest version is 1.4.1, while current is 1.4.0
[infos] Update available at https://wsupdate.ndata.li/launcher/versions/1.4.1.jar.pack
[infos] Enumerating instance list...
[infos] 0 instance(s) enumerated.
```

**Comment by miiichael** [comment]
This is still an issue.
