### ISSUE TITLE
[Request] Separated news pages

### ISSUE THREAD

**Issue by elwooha6** [SKCraft/Launcher#152]
Say you are hosting more than one modpack on the launcher, I would like a way to make the news area display a separate page for each pack, selected by clicking on the pack name on the left panel.

Not sure how feasible this would be but it'd make a nice feature/option for people running multiple modpacks.

**Comment by dj3520** [comment]
Duplicate of #61

**Comment by elwooha6** [comment]
Is there anywhere that gives what html works with the launcher? I made a news page that I thought would be simple but apparently the launcher doesn't support iframes.

**Comment by elwooha6** [comment]
Google helped me, sorry for clogging up the issue tracker.
