### ISSUE TITLE
custom urls in modpack creation broken

### ISSUE THREAD

**Issue by Achati** [SKCraft/Launcher#157]
custom urls as described here: [Download from a Custom URL](https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks#download-from-a-custom-url)
seem to not work
i made a script to download mods from curseforge and save the links in .url.txt files
as well as the files, according to the description thats all it needs
the resulting modpack.json is not pointing at the curse urls though

(click to open details)
<details> 
  <summary>folderstructure: `tree mods`</summary>
   ```
mods
├── ActuallyAdditions-1.10.2-r62.jar
├── ActuallyAdditions-1.10.2-r62.jar.url.txt
├── Bagginses-1.10.2-3.0.4b.jar
├── Bagginses-1.10.2-3.0.4b.jar.url.txt
├── BloodArsenal-1.10.2-2.0.1-11.jar
├── BloodArsenal-1.10.2-2.0.1-11.jar.url.txt
├── BloodMagic-1.9.4-2.0.4-58.jar
├── BloodMagic-1.9.4-2.0.4-58.jar.url.txt
├── Botania-unofficial.r1.8-320.jar
├── Botania-unofficial.r1.8-320.jar.url.txt
├── Chisel-2.9.5.11.jar
├── Chisel-2.9.5.11.jar.url.txt
├── chiselsandbits-12.1.jar
├── chiselsandbits-12.1.jar.url.txt
├── CorrelatedPotentialistics-1.1.3.jar
├── CorrelatedPotentialistics-1.1.3.jar.url.txt
├── deepresonance-1.10-1.2.2.jar
├── deepresonance-1.10-1.2.2.jar.url.txt
├── ElecCore-1.9.4-1.5.311.jar
├── ElecCore-1.9.4-1.5.311.jar.url.txt
├── EnderCore-1.10.2-0.4.1.53-beta.jar
├── EnderCore-1.10.2-0.4.1.53-beta.jar.url.txt
├── EnderIO-1.10.2-3.0.1.100_beta.jar
├── EnderIO-1.10.2-3.0.1.96_beta.jar.url.txt
├── hopperducts-mc1.9.4-1.4.7.jar
├── hopperducts-mc1.9.4-1.4.7.jar.url.txt
├── industrialcraft-2-2.6.37-ex110.jar
├── industrialcraft-2-2.6.37-ex110.jar.url.txt
├── ironchest-1.10.2-7.0.9.796.jar
├── ironchest-1.10.2-7.0.9.796.jar.url.txt
├── jei_1.10.2-3.9.0.246.jar
├── jei_1.10.2-3.9.0.246.jar.url.txt
├── journeymap-1.10.2-5.2.4-unlimited.jar
├── journeymap-1.10.2-5.2.4-unlimited.jar.url.txt
├── JustEnoughResources-1.10.2-0.4.9.50.jar
├── JustEnoughResources-1.10.2-0.4.9.50.jar.url.txt
├── Mantle-1.10.2-0.10.4.jar
├── Mantle-1.10.2-0.10.4.jar.url.txt
├── mcjtylib-1.10-1.9.9.jar
├── mcjtylib-1.10-1.9.9.jar.url.txt
├── ProgressiveAutomation-1.10.2-1.6.50.jar
├── ProgressiveAutomation-1.10.2-1.6.50.jar.url.txt
├── PSIonicUpgrades-r1.13.jar
├── PSIonicUpgrades-r1.13.jar.url.txt
├── Psi-r1.0-39.jar
├── Psi-r1.0-39.jar.url.txt
├── Quark-r1.0-55.jar
├── Quark-r1.0-55.jar.url.txt
├── RebornCore-1.10.2-2.6.2.27-universal.jar
├── RebornCore-1.10.2-2.6.2.27-universal.jar.url.txt
├── refinedstorage-0.9.4.jar
├── refinedstorage-0.9.4.jar.url.txt
├── rftools-1.10-5.21.jar
├── rftools-1.10-5.21.jar.url.txt
├── roots-1.10.2-0.112.0.jar
├── roots-1.10.2-0.112.0.jar.url.txt
├── supercraftingframe-1.10.2-1.2.1.87.jar
├── supercraftingframe-1.10.2-1.2.1.87.jar.url.txt
├── TConstruct-1.10.2-2.4.0.jar
├── TConstruct-1.10.2-2.4.0.jar.url.txt
├── theoneprobe-1.10-1.1.0.jar
├── theoneprobe-1.10-1.1.0.jar.url.txt
├── Totemic-1.9.4-0.7.8.jar
└── Totemic-1.9.4-0.7.8.jar.url.txt
``` 
</details>
<details> 
  <summary>filecontent `cat mods/Quark-r1.0-55.jar.url.txt`</summary>
   `http://addons.curse.cursecdn.com/files/2327/670/Quark-r1.0-55.jar`
</details>

**Comment by sk89q** [comment]
I found the problem.

The creator disables URL downloading for testing, but it also affects the build part. I personally build the modpacks via command line automatically so I suppose the issue never has been a problem.

Fixed in 64ed29f9c0d3b3119f1d043e5cefadb15004f49b

**Comment by D3add3d** [comment]
@NikkyAI May I ask for your script? It would be really useful for me

**Comment by NikkyAI** [comment]
well its pretty old and i stopped using them.. but i can see if i have backups

**Comment by NikkyAI** [comment]
@D3add3d i found this mix of tools and scripts https://github.com/NikkyAI/sktools it pulls another repo for curseforge specific stuff
and you can probably adapt this https://github.com/NikkyAI/alpacka-meta to generate the files you want or pull the info from https://curseforge.nikky.moe or https://cursemeta.dries007.net/devinfo although no telling for how long those will be hosted
