### ISSUE TITLE
Openshift website broke | Any other websites?

### ISSUE THREAD

**Issue by StormMusic** [SKCraft/Launcher#160]
I can't sign up with openshift they have closed sign ups to new users.

**Comment by spannerman79** [comment]
@StormMusic what does that have to do with this issue tracker??

**Comment by StormMusic** [comment]
Oh (´･_･`) thought this was where you just report stuff :/

**Comment by ajthemacboy** [comment]
Yes, there are plenty of other websites. The best thing to do for cheap is pickup a cheap VPS from https://lowendbox.com/.

**Comment by sk89q** [comment]
Few free ones though. If you are a student (may or may not have to be college), you can get a year or so free worth of VPS from Digital Ocean.

**Comment by StormMusic** [comment]
@sk89q Okay thanks!

**Comment by SkyBlade1978** [comment]
Just got one from GoDaddy, was 5 pounds a month (cheaper if you pay several months up front), sure not free but 100 gig of storage, php etc and a good control panel
