### ISSUE TITLE
CraftTweaker / Modtweaker support

### ISSUE THREAD

**Issue by lukiono** [SKCraft/Launcher#165]
Is it possible to integrate the "scripts" folder from CraftTweaker into the builds?

As seen here on the screenshot;
![2016-10-21_09-12-56](https://cloud.githubusercontent.com/assets/831436/19589820/d0fa9d4e-976e-11e6-9e97-1d71944bcf75.png)

**Comment by sk89q** [comment]
Just put it into the src folder. 

The launcher is able to sync everything in the src folder and even the mods and config folders are not special at all.

**Comment by lukiono** [comment]
Simple as that =D

Thank you
