### ISSUE TITLE
Having duplicate modpack.jsons in different directories yields unintended consequences

### ISSUE THREAD

**Issue by utoc** [SKCraft/Launcher#166]
This may be an intentional design; if so, please ignore as needed.

My main modpack folder: http://i.imgur.com/PUqYmO0.png

BBQSauce v2 - Copy is an identical copy of my modpack, the previous release, I keep as a benchmark to produce a diff from (to get a changelog).

I had an issue where every time I would edit a certain file, BBQSauce v2/src/config/PressurePipes/client.config, every time it would get overwritten by the previous version in both the build version and in the test instance version.  It was truely maddening.  Deleteing the webserver instance/test instance folder did nothing.  Today I finally figured out the issue.. if you have a second folder with an identical modpack json, it will build a pack from both folders.  Whats weird is that it almost always uses the mods and files in the primary folder.. but every now and then it will pull a random file from the copy directory.. in this case, it used the config in Copy/src/config/PressurePipes.

The issue has popping up and around for quite some time but this is the first time I actually realized what was going on.  The simple solution is to make sure I delete modpack.json in the copy folder from now on.. everything works perfectly if you do that.  Whats weird is that I've NEVER added the Copy directory into Creator.. and that explains why it isn't enumerate. (seen here: http://i.imgur.com/I65BBRL.png)

Anyway.  Reporting this in case there is something you can do besides tell users HEY DONT DO THIS.

**Comment by sk89q** [comment]
I would recommend some version control software to manage versions rather keeping different folders, but I will look into that issue.
