### ISSUE TITLE
url.txt containing spaces or %20 fails to download

### ISSUE THREAD

**Issue by NikkyAI** [SKCraft/Launcher#169]
2 of the mods that i added .url.txt for
refuse to download correctly on linux or windows, it seems to be the only files with spaces in their names
i obviously did escapse the spaces in the url
removing the url.txt solves the issue apparently (but i would relly prefer being able to point every file at cursecdn)

the links that i have problems with are 
Pam's HarvestCraft 1.9.4-1.10.2b.jar
https://addons-origin.cursecdn.com/files/2320/919/Pam's%20HarvestCraft%201.9.4-1.10.2b.jar

and
GraveStone Mod 1.5.5.jar
https://addons-origin.cursecdn.com/files/2320/57/GraveStone%20Mod%201.5.5.jar

i tried removing the spaces from the file, escaping the ' and a few other things, after every deployment to the server i deleted the instance in the launcher too

**Comment by kayila** [comment]
I have both of these in my pack, as well as several other mods with spaces
in their filenames, are you sure you have the correct URL?

**Comment by NikkyAI** [comment]
i just tested and weirdly enough it works fine if the spaces in the url are not escaped
i guess it was the fault of my script
