### ISSUE TITLE
Appears to be missing MercuriusUpdater from forge libs

### ISSUE THREAD

**Issue by gdude2002** [SKCraft/Launcher#170]
This is when installing Forge manually on the server, and using SKCraft's automatic loader stuff. 

* Forge: `1.10.2-12.18.2.2151`

Simply put, the client isn't able to connect to the server.
![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/November/java_2016-11-19_14-52-43.png)

On the server, we have `libraries/net/minecraftforge/MercuriusUpdater` and `libraries/net/minecraftforge/Mercurius`, but this doesn't get created on the client, or in the staging area of the modpack builder.

This seems relatively new - is it just something that the launcher hasn't added support for yet?

**Comment by gdude2002** [comment]
I've asked around the Forge channel on IRC, but nobody responded to my questions so far.

Here's the repo: https://github.com/MinecraftForge/MercuriusUpdater

**Comment by gdude2002** [comment]
I can confirm that adding the lib generated on the server to the client's mods dir fixes this; I think therefore that it's a launcher issue that isn't adding it to the libs

**Comment by sk89q** [comment]
Is the file missing on the server or the client? Both?

**Comment by gdude2002** [comment]
On the client; I haven't tested server deployments since I do that manually

**Comment by sk89q** [comment]
Let me know if this is still an issue.
