### ISSUE TITLE
OpenShift is dead

### ISSUE THREAD

**Issue by Sausagefuff** [SKCraft/Launcher#171]
In the requirement section about creating your own website, the guide to creating a free website through OpenShift has changed. Once you create your account and are ready to create a project there is no longer "PHP 5.4" and is not even an option anymore. There are newer versions, PHP 5.5 and PHP 5.6. Attempting to follow the tutorial is difficult and since the guide is catered to non tech savvy people such, as myself, when the newer PHP versions have different overlays and such. Just a heads up for future reference.

**Comment by SDUBZ** [comment]
also openshift 2 is dying off and becoming openshift 3 at the end of september new tutorial may be required

**Comment by hedgehog1029** [comment]
Might remove the OpenShift wiki page in future but either way the Website Hosting page has been updated recently.
