### ISSUE TITLE
Modpack Creator 2.0.1 Still attempts to download JLine from central.maven.orq

### ISSUE THREAD

**Issue by Routhinator** [SKCraft/Launcher#172]
Whenever I try to build or test a modpack with the 2.0.1 release of Modpack Creator, it is trying to download files from central.maven.org.

The launcher builder is updated and going to the correct place, but not the modpack creator itself.

Seems like #122 did not make it into the 2.0.1 release.

**Comment by sk89q** [comment]
2.0.1 is a bit dated and I haven't gotten around to updating it.

If you already have the launcher downloaded and you've run Gradle, you can find the latest modpack creator in the creator-tools/build/libs folder.

**Comment by Routhinator** [comment]
Yes I _just_ figured this out. Using the built one. There should be a note in the Initial Steps wiki about this. 

That'll teach me to blindly follow directions. :)

**Comment by AutisticMC** [comment]
agree

**Comment by hedgehog1029** [comment]
Releases have been removed & wiki does mention this.
