### ISSUE TITLE
Launching the modpack always updates and overwrites local files

### ISSUE THREAD

**Issue by cosmicdan** [SKCraft/Launcher#176]
Whenever I start a modpack via the launcher, it will always check for updates and overwrite *any* of the local files that differ from the original.

This is a pretty clumsy way to go about things. Files can contain client-specific config (e.g. GUI or rendering configuration) and the only way around it is to add it to the user-files include list. But doing this will then, I assume, prevent updates to that file when the modpack actually has updated that file.

**Comment by Nincodedo** [comment]
Any client specific configs should be separate from general configs. If they're not you should talk with the author of that mod. This isn't really something the launcher can fix.

**Comment by sk89q** [comment]
What you're suggesting involves doing diff of changes and dealing with merge conflicts. It's not simple and even things like Git requires human intervention.

**Comment by cosmicdan** [comment]
I completely agree @Nincodedo, though sadly mod developers can be pretty stubborn.

I've not been able to figure out how exactly the download/update process works, but I was thinking this could be done relatively simply by caching each hash=filename keypair on the client side and only overwriting files when the hash for a given filename has changed. Have I misunderstood how that objects/indexes system works?

**Comment by sk89q** [comment]
If you do that, you still end up completely wiping the user's settings every time you do an update.

Here's the code that determines if a file should be overwritten:
https://github.com/SKCraft/Launcher/blob/64ed29f9c0d3b3119f1d043e5cefadb15004f49b/launcher/src/main/java/com/skcraft/launcher/model/modpack/FileInstall.java#L76

**Comment by cosmicdan** [comment]
Well, it would only overwrite the file if it isn't listed in user files include list.

Ok, thanks - looking at that code, I was thinking that instead of recalculating existingHash, instead just remember the original hash for the file and compare against that. Some kind of "forced update" would ignore cached hashes, though. Or the user could manually delete files from the instance if they wish it/them to be reset to their defaults again, regardless of the presence of a modpack update.

I could maybe work something out and do a PR if you like. But I'm guessing you'd much prefer this behavior to be applied on a per-file basis (i.e. a "lazy include" list) rather than by default with exclusions (e.g. a "force updates" list) whereas I'd prefer the latter - so maybe some kind of checkbox to toggle between the two behaviors...?

**Comment by sk89q** [comment]
It should already not update files that were not changed. The last line checks if the version/hash has changed. In versions 3.x and below of the launcher, it definitely did not update a file unless it was updated in the pack, and this behavior should be inherited in the current version of the launcher.

**Comment by cosmicdan** [comment]
Oh. Well this is embarrassing.

I just tested again (removed a few config files from userfile include list) and it is indeed working as intended - the launcher is not overwriting files. I swear it did at one stage - must have had a hash change on the remote that I never noticed for whatever reason.

This was my original request, it's already resolved. Sorry for the misunderstanding :)
