### ISSUE TITLE
Java error when starting a Minecraft Modpack

### ISSUE THREAD

**Issue by xXDrafterXx** [SKCraft/Launcher#178]
To report this error, please provide:

java.io.FileNotFoundException: .\instances\woodclapper\manifest.json (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.saveContent(HttpRequest.java:509)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:89)
	at com.skcraft.launcher.update.Updater.update(Updater.java:141)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

What can i do?

**Comment by sk89q** [comment]
Is this a vanilla or modded modpack?

**Comment by EmanYm** [comment]
I get this error as well.

I get it after I have uploaded my example files to my web host, edited the launcher.properties at `launcher/src/main/resources/com/skcraft/launcher` to point to the appropriate files on my host and recompiled (`Testing the Changes` step on [this](https://github.com/SKCraft/Launcher/wiki/Initial-Steps) guide.)
A box appears that looks like [this](https://i.gyazo.com/31794c0f1f5a84bb62c6ced55d266b3c.png) and I can't figure out why.
When I search the SKCraft folder for `manifest.json` I get a single file, `Instance.java` which contains this block:

>     /**
>     * Get the file for the package manifest.
>     *
>     * @return the manifest path, which may not exist
>     */
>    @JsonIgnore
>    public File getManifestPath() {
>        return new File(getDir(), "manifest.json");
>    }

The line that references the manifest.json in `launcher/src/main/resources/com/skcraft/launcher` has 'versionManifestUrl=https://s3.amazonaws.com/Minecraft.Download/versions/%1$s/%1$s.json' which can not be viewed by my browser when I remove the "versionManifestUrl=" and "%1$s/%1$s.json" from the url (it downloads a 0kb file)

Also.  No `manifest.json` appears inside the jar, only a `\META.INF\MANIFEST.MF` which contains the following
>Manifest-Version: 1.0
>Main-Class: com.skcraft.launcher.Launcher

Not sure if it matters, but I noticed [the guide](https://github.com/SKCraft/Launcher/wiki/Initial-Steps) uses `v4.2.3-SNAPSHOT` and the version that is used when I go to the locations mentioned is `v4.3-SNAPSHOT`

**Comment by jtrent238** [comment]
Are you running the file from a secure location such as `C:\` or `C:\Program Files\`? If so that is why try running it from desktop.

**Comment by EmanYm** [comment]
My downloaded SKCraft package is in \downloads\Launcher-master\ (default, I just unpacked it to downloads), and the mod pack I put together with the builder is default (\Documents\SKCraft\<mod name>\src\mods

I have also achieved getting Forge to load.  I just had the wrong jar file.
