### ISSUE TITLE
Setting PermGen/max heap size on a per-modpack basis

### ISSUE THREAD

**Issue by Slind14** [SKCraft/Launcher#18]
Hey,

is it possible to define different java args per modpack? We have 2 modpacks that don't run on 32bit systems but I don't want to force everyone to change the settings if they don't have a 64bit system.

**Comment by Penagwin** [comment]
We could just move their placement around mabye?

**Comment by hedgehog1029** [comment]
Was fixed a while back when I added instance-specific settings.
