### ISSUE TITLE
Forge + Liteloader = Crash

### ISSUE THREAD

**Issue by EmanYm** [SKCraft/Launcher#180]
Greetings.

I am wondering if there is a way to load LiteLoader before Forge.  As Mumfrey puts it [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290155-liteloader), you need to install Forge before LiteLoader.

[The guide](https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks#adding-mods) says I can put Forge installer and LiteLoader installers into \loaders.
The `README.txt` in the sample-files folder states:
>You'd put Forge and LiteLoader installers here.
>i.e. forge-1.7.10-10.13.0.1208-installer.jar
>It should NOT be the Windows version of the installer.
>Any installer will work that has a supported "install_profile.json" in its .jar.

Both of the installer .jar files I downloaded have the install_profile.json
`forge-1.10.2-12.18.3.2221-installer.jar`
`liteloader-installer-1.10.2-00.jar`

When I hit **Test** on the modpack creator with LiteLoader in the launchers folder I get [this](http://pastebin.com/P66Uza3L) in my test console.
However, if I remove the LiteLoader jar[ it loads minecraft with no errors](http://pastebin.com/QWRiYVk0).

The few .liteloader files I have will not be missed if I have to go without LiteLoader, there is a[ forge version of WorldEditCUI](https://mods.curse.com/mc-mods/minecraft/242932-worldeditcui-forge-edition) that works perfectly.

**Comment by spannerman79** [comment]
Your log shows that you are trying to add SpongeForge.  That is a **server side mod**. Not client.  You cannot mix server only mods with client only mods.

This is not a launcher issue.

**Comment by EmanYm** [comment]
Yea, I realized that after, then forgot where I put this post.  Sorry about that.
