### ISSUE TITLE
LWJGL Java Error on startup / testing modpack

### ISSUE THREAD

**Issue by sgreiner** [SKCraft/Launcher#181]
Hello,

since I upgraded from Java 8 Update 51 to Update 121 I get this error when I test an modpack in the modpack creator or try to start a modpack in the launcher.
It didn't happen with update 51. Also I can run the modpack from the Mojang launcher directly.

> [00:01:21] [Client thread/ERROR]: Couldn't set pixel format
> org.lwjgl.LWJGLException: Pixel format not accelerated
> at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:574) [bes.class:?]
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431) [bes.class:?]
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) [bes.class:?]
> at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> [00:01:22] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----
> // Everything's going to plan. No, really, that was supposed to happen.
> 
> Time: 2/19/17 12:01 AM
> Description: Initializing game
> 
> org.lwjgl.LWJGLException: Pixel format not accelerated
> at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
> at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
> at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
> at org.lwjgl.opengl.Display.createWindow(Display.java:306)
> at org.lwjgl.opengl.Display.create(Display.java:848)
> at org.lwjgl.opengl.Display.create(Display.java:757)
> at org.lwjgl.opengl.Display.create(Display.java:739)
> at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:594)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
> at net.minecraft.client.main.Main.main(SourceFile:124)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
> at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
> at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
> at org.lwjgl.opengl.Display.createWindow(Display.java:306)
> at org.lwjgl.opengl.Display.create(Display.java:848)
> at org.lwjgl.opengl.Display.create(Display.java:757)
> at org.lwjgl.opengl.Display.create(Display.java:739)
> at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:594)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431)
> 
> -- Initialization --
> Details:
> Stacktrace:
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
> at net.minecraft.client.main.Main.main(SourceFile:124)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.11.2
> Operating System: Windows 10 (amd64) version 10.0
> Java Version: 1.8.0_121, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 1416848080 bytes (1351 MB) / 1601699840 bytes (1527 MB) up to 3817865216 bytes (3641 MB)
> JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024M -Xmx4096M -XX:MaxPermSize=256M
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> FML: 
> Loaded coremods (and transformers): 
> Launched Version: 1.11.2
> LWJGL: 2.9.4
> OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> GL Caps: 
> Using VBOs: Yes
> Is Modded: Definitely; Client brand changed to 'fml,forge'
> Type: Client (map_client.txt)
> Resource Packs: 
> Current Language: ~~ERROR~~ NullPointerException: null
> Profiler Position: N/A (disabled)
> CPU: <unknown>
> [00:01:22] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\zzz\Documents\MineCraft\.modpacks\staging\launcher\instances\gow\minecraft\crash-reports\crash-2017-02-19_00.01.22-client.txt
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0

**Comment by spannerman79** [comment]
That is an error based on the type of graphics system you are running.
**The mojang launcher uses java below 8u60**

http://hopper.minecraft.net/help/pixel-format-not-accelerated/

Non launcher issue - issue with your own hardware (basically update your hardware)

**Comment by sk89q** [comment]
Update your graphics driver.

**Comment by sgreiner** [comment]
The graphics driver was updated three days ago to 378.66 and that was the problem: during the update something went wrong.
We got it to work now...

**Comment by dj3520** [comment]
@sgreiner If you're using nvidia drivers than I can say I've seen this too. The weird issue that I think @sk89q  should know is that even while I was having this issue, the vanilla launcher still worked. But it's now fixed for me with an update to the graphics driver.

**Comment by dj3520** [comment]
I'm actually using a terribly old version of the vanilla launcher.
`Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121`
