### ISSUE TITLE
Additional News pages?

### ISSUE THREAD

**Issue by EmanYm** [SKCraft/Launcher#182]
I have a main pack for players and a hidden pack for staff that requires a key to get.

Is there a way to have additional "News" pages for staff, or a part of it that only shows up if the correct key is entered, like it is with the locked packs?

**Comment by spannerman79** [comment]
Possible dupe #61

**Comment by EmanYm** [comment]
I didn't search past the first page or the closed tickets, and didn't realize this was already suggested.  Sorry.

**Comment by spannerman79** [comment]
If you don't need this issue open anymore then please close it.
