### ISSUE TITLE
"The system cannot find the path specified"

### ISSUE THREAD

**Issue by EmanYm** [SKCraft/Launcher#183]
I'm still having the same issue as #178.

The error window has:
".\instance\\[modpack]\manifest.json (The system cannot find the path specified)"
then in the error details:
>To report this error, please provide:
>
>java.io.FileNotFoundException: .\instances\\[modpack]\manifest.json (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.saveContent(HttpRequest.java:509)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:89)
	at com.skcraft.launcher.update.Updater.update(Updater.java:141)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I used [this](https://github.com/SKCraft/Launcher/archive/master.zip) source from the "Compiling the Launcher" step on the wiki's "[Initial Steps](https://github.com/SKCraft/Launcher/wiki/Initial-Steps)" page
I unpacked/compiled the source in `\downloads` and my work space is in `\documents`
Forge 2221 in the loaders folder
four mods in the src folder, all with a "universal" tag

I've been trying to figure out for the last three days what's wrong, and started over four times.  I've followed the steps as best as I can and I still get the error each time.

I'm just wondering if my file host has anything to do with it.  It's labled as "potentialy unreliable" in [your list](https://github.com/SKCraft/Launcher/wiki/Website-Hosting).
Is it possible to host the required files on my own machine for a more reliable and manageable service?

**Comment by EmanYm** [comment]
Does it perhaps have something to do with [this](https://github.com/SKCraft/Launcher/wiki/Custom-Version-Manifest) and `latest.json`?

Latest.json (also found in "[Configuring Self Update](https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update#latestjson)")
>{
    "version": "4.0.1",
    "url": "http://example.com/launcher/versions/4.0.1.jar.pack"
}

None of the `build.gradle` files have "4.0.1" in them.  The closest is a `4.3-SNAPSHOT` in the root's build.gradle.
There are so many things that are unclear to someone that's not familiar with java on the bootstrap guide.

**Comment by EmanYm** [comment]
Does no one have any insight or advice to fix this?

It's been reported on the forum as far back as [2016](http://forum.enginehub.org/threads/missing-manifest-json.16814/) with no replies and [2015](http://forum.enginehub.org/threads/manifest-json-not-found.16118/) with no resolution.

- I'm running a custom mod pack (not the default `lightpack` or `monsterpack`)
- I'm running the launcher directly (\Downloads\Launcher-master\launcher\build\libs\launcher-4.3-SNAPSHOT-all.jar and fancy launcher).
- I have not run the bootstrap program yet (I want to have this working before I bootstrap it).
- The launcher finds the pack hosted on the site with no problem.
- This error comes when I try to download the mod pack, after I've logged in to Minecraft.
- There is no manifest.json in the `\_upload\` folder.
- There is a `[pack name].json` for each of the modpacks and `packages.php` in the workspace for my pack.  How would I point at these files instead of manifest?

Like I said before, I tried to figure this out for a week before I posted a reply on issue 178 ten days ago.
If I need to run the bootstrap program I'll need some help, I don't find the instructions very clear.

**Comment by dj3520** [comment]
>I'm running the launcher directly (\Downloads\Launcher-master\launcher\build\libs\launcher-4.3-SNAPSHOT-all.jar and fancy launcher).

Suggest moving it somewhere else.

>There is no manifest.json in the \_upload\ folder.

That's significant. There should be a packages.json that looks [a bit like mine](http://net.dj3520.net:8000/smc-loader/packagesjson.btm) which tells the launcher what packs are avalible and what versions they are. It also says where the manifest.json is for that pack.

>There is a [pack name].json for each of the modpacks and packages.php in the workspace for my pack. How would I point at these files instead of manifest?

The packages.json needs to reference them on the "location" line.

**Comment by EmanYm** [comment]
> Suggest moving it somewhere else.

I wasn't having an issue compiling, making packs or running the launcher from \Downloads
Would `C:\Program Files\SKCraft` work?
I plan on restarting from scratch (again) so I can move it if I need to.

> There should be a packages.json

There is, or rather `packages.php`  I have php support on the chosen host.
How do I make the launcher look at that instead of manifest.json?  Or can I just rename "packages" to "manifest" and trick it into working that way (I doubt this would work though)?

I have my files on my host:
> public_html
> -launcher (where I will be putting the launcher for people once I run bootstrap)
> -packs (where I am putting the modpacks from the _upload folder)
> --libraries
> --objects
> --packages.json
> --news.html
> --latest.json
> --packages.php
> --[packname].json (one for each pack)

I'm wondering if I could move it from "public_html" folder to "SKCraft_" folder on my host.

**Comment by dj3520** [comment]
>Would C:\Program Files\SKCraft work?

Program Files requires admin privileges, so somewhere else. Making a folder in your documents is what I'd do for right now. The bootstrap ends up doing this anyway.

>How do I make the launcher look at that instead of manifest.json?

https://github.com/SKCraft/Launcher/wiki/Initial-Steps#customizing-the-launcher

>I'm wondering if I could move it from "public_html" folder to "SKCraft_" folder on my host.

Simply change the urls in the above step.

**Comment by EmanYm** [comment]
Thank you for your time, @dj3520
I'll do a quick test later today and reply if it worked.

**Comment by dj3520** [comment]
@EmanYm No problem. I've actually got my own sort of auto-system for everything after I set it up. I build a modpack, it gets uploaded and the manifest gets changed automatically.

**Comment by EmanYm** [comment]
So now I have main build running from "\Documents\SKCraft"
The packs I made are in "\Documents\SKCraft Workspace"
and I will be sending the bootstrap results to "\Documents\SKCraft Launcher"

The version should correspond to the version in build.gradle


I'm working on setting up the bootstrap, and I'm stuck on [this step](https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update#latest.json).
> The version should correspond to the version in build.gradle (in the source code). Change "4.0.1" to whatever version is in build.gradle at the moment.

Which `build.gradle` does this refer to?

**Comment by spannerman79** [comment]
Read the actual file https://github.com/SKCraft/Launcher/blob/master/build.gradle#L25

**Comment by EmanYm** [comment]
What I was saying is it doesn't specify which build.gradle in the guide.
https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update#latestjson

There are six `build.gradle` files in my main folder, each with a different number
- One in the main source (root) folder
- one in \launcher
- one in \launcher-fancy
- one in \launcher-builder
- one in \launcher-bootstrap
- and one in \creator-tools

If you are meant to look at the one in the root folder it should say that in the guide.

Once I find the correct build.gradle which number do I need?
(from the root build.gradle)
- The one from `dependencies`
> dependencies {
classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.0'
}

- or the one from `subprojects`
> version = '4.3-SNAPSHOT'
>
>sourceCompatibility = 1.6
targetCompatibility = 1.6

If it's `subprojects.version` then it doesn't follow the guide
> Unlike the package/modpack version, this version must be a proper version string (X.Y.Z)

I'm going to have more questions about the `.jar.pack` step once I can get past `latest.json`



The guide may be obvious to someone that knows what they're doing.  I haven't done programming of any kind for around ten years so I've lost a lot of what I used to know, and there are likely younger kids trying to get this to work that can't comprehend some of the instructions.

I understand that the people in charge of the guide may not have the time to work on the guide, but a more precise "SKCraft for Dummies" style guide is needed.

**Comment by dj3520** [comment]
It's the one in root, and despite having "SNAPSHOT" in it, a numerical version is required. I'd change it to 0.0.x for now since you're just playing around with it. It needs to be (somewhat) numerical because the bootstrap looks for a higher version number.

>I'm going to have more questions about the .jar.pack step

the .jar.pack file is just what the bootstrap downloads and runs. It's really just the launcher.

**Comment by EmanYm** [comment]
> It's really just the launcher.
Can I bypass all the bootstrap nonsense and just upload the (uncompressed) launcher?  From what I can tell, the only reason for it is auto-updates of the launcher.

**Comment by sk89q** [comment]
Yes. Sorry I haven't been able to look at this. I haven't been available much.

**Comment by EmanYm** [comment]
@sk89q No worries, SK.  I always tell people that life should always come first.

**Comment by Guatas** [comment]
Hello, I have a player with the exact same problem.. But it's weird as long as he is for now the only one getting this issue..

Everyone is downloading the modpack easily and get automatic upgrades.. We are not using bootstrapper by the way.

**Comment by sk89q** [comment]
Let me know if this is still an issue.

**Comment by Tokeli** [comment]
Still having this issue myself. Confusingly, it's an issue only for a single person. Every single person just makes a folder in their Downloads, drags the launcher in, and runs it. This one person gets the manifest problem. Even other completely-new people trying afterwards have no trouble.

**Comment by spannerman79** [comment]
> Confusingly, it's an issue only for a single person

What OS is that single person on?  Do they have any sort of space accountancy system running that would prevent over usage? (Typical for Win10 + Win7 on a system where more then one user).

What I do is I distrubte a zip where the bootstrap jar is within a directory.
```
- Name_of_Launcher
------------------ bootstrap.jar
------------------ portable.txt
```

Then I say make sure it is in a location that you have full read and write access. For windows users best is in My Documents, linux is home, Mac not sure of (don't have any mac users)
