### ISSUE TITLE
How does the .url.txt work?

### ISSUE THREAD

**Issue by EmanYm** [SKCraft/Launcher#184]
On the `Creating Modpacks` page of the wiki it states
>You can have select mods be downloaded from a URL other than your website where you will host the modpack.

I've noticed I actually need to have the .jar to run a Test of the pack.  Does it pack the .jar when I hit Build, or does it pack the .txt, and then download the .jar the first time it's selected in the launcher?  Some of the mods I will be using request I don't include the .jar file in the pack.

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks#download-from-a-custom-url

**Comment by EmanYm** [comment]
I was hoping it would be more along the lines of not needing the .jar, and it would wait until the user selected that optional mod before downloading from the address in the .url.txt.  That would save space on the host.

I guess that answered my question.  Mind if I close this, or should I leave it open in case someone else has the same type of question?

**Comment by spannerman79** [comment]
> I was hoping it would be more along the lines of not needing the .jar, and it would wait until the user selected that optional mod before downloading from the address in the .url.txt. That would save space on the host.

Its needed for hash checking.

Close the issue if its resolved. You don't leave opened issues if the issue has been resolved.
