### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by EmanYm** [SKCraft/Launcher#191]
I noticed the last source update was 10+ months ago.  Most areas are two years old.  Is SKCraft a dead project?  or is there a chance SK (or someone) will have time to update it in the near future?

**Comment by sk89q** [comment]
I won't say anything for sure, but this iteration of the launcher was put together in a few days, so it may survive at least any smaller changes.

**Comment by EmanYm** [comment]
I would really love to get back on to SKCraft.  I've been having issues with outdated files being downloaded (jline 2.13 instead of 3.0).

I like the robustness of SKCraft over some other better known launchers.

**Comment by spannerman79** [comment]
> I've been having issues with outdated files being downloaded (jline 2.13 instead of 3.0).

Elsewhere in another or other issues it was stated that this launcher is meant to be compatible with Java 6. jline 3 is Java 8.  That would break backwards compatibility for Java 6,  https://github.com/SKCraft/Launcher/blob/master/build.gradle#L27

**Comment by EmanYm** [comment]
I see.  I will tell my brain to stop screaming at me about outdated files. 😛 
Thanks for the information, Spannerman

**Comment by sk89q** [comment]
The files that the launcher downloads for the game doesn't affect what the launcher uses though.

**Comment by sk89q** [comment]
Well I pushed a commit, lol.
