### ISSUE TITLE
First mod install should download a zip

### ISSUE THREAD

**Issue by aequasi** [SKCraft/Launcher#193]
On the first install of a modpack, it should download a zip of the modpack, instead of each of the files. Would drastically cut down the initial download time.

**Comment by Nincodedo** [comment]
Then you would need to host two sets of files, the zip and all the individual mods/configs.

**Comment by aequasi** [comment]
Thats fine. Give the option to do it.

**Comment by spannerman79** [comment]
> On the first install of a modpack, it should download a zip of the modpack, instead of each of the files. Would drastically cut down the initial download time.

This would directly conflict with some mod dev requirements that their mod **must** be downloaded via CurseCDN.

**Comment by aequasi** [comment]
It is still via CurseCDN, just packaged up. Its no different than downloading the mod through this launcher. Its downloaded by the launcher, via CurseCDN

**Comment by spannerman79** [comment]
> Its downloaded by the launcher, via CurseCDN

That would require the complete modpack to be on the CurseCDN in a single zip/compressed format - which again is against many mod developers wishes as they want their mod to be downloaded directly for stats etc. 

 Not even curse hosted modpacks are complete zips of **all** the mods. They have a manifest that downloads the required mod files one by one.

**Comment by sk89q** [comment]
I won't be doing this because it's a lot of work for I think not a lot of gain.
