### ISSUE TITLE
Error with launching 1.10.2

### ISSUE THREAD

**Issue by Frontrider** [SKCraft/Launcher#199]
I get this error while trying to test the pack.

https://pastebin.com/ZLFpcy9x

No files are corrupted tough. The mods are from the direwolf20 pack, the installer works on its own.
Where should I look in terms of this error?

**Comment by sk89q** [comment]
Is the MC version 100% right in the modpack properties?

**Comment by Frontrider** [comment]
fixed, and now I feel dumb.
