### ISSUE TITLE
Bootstrap Lang Files are Overwritten on Build

### ISSUE THREAD

**Issue by yayes2** [SKCraft/Launcher#200]
I'm trying to brand the launcher and the launcher lang file works fine, but the launcher-bootstrap lang file is overwritten on build so my changes are never saved.

I'm editing launcher-bootstrap\build\resources\main\com\skcraft\launcher\lang\Bootstrap.properties. Is there a different file to edit?

**Comment by sk89q** [comment]
You need to edit the files in src/
