### ISSUE TITLE
Support for 1.4.7

### ISSUE THREAD

**Issue by StrayanDropbear** [SKCraft/Launcher#202]
Hello, I've tried making a modpack on 1.4.7 but it doesn't start (vanilla) 

Does it work with older versions of minecraft?

**Comment by spannerman79** [comment]
Client Logs?

**Comment by StrayanDropbear** [comment]
Hmm, it was giving me an NPE every-time i started it. 

Restarted the modpack creator and now it starts.. odd

**Comment by StrayanDropbear** [comment]
Another question, how would I get forge working on 1.4.7? they didn't make installers back then, only the universal zips.

**Comment by spannerman79** [comment]
From memory modding in 1.4.7 you need to modify the actual minecraft.jar.  I don't think this launcher can insert files into the minecraft.jar automatically.

In fact I think many people would have issues running 1.4.7 modded due some changes with java 8.  You cannot obtain older versions of java (windows users) via oracle unless you have a service agreement with them.

Personally if you want to use legacy modded MC I wouldn't go back further then 1.6.4 - but that is my personal point of view.

**Comment by EmanYm** [comment]
There is [a site](http://www.oldversion.com/) that archives old versions of software, [including Java](http://www.oldversion.com/windows/java-platform/).

**Comment by sk89q** [comment]
I dropped in SKCraft's 1.4.7 pack and it loaded. I used `custom_jar.jar` but we made that way back then.

The more troublesome issue is that it seems to read from the .minecraft folder... if anyone knows what the fix for that is, let me know.

![image](https://user-images.githubusercontent.com/38949/29478990-a2fd3dea-8424-11e7-9de6-d5c9f2a1f3b1.png)

**Comment by sk89q** [comment]
Commit f9a728dcd66e1ed76f352768c16b88480f46dc9f fixes it reading from `.minecraft`! ...at least for 1.4.7.

**Comment by sk89q** [comment]
p.s. I can send you my 1.4.7 jar if you want. Just remember to remove the SKCraft loading screen + random messages + background if you care.

Also you'd need to deploy a new version of the launcher with the update.

**Comment by StrayanDropbear** [comment]
all good, I managed to get my own jar working. Cheers for the update :) 1.4.7 works perfectly for me now.

**Comment by StrayanDropbear** [comment]
Hmm, when I try and install it through the launcher (not creator tools) I get this error:
https://gist.github.com/StrayanDropbear/a38a595875e41eaab94f219fa5049078

**Comment by sk89q** [comment]
That looks like an unrelated issue with the JSON files being corrupted. Try reuploading them?

**Comment by StrayanDropbear** [comment]
Yeah re-uploading fixed it, Thanks for the help 👍
