### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by i9hdkill** [SKCraft/Launcher#207]
Java 9 brings "some" changes to JavaFX.

Including HighDPI support.

As the launcher refuses to load on Java 9, which is now recommended and distributed anywhere, an update would be a nice thing.

Maybe it's easier to make the launcher work on Java 9 first, than implementing HighDPI + Java 9 support at the same time. So probably update in two steps:
- Basic support for Java 9(Including backwards comp. for Java 8)
- (If you have time) High dpi support

Thanks in advance!

**Comment by spannerman79** [comment]
> Java 9, which is now recommended and distributed anywhere

Distributed anywhere - true

Now recommended - not true.

I actually had an argument over this in another discord server - the average person (aka John/Jane Doe) go's to java.com.

From Java.com
>Recommended Version 8 Update 144

So while I agree that Java 9 does provide some changes it is **not** the recommended to the average user.

**Comment by i9hdkill** [comment]
You might be right that Java 8 is still recommended, but keep in mind that Java.com is not always up to date and it recommends Java 32 Bit for 64 Bit Browsers/PCs... 
Anyway, if people type Java Download in Google, they often land on third party sites which provide Java 9. So even if it's not officially recommended, people will install it(Instead of Java 8). This will lead to problems quite quickly.

**Comment by spannerman79** [comment]
> Anyway, if people type Java Download in Google

https://www.google.com/search?q=java+download on chrome gives me this;

![chrome_java_google](https://user-images.githubusercontent.com/7542384/30948562-227281da-a454-11e7-86cb-e86ee4f2a941.PNG)

Using the dreaded Edge using Bing (default for new computers having Windows 10) gives me this;

![java_edge_win10](https://user-images.githubusercontent.com/7542384/30948623-85dd8ff8-a454-11e7-8e68-82df8585d155.PNG)

I'd say your premise is a little...off...when it comes to what people get when they search for "java download"

**Comment by sk89q** [comment]
Fixed
