### ISSUE TITLE
Empty Files

### ISSUE THREAD

**Issue by Pulverizer** [SKCraft/Launcher#209]
When processing a modpack for uploading it also creates hashes for empty files which can cause issues when using hosts like github that don't like empty files and cause the launcher to error due to the file being not found.

Simple fix: Don't hash empty files.

**Comment by dj3520** [comment]
This is possibly a dumb question, but why are there empty files in your modpack?

**Comment by sk89q** [comment]
What does GitHub do

**Comment by Pulverizer** [comment]
@dj3520 empty configs, ask the mod developers
@sk89q github doesn't keep empty files, aka deletes them

**Comment by wizjany** [comment]
github definitely allows empty files.

**Comment by Pulverizer** [comment]
@wizjany it doesn't let me upload them. Well it does but then they were instantly deleted.

**Comment by sk89q** [comment]
Let me know if this is still an issue.
