### ISSUE TITLE
Help no mods in game

### ISSUE THREAD

**Issue by cedmen1** [SKCraft/Launcher#210]
Hello so i have my mods in my modpack folder here : 
[https://gyazo.com/68147cae29d101abc3bc476bd572db7b](url)
But in game its not showing up : 
[https://gyazo.com/56bec41770438af95d5125ee5b7e9c89](url)
In my minecraft the mods are there but not in game : 
[https://gyazo.com/c01f4be0434b70945a03966f7cec4d10](url)

Please someone help !

**Comment by sk89q** [comment]
Your images didn't load for me even if I fixed the link but it's usually because the jars got uploaded in a way that corrupted them.

**Comment by spannerman79** [comment]
Prob not in `binary` mode https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks#upload-everything

**Comment by cedmen1** [comment]
Thanks guys its working now :)

**Comment by spannerman79** [comment]
If your issue is resolved then close the issue @cedmen1
