### ISSUE TITLE
Compiling the editor

### ISSUE THREAD

**Issue by Frontrider** [SKCraft/Launcher#213]
Does it needs to be compiled on the computer where it will be used? 
I sent the one compiled on my linux to my windows friend (he has a hard time with that) and it fails to run.

**Comment by wizjany** [comment]
fails to run how? my first guess would be that you didn't send the artifact with all the dependencies bundled so it's missing those.

**Comment by Frontrider** [comment]
Its supposededly looking for a file called "mccommand.txt" (had a bunch of paths related to the the editor's folders) in a folder which is my home directory. Which can not exist on a windows machine.

**Comment by Frontrider** [comment]
Yeah, while compiling a path is hard coded, and its not noted in the readme.

**Comment by sk89q** [comment]
Let me know if this is still an issue.
