### ISSUE TITLE
Could not determine java version from '9.0.1'.

### ISSUE THREAD

**Issue by Flinner** [SKCraft/Launcher#216]
Hi,

I was trying to build the launcher. However, I got this error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I thought this launcher supports java 9?

**Comment by sk89q** [comment]
The launcher does but Gradle needs to be a newer version. I'll do it when I get chance but you can also install Gradle 4.2+ to your computer and use `gradle` instead of `gradlew` in the instructions.

**Comment by Flinner** [comment]
Thank you for the blazing fast reply! I'll try right now.

**Comment by Flinner** [comment]
It looks like there's a plugin that's outdated from gradle after I changed the gradle-wraper.properties last line to distributionUrl=https\://services.gradle.org/distributions/gradle-4.3.1-bin.zip

`Download https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.0/shadow-1.2.0.jar

> Configure project : 

*******************************************
 You are building SKCraft Launcher! 

 Output files will be in [subproject]/build/libs
*******************************************



FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bofone/Documents/Minecraft Experience/Minetizen Client/Minetizen-Launcher/creator-tools/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':creator-tools'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin']
   > Could not create task of type 'ShadowJar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
`

**Comment by sk89q** [comment]
Uhhh I tried Java 9 and a lot of the build process doesn't seem to be fully working (notably Lombok) so use Java 8 for now.

**Comment by Flinner** [comment]
Thanks! Got it.

**Comment by sk89q** [comment]
Fixed
