### ISSUE TITLE
Bootstrap Java 9 Incompatibility?

### ISSUE THREAD

**Issue by Bo-Fone** [SKCraft/Launcher#217]
I just compiled the bootstrap and decided to distribute using bootstrap. But when I try to open it. I get this error:

To report this error, provide:

java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.skcraft.launcher.bootstrap.HttpRequest.returnContent(HttpRequest.java:199)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:75)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

**Comment by sk89q** [comment]
I haven't tried to fix it but when I investigated this issue the last time,
it's because Java no longer distributes the JAXB library with Java as of 9,
but you can now add the dependency separately and compile/shadow/bundle it
into the .jar.

**Comment by Flinner** [comment]
How do I do that? Would you mind provide me instructions or build script? Thanks a lot!

**Comment by spannerman79** [comment]
@Flinner for now either
Do what @sk89q already suggested via https://github.com/SKCraft/Launcher/issues/216#issuecomment-343800055

or

[A 5 second google search](http://lmgtfy.com/?q=JAXB+library+java+9+gradle) and do some reading.

**Comment by sk89q** [comment]
No need for attitude.

@Flinner <https://github.com/flinner> is trying to run the launcher with
Java 9 now -- not compile it.

I don't have much of a moment right now but you need to find the dependency
for JAXB (i.e. search Maven JAXB is how I'd do it) and add it under
"dependencies {}" in one of the build.gradle files. I believe the build
script is written to automatically include new dependnecies into the final
.jar.

**Comment by Flinner** [comment]
Solved! Added JAXB to the build.gradle for the bootstrap. Thank you so much! However, a new issue come up. The bootstrap successfully downloaded the launcher. But the launcher sort of just hang in there, I can see the "java" runtime icon show up on my dock (macOS), but after awhile without any error message. It disappeared. And no launcher window opened. I think there's still some issue for the launcher to run under Java 9. 

Please let me know how to inspect where the problem might be since it does not give me any error messages. Also, I'm quite inexperienced to programing. But I'm modestly learning, if not, trial and error, to get things working. So please bear with me if I asked some stupid question. XD

**Comment by sk89q** [comment]
Does the launcher work on its own?

**Comment by Flinner** [comment]
I was trying it under my old machine which still had Java 8 on it. The newly compiled bootstrap and launcher does work on the old machine. But still, neither the bootstrap nor the launcher itself will launch in my new machine under Java 9.0.1. They do not give out any error message nor weird stuff XD. It tried to open the launcher by itself. It acts the same as I described in my last comment which the java runtime icon showed up but disappeared after a while without opening any thing nor giving me errors as if it secretly ran and hit a brick then went away.

**Comment by sk89q** [comment]
Can you run it via terminal to see if Java spits out any messages?

**Comment by Flinner** [comment]
Ah, I just searched and tried to do java -jar command, and here is the output. This time it did give me errors in terminal. 

[https://pastebin.com/TUJTJft5](url)

**Comment by Flinner** [comment]
Ah, I just searched and tried to do java -jar command, and here is the output. This time it did give me errors in terminal. 

https://pastebin.com/TUJTJft5

**Comment by Flinner** [comment]
Clicked the wrong button... Sorry..

**Comment by sk89q** [comment]
That error regards the library used to make the dark theme work.

1. You could see if there's a new Java 9-compatible version of Substance.
2. You could see what's wrong.
3. You could use the light theme.

**Comment by kirill-grouchnikov** [comment]
I'm the developer of Substance.

The dependency on Insubstantial is using an old and no longer maintained fork of Substance. The recently released version 7.1 of Substance (Insubstantial got a bit ahead of Substance as far as versions go) should also provide much better support for high-dpi screens, with the only known issue so far being tracked in https://github.com/kirill-grouchnikov/substance/issues/48

If you're interested in tracking the latest stable / dev version of Substance, I'll be glad to take a look at any crashes or visual bugs that are happening.

**Comment by Flinner** [comment]
Hi @sk89q , Just want to know that whether the Java 9 compatibility issue has resolved. @kirill-grouchnikov is the developer of Substance. I brought him here hope that this issue could be solved. If there's something I could do, I would love to help!

**Comment by sk89q** [comment]
I just haven't found time to dedicate to the problem yet.

**Comment by Flinner** [comment]
Got it! Thanks for the reply. Just want to make sure its not forgotten 👍.

**Comment by kirill-grouchnikov** [comment]
Substance 8.0 was released last week FYI. The current release cycle is to have two releases a year, so that would be the timeframe for fixing bugs and getting the fixes into the stable releases.

**Comment by Flinner** [comment]
Yes. Please... We have been waiting for quite some time now. Appreciate the update in advance!

**Comment by sk89q** [comment]
Let me know if it works now.

**Comment by hedgehog1029** [comment]
Fancy launcher should be fixed on modern Java now.
