### ISSUE TITLE
Unable to modify newsUrl in launcher.properties

### ISSUE THREAD

**Issue by Wruczek** [SKCraft/Launcher#218]
First of all, amazing work! And thanks for releasing it for free to the community.

I was trying to change the `newsUrl` in `launcher.properties` to end with `.php` instead of `.html`, so I can use features of PHP, but the file extension is changed back to `.html` every time i build the launcher.

What should I do?

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/News-Page-Guide

Swing web browser is very limited.

**Comment by Wruczek** [comment]
It is, but this problem is not related to Swing in any way. The launcher simply disallows to change file extension in `newsUrl`, but allows it on `packageListUrl`

**Comment by spannerman79** [comment]
Place php tags within the html file. More then one way to skin a cat.

I've found that even then most php driven content doesn't display correctly with swing. 

My news page is a static html document with *very* basic html and css - no php or css3 whatsoever. I *think* and how I feel is that the news page is used to showcase announcements and the sort.  Not for showing complex content.
Things like (example only)

> Good news, just updated xx server to blah blah like everyone voted over on the forum <forum is hyperlinked to said location> please make sure when you select it it updates first before attempting to join

As to the `newsUrl` force rewrite - perhaps its assumed knowledge that isn't documented and revolves around what I hinted towards before? *shrug*

**Comment by Wruczek** [comment]
> Place php tags within the html file. More then one way to skin a cat.

Yes its possible, but many web servers (including mine) are not configured to pass `.html` files to the php preprocessor. They simply output contents of `.html` files to the browser. While making web server parse `.html` files, I still think that I should be able to change the URL however I like it, without it being forced this way.

> My news page is a static html document with very basic html and css - no php or css3 whatsoever

PHP is used on backend and doesnt change the complexity of the site. Its not interpreted on the client side thus it doesnt matter for Swing.

PS. Ive tried going into the builded jar file and changing `com/skcraft/launcher/launcher.properties` file directly here and packing it back to jar, and it works very nicely.

**Comment by sk89q** [comment]
Let me know if this is still an issue.
