### ISSUE TITLE
Adding servers.dat to modpack/launcher

### ISSUE THREAD

**Issue by Velikss** [SKCraft/Launcher#227]
Hello,

I'm currently making a launcher for my server and I was curious if there would be a way to add a pre-defined server-list to the client. So that when a player runs our launcher it already has our servers added to the server-list in his/her client.

**Comment by spannerman79** [comment]
The commit was made so you could do that via a config by the looks of it ( https://github.com/SKCraft/Launcher/commit/21e67328c75850cbaa7a144d4ef3ec7a50fe921e ) although there is no wiki page on it.

Perhaps @me4502 could explain further

**Comment by me4502** [comment]
That’s different to what is wanted. My commit provides the ability to make the launcher automatically send people to a certain server on startup.

**Comment by Velikss** [comment]
That might work aswell, in which config would I do that exactly?

I still want to know how to pre-define the serverlist though. I have seen it in other launchers, I'm assuming I need to place a custom servers.dat somewhere?

**Comment by sk89q** [comment]
You'd have to modify the launcher bootstrap. On don't really recommend it. 

The launcher just copies your modpack wholesale into the Minecraft directory so just put the file whenever MC would put it.

**Comment by Velikss** [comment]
You sure? It seems like my launcher recreates MC and places all the files in <folderwherethelauncherislaunched>/instances/launcher/minecraft

Doesn't seem to interact with my .minecraft folder tbh

**Comment by sk89q** [comment]
Not that Minecraft folder, but the Minecraft folder of the instance.

**Comment by Velikss** [comment]
Alright, then I'll take the other option. @me4502 How do I configure the launcher to send people to a certain server on startup?

**Comment by Aughen** [comment]
What I did to auto-populate my server address for users is log in to the server playing the game from my local machine, it will make a Server.dat file in your Minecraft directory and then put that server.dat file in your SRC directory before you build the pack and it loads every time with my servers

**Comment by spannerman79** [comment]
> What I did to auto-populate my server address for users is log in to the server playing the game from my local machine, it will make a Server.dat file in your Minecraft directory and then put that server.dat file in your SRC directory before you build the pack and it loads every time with my servers. it does not add the servers to the launcher but to the individual mod packs that you make

Yes adding a server.dat will do that @Aughen but what @Velikss is asking relates to https://github.com/SKCraft/Launcher/commit/403f2848b82d127691db529c2a3109373faaf5b7

So there (i assume) no multiplayer select screen or server select screen - the client connects automatically.

**Comment by Aughen** [comment]
OK, that makes sense, I guess I just don't see the benefit in that.

**Comment by spannerman79** [comment]
Well if you have a single pack made up and you only have one server running that uses those mods, its a bit pointless to have a server selection screen when not only mods affect a client but also config file settings also affect the client as well (mismatched biomes, potions etc).

So if you are the only one running that server, why would you include a server.dat when you can have the client automatically join that particular server.

**Comment by Grand-Trizmo** [comment]
just copy the servers.dat from your own client with it premade into the src folder then add it to the include section of the creator
![properties](https://i.triz.moe/1525799846.png)

**Comment by Shoxxo** [comment]
Thanks, this should work ;)

**Comment by sk89q** [comment]
Let me know if this is still an issue.
