### ISSUE TITLE
Missing Guide

### ISSUE THREAD

**Issue by Shoxxo** [SKCraft/Launcher#228]
So, no one in Discord was able to help me. Now i will start this here.

My Question is, how to build the *.jar.pack file for the Bootstrp Launcher? The Guide says nothing about that. Please add the Guide.

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update#creating-the-jarpack

**Comment by Shoxxo** [comment]
To report this error, provide:

java.io.IOException: Failed to find launchable .jar
	at com.skcraft.launcher.Bootstrap.launchExisting(Bootstrap.java:140)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:119)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

**Comment by Shoxxo** [comment]
Reference : https://github.com/SKCraft/Launcher/issues/112

Not Working.

**Comment by AuuuA** [comment]
Open cmd as administrator. go to the /java/JAVAJDK/bin folder And use pack200 command
