### ISSUE TITLE
Latest.json error?

### ISSUE THREAD

**Issue by nacjm** [SKCraft/Launcher#232]
Yes i know this is a duplicate of #204 but it has not been touched since last year and I just got that same issue.

launcher.properties:https://hastebin.com/otexomuqiw.ini
launcher bootstrap.properties:https://hastebin.com/uxofiqawuk.ini
I am getting the same error as #204.

**Comment by spannerman79** [comment]
```
--2018-05-06 20:55:13--  http://aetherionmod.epizy.com/packages.json
Resolving aetherionmod.epizy.com (aetherionmod.epizy.com)... 185.27.134.131
Connecting to aetherionmod.epizy.com (aetherionmod.epizy.com)|185.27.134.131|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-05-06 20:55:15 ERROR 403: Forbidden.
```

Stop using "free" website hosting.

**Comment by nacjm** [comment]
Yeah i realize that now I am now trying github pages and getting a 404.
new bootstrap: https://hastebin.com/taqirigoju.ini
new launcher: https://hastebin.com/orelepasag.ini
any ideas?

**Comment by spannerman79** [comment]
Again, don't use "free" website hosting.

You don't have access to apache/ngnix logs to pin point whats going on.
That is why any free/"free" hosting isn't recommended on https://github.com/SKCraft/Launcher/wiki/Website-Hosting#reliable-but-not-recommended

**Comment by nacjm** [comment]
alright here is the apache log now what: https://hastebin.com/idepisitof.php
bootstrap:https://hastebin.com/adegarajef.ini
launcher:https://hastebin.com/inayesifoj.ini

**Comment by sk89q** [comment]
Let me know if this is still an issue.
