### ISSUE TITLE
Bootstrap not starting when using FancyLauncher.

### ISSUE THREAD

**Issue by JacksonPlayz** [SKCraft/Launcher#233]
Okay, so when I set the launcher it uses to FancyLauncher in the bootstrap properties it spits out this error when trying to run it. I've followed all of the instructions and it works if it is using the non fancy launcher.

java.io.IOException: Failed to find launchable .jar
	at com.skcraft.launcher.Bootstrap.launchExisting(Bootstrap.java:140)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:119)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

When it is set to Launcher it works perfectly but doesn't use the fancy launcher.

**Comment by spannerman79** [comment]
Seeing as no details were given https://github.com/SKCraft/Launcher/wiki/Fancy-Launcher#usage

**Comment by JacksonPlayz** [comment]
I did that. When I recompiled it and uploaded the jar.pack and then started it up it spit out the error.

**Comment by sk89q** [comment]
Let me know if this is still an issue.

**Comment by MJRamon** [comment]
I can confirm this issue is still present.

**Comment by hedgehog1029** [comment]
This is caused by failing to follow this step:
> If you are using the bootstrapper, you will also need to change the "launcherClass" property in the bootstrap properties file
