### ISSUE TITLE
Will this work for Mac OS?

### ISSUE THREAD

**Issue by Pacecca** [SKCraft/Launcher#236]
I want to do this for my Mac, but it has .bat files and i don't know if it will work.
If it does work, would you be able to create a new version for Mac?

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/Initial-Steps

**Comment by sk89q** [comment]
Works on Mac

**Comment by thefudgeishot** [comment]
actually it doesn't if your using mods and trying to launch it will crash and spannerman79 wont fix it

**Comment by thefudgeishot** [comment]
what about for mods

**Comment by Grand-Trizmo** [comment]
Yes works exact same for modded on Mac as it does on windows
