### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SoulSen** [SKCraft/Launcher#243]
Will This work in the new minecraft lanucher, and also can you maybe make a youtube tutorial to make it easier? And also if i take the -all.jar can I just give it to someone and it'll work? or do i have to give the whole thing.

**Comment by sk89q** [comment]
Work in?

**Comment by SoulSen** [comment]
Wait what do u mean?

**Comment by sk89q** [comment]
This launcher is separate from the MC launcher so I'm not sure what you're asking.
