### ISSUE TITLE
forge starting

### ISSUE THREAD

**Issue by DamianoMazzara** [SKCraft/Launcher#250]
Hi,
I want to create my custom launcher with netbeans, for a single modpack that uses forge, but i don't know how to run the forge version "manually" without using a launcher. I've read that forge uses the native minecraft version (for example 1.12.2.jar) and forge libraries, but i don't know how to start it, what is the file jar to execute and how to link the forge libraries to load the mods.
Hope you can help me; sorry for annoying you.
_This is not an issue but i didn't know how to contact you..._

**Comment by spannerman79** [comment]
@Pandaliano A literal 5 second search with google and i came across https://github.com/RX14/jMCLaunchLib#usage
