### ISSUE TITLE
Cannot download minecraft assets

### ISSUE THREAD

**Issue by kubachrabanski** [SKCraft/Launcher#252]
This error showed up while I was testing the launcher locally through the creator

The error that shows up:

To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

The files that fail to download all the time:

Downloading 3 files... (3 remaining, 0 failed)
...	org.ow2.asm:asm-all:5.2.jar
...	org.apache.maven:maven-artifact:3.5.3.jar
...	jline:jline:2.13.jar

Minecraft: 1.12.2

**Comment by MnkyArts** [comment]
same here.

**Comment by MnkyArts** [comment]
Fixed it.

simply download the files which cant be downloaded
(- asm-all:5.2.jar
- maven-artifact:3.5.3.jar
-jline:2.13.jar)

and put them in the "libraries" folder on your Webserver.

asm-all:5.2.jar would be: libraries/org/ow2/asm/asm-all/5.2
maven-artifact:3.5.3.jar would be: libraries/org/apache/maven/maven-artifact/3.5.3/
jline:2.13.jar would be: libraries/org/jline/jline/3.5.1

hope i could help you and some other people.

**Comment by KaratekHD** [comment]
Same problem here. Works fine on 1.7.10, but not on 1.12.2. I click 'Test' in the modpack creator and get the same error message.  I am behind a http proxy, don't know whether that's important. Sadly, @MnkyArts fix doesn't work for me.

**Comment by spannerman79** [comment]
@KaratekHD don't necro issues.

https://github.com/SKCraft/Launcher/issues/235 - either wait until @sk89q makes the fixes, accepts the needed PR's or make the changes defined in that issue.

**Comment by KaratekHD** [comment]
Oh, I'm sorry, didn't See that issue

**Comment by Escartem** [comment]
I have downloaded the jar files but I have no idea how to import it to the webserver. I'm using Windows 10

**Comment by spannerman79** [comment]
@sk89q - please close/lock this issue.

**Comment by hedgehog1029** [comment]
Fixed in master.
