### ISSUE TITLE
[Enhancement] Make the launcher launch the Minecraft launcher instead.

### ISSUE THREAD

**Issue by JacksonPlayz** [SKCraft/Launcher#253]
As the title says, make the modpack launcher launch the Minecraft launcher so you don't have to login to the modpack launcher. It'll make a lot more users feel safer logging in.

(I said launch or launcher too much)

**Comment by spannerman79** [comment]
For you to ask this you don't understand how a custom launcher works.

Try making the same suggestion over on the ATLauncher or Technic launcher support locations - see what sort of response you'll get 🤣

**Comment by JacksonPlayz** [comment]
Okay.
