### ISSUE TITLE
Minecraft 1.4.7

### ISSUE THREAD

**Issue by HaoSs07B** [SKCraft/Launcher#256]
How do I load liteloader and minecraft forge for minecraft 1.4.7 when there's no installer for these ?

**Comment by spannerman79** [comment]
https://github.com/SKCraft/Launcher/wiki/Custom-JAR

**Comment by HaoSs07B** [comment]
> https://github.com/SKCraft/Launcher/wiki/Custom-JAR

Thank you.

**Comment by HaoSs07B** [comment]
Back on it, the pack runs fine when testing it via the creator but when I launch it from the Launcher the window never gets created.

**Comment by EazyFTW** [comment]
#235  would fix your issue.

**Comment by spannerman79** [comment]
> Back on it, the pack runs fine when testing it via the creator but when I launch it from the Launcher the game window never gets created.

And how can I (or anyone else for that matter) try to reproduce that when we aren't at your system?

That is just as helpful as someone saying "Oh my computer crashed" and expected help @HaoSs07B

**Comment by HaoSs07B** [comment]
I can give you a copy of the custom jar.

http://b-gaming.com/publicdata/custom_jar.jar

**Comment by hedgehog1029** [comment]
If you're still experiencing this issue, please open a discussion.
