### ISSUE TITLE
servers.dat doesnt update

### ISSUE THREAD

**Issue by Grand-Trizmo** [SKCraft/Launcher#257]
when you release a pakc with a servers.dat then later want to change that file the launcher wont grab it as part of a pack update. so you are stuck with the original servers.dat unless you force update so that it overwrites the servers.dat

**Comment by sk89q** [comment]
You need to edit the modpack and remove servers.dat from the modpack settings. Unfortunately that means if users add a server, they will also lose it. +/-

**Comment by Grand-Trizmo** [comment]
but if i just want to modify it i would have to update it so that it doesnt have the servers.dat ,then push another update with a revised servers.dat?

**Comment by sk89q** [comment]
Well it actually won't wipe the user's file if until you edit the file again (if you remove the file from the settings).

**Comment by hedgehog1029** [comment]
Probably marked as a "user file", can be excluded from that in the modpack settings.
