### ISSUE TITLE
Launcher crashes istantly after launching modpack

### ISSUE THREAD

**Issue by JohnSmith114** [SKCraft/Launcher#26]
Currently the modpack only has the custom_jar.jar which is actually forge-1.7.10-10.13.0.1199.

This is the log of the launcher: http://pastebin.com/9WM4BFD4

My setup was a folder called "testmodpack" with inside a dist and a src folder. Inside the src folder there's only the custom jar and no other folders.
The command I used to compile the modpack was the following:

"java -cp SKCraftLauncher.jar com.skcraft.launcher.builder.PackageBuilder --version "1.0" --manifest-dest "dist/manifest.json" --objects-dest "dist/objects" --files "src" --config "modpack.json" --objects-url "objects" --version-file "version.json" --libs-url "http://giuzcraft.altervista.org/johnsmithpackReborn2/libraries""

Which I issued after changing directory to "testmodpack".

All the libraries have been uploaded at the following link: 
http://giuzcraft.altervista.org/johnsmithpackReborn2/libraries

**Comment by sk89q** [comment]
Closing due to age.

**Comment by TheFedoraBreifcase** [comment]
I am having the same problem but with paid hosting.

**Comment by sk89q** [comment]
How did you upload the files? FTP?

**Comment by TheFedoraBreifcase** [comment]
Yes, I used FTP.

**Comment by sk89q** [comment]
Make sure to upload in binary mode.

**Comment by TheFedoraBreifcase** [comment]
Ok, I will try that.
