### ISSUE TITLE
When attempting to use the wrapper i get this error

### ISSUE THREAD

**Issue by JohnyMuffin** [SKCraft/Launcher#278]
Hello,
When i attempt to use the Wrapper i get this error

To report this error, provide:
java.io.IOException: Failed to find launchable .jar
	at com.skcraft.launcher.Bootstrap.launchExisting(Bootstrap.java:140)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:119)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

latest.json
{
    "version": "4.0.1",
    "url": "http://xxxxxxxxx.com/launcher/launcher.jar.pack"
}

Running the wrapper makes a file called 1548404384960.jar in the Launcher folder that is the actual Launcher. I just don't think its managing the copying correctly.

**Comment by spannerman79** [comment]
For testing;

- Ensure you are using Java 8. 9 & 10 are still buggy ( see https://github.com/SKCraft/Launcher/commit/40b5fb838c1af16812653e002fe851a64696cced ).  If you are using lets encrypt to serve your files check ensure your java version is high enough, see https://letsencrypt.org/docs/certificate-compatibility/
- Use `curl` to check the status of your `launcher.jar.pack`.  You have no idea how many webserver misconfigurations cause issues.

**Comment by JohnyMuffin** [comment]
Ahh, the Lets Encrypt issues make a lot of sense. Guessing Java doesn't classify it as a proper Cert Root yet.

Thanks
