### ISSUE TITLE
cracked account

### ISSUE THREAD

**Issue by jakub96124124** [SKCraft/Launcher#279]
Hello
it would be possible to add a cracked account to the launcher ?
Thanks

**Comment by spannerman79** [comment]
A [simple search](https://github.com/SKCraft/Launcher/search?q=cracked+account&type=Issues) would have given you that answer

**Comment by jakub96124124** [comment]
I did not ask for the answer and I waited for the answer to be added to the plan.

**Comment by AzureZhen** [comment]
As stated by sk89q https://github.com/SKCraft/Launcher/issues/101#issuecomment-155216606

**Comment by hedgehog1029** [comment]
Not supported.
