### ISSUE TITLE
"The SKCraft Launcher could not be downloaded."

### ISSUE THREAD

**Issue by Kamisoi** [SKCraft/Launcher#281]
Hello,
Well.. Trying to create bootstrapper working makes me sick actually.

https://privatebin.net/?7176813e04627228#oEEqUgU9VQg6tVRpNfgUB0FNavVtr7CtUSu+hoA23NY=

^ It's error that's provided every time I launch the bootstrap. No matter of config, no matter of configuration - it always give only this error.

When I launch normal pack, it download pack fine & load provided news page
Anything that could be causing that?
If it's important, server isn't using any domain, just plain IP with directory attached to it [like "localhost/home" for example].

**Comment by sk89q** [comment]
Can you post the bootstrapper configuration (maybe slightly obfuscated)?

**Comment by Kamisoi** [comment]
![image](https://user-images.githubusercontent.com/26931504/52901153-98b60d00-31ff-11e9-9c59-22eb08a6ab38.png)
Here you go

**Comment by Kamisoi** [comment]
Just found out, that using 
`packageListUrl=http://example.com/packages.php?key=%s`
won't work either.

Error provided here: https://privatebin.net/?42735dd89fd50f97#ib4Iyxuvv+kHD4XJuP/HYX+ilEoi7laN+CjjI5kAckw=

**Comment by spannerman79** [comment]
@Kamisoi the reason why sk89q asked for your bootstrapper config was that us linux users could actually test your `latest.json`.

Those errors you report are an issue with your webserver/hoster.

NB: "Free" hosting is not supported.  You need a clean direct URL location to obtain the lanucher resources

**Comment by Kamisoi** [comment]
I'm not using "free" hosting tho. I'm hosting everything on my root server, only thing I'm changing is disabling Apache & PHP version note and disabling indexing inside web directory.

Like I've said, bootstrapper is erroring with provided + just found out that using any launcher with set packageListUrl pointing on packages.**php** creates another error that I'm not even familiar with

**Comment by spannerman79** [comment]
Then those are issues that you need to resolve yourself. As *no one* can give you external diagnositics due to inability on your part you need to trace down your webserver configs yourself.

This is not a launcher issue. Webserver/php misconfiguration @sk89q

**Comment by Kamisoi** [comment]
That's pretty weird for me, really.
Because it is literally plain Apache & PHP config. 
Can it be because of using IP rather than domain as access URL for every path?

**Comment by spannerman79** [comment]
> Can it be because of using IP rather than domain as access URL for every path?

No.  Before when I was testing out skq's launcher I was using an IP instead of a domain name.
As I'm running PHP 7.2, Apache with nginx as reverse proxy I have no issues


> If we talk about what's inside latest.json:

Its not whats inside is the ability for your websever to server the file correctly.  Hence why sk (and others like myself) ask for the config in order to do a `curl` to check the status of it.

**Comment by Kamisoi** [comment]
![image](https://user-images.githubusercontent.com/26931504/52907080-4eae4500-325a-11e9-8560-5ad6fba16d09.png)
I'm not even worried about obfuscating that IP anymore

**Comment by spannerman79** [comment]
Your bootstrap config (that you gave previously) is pointing to a file that doesn't exist
```
curl -Is http://xx.220/thaklauncher/latest.json | head -n 1
HTTP/1.1 404 Not Found
```
Your 1.0.1.jar.pack
```
curl -Is http://xx.220/launcher/1.0.1.jar.pack | head -n 1
HTTP/1.1 200 OK
```

**Comment by Kamisoi** [comment]
Yes, I know that. I replaced that on local, still same. From time I posted picture of config I had to reinstall whole system on server, so in config now is `http://xx.220/launcher/1.0.1.jar.pack`
And latest.json `http://xx.220/latest.json`

**Comment by spannerman79** [comment]
```
curl -Is http://xx.220/latest.json | head -n 1
HTTP/1.1 200 OK
```
I saw that in your bootstrap config you got `launcherClass=com.skcraft.launcher.FancyLauncher`, are you using Java 9/10 at all? If so you'll need to drop down to Java 8 ( see https://github.com/SKCraft/Launcher/commit/40b5fb838c1af16812653e002fe851a64696cced )

**Comment by Kamisoi** [comment]
Nope. I'm using Java 8u201, 64 bit.

Also for now, just for my own sake I'll use only packages.json as building launcher with pointing for packages.php don't do anything, can't obtain uploaded pack

**Comment by spannerman79** [comment]
The secret key needs to be using the ASCII character set only.  as the secret gets passed on as a URL.  Java doesn't "covert" URL's to ASCII like web browsers do.
For example, if my secret key was `SKCraft is da bomb!` the key needs to be entered as `SKCraft+is+da+bomb%21`

**Comment by Kamisoi** [comment]
Secret keys weren't used yet, only generated packages.php for one pack and when compiling launcher with it, that pack isn't loaded to launcher like it is with packages.json; it just makes error that I'll be able to provide in ~5 to 8 hours

**Comment by sk89q** [comment]
The mod packs could not be downloaded error is because the page that gets download isn’t valid JSON.

If you scroll down in that error it says there’s a misplaced < which usually means there’s a HTML file at that URL.

And usually that’s because the file is missing or the launcher was blocked (happens with ClpudFlare for example). 

I’m traveling atm without my laptop so I’ll check it out later.

**Comment by Kamisoi** [comment]
Isn't valid JSON - could be
But I was pointing launcher to generated PHP packages file. That was the problem

**Comment by spannerman79** [comment]
> Isn't valid JSON - could be

When I previously put in the full URL into https://jsonformatter.curiousconcept.com/ it actually states it has the wrong encoding.

So while it may be UTF-8 on file your webserver is screwing it up.

**Comment by Kamisoi** [comment]
No matter if I force UTF-8 with .htaccess or apache config file, that site still throw errors.

**Comment by Kamisoi** [comment]
Fast update - somehow, changing just build version from 1.0.1 to 1.0.2, replacing file on server & pointing everything to packages.json rather than packages.php - works fine. Even with bootstrapper.

**Comment by spannerman79** [comment]
As your issue is resolved I suggest you close it.

The fancy launcher will always use more RAM compared to classic. That is the trade off.

**Comment by Kamisoi** [comment]
Ya, but not 1GB RAM for pure launcher.. 
Anyway, thanks guys, glad u helped me
