### ISSUE TITLE
The beta 3 -beta6  launcher doesn't accept e-mail names longer than 17 chars

### ISSUE THREAD

**Issue by pkej** [SKCraft/Launcher#282]
My e-mail name is 20 characters long before the @ sign. The latest launcher stops accepting input when I've reached 17 characters, and will only accept an @ character after that point. The local part of an e-mail address can be 64 characters long per the spec:

https://tools.ietf.org/html/rfc2821#section-4.5.3.1

 local-part
      The maximum total length of a user name or other local-part is 64
      characters.

**Comment by sk89q** [comment]
Weird. I’m not aware of any email validation anywhere. I’ll check it out when I get home

**Comment by pkej** [comment]
I tried using the older sklauncher, 2.8.1.exe, and I get a login window, which accepts my full length name. It doesn't ask me for my mojang-password.

The 3-beta6 asks for my mojang password, and I can't log in. If I remove all the punctuation, which gmail actually doesn't care about if you log in, Mojang can't authenticate me, because in their system my punctuation is relevant.

I hope that helps?

**Comment by pkej** [comment]
Hi, hmm, perhaps I'm on the wrong github? I'm talking about https://skmedix.pl/sklauncher/ and you have your skcraft/launcher, is that the same? I am actually using the modpack creator.

**Comment by sk89q** [comment]
Never seen that page before. It’s not associated with us
