### ISSUE TITLE
Modpack Properties -> User files -> Exclude patterns

### ISSUE THREAD

**Issue by pkej** [SKCraft/Launcher#283]
The rules made in the exclude files doesn't seem to be run when doing a test. Reproduce by adding an exclude like:

mods/*.disabled

add some files with the .disabled filetype in the src/mods folder.

Delete test launcher instances

Do a test run

go to the mods folder of the instance and notice that files with the .disabled extension exists in the test instance.

I guess a general *.disabled would only apply to the root of the src directory?

**Comment by spannerman79** [comment]
I think generally when the modpack is on the end user/system the only time you rename a mod to `*.jar.disabled` would be for testing.

That is why https://github.com/SKCraft/Launcher/wiki/Optional-Features is used, so only the mod is loaded client side.
