### ISSUE TITLE
Creator Tools Fails [1.13.2] when Forge loader is being built

### ISSUE THREAD

**Issue by seeker2921** [SKCraft/Launcher#285]
All,

I have applied all PR's to point to the new downloads and can build and play 1.13.2 with no issues.

When adding ANY version of forge (the installer) to the modpack and building it in creator tools, I get the following:

`[info] --- Checking for mod loaders to install... ---
[info] Installing forge-1.13.2-25.0.9-installer.jar...
[warning] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:173)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:139)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:407)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:77)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:32)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`
removing just the loader, while leaving the mods results in a good build (Other than the fact that it cant be played without the loader :) ).

This seems likely to be a change made in forge loader itself for 1.13 that we just haven't accounted for yet.

Anyone else get forge 1.13.2 loader to work yet?

**Comment by spannerman79** [comment]
The forge dev team have drastically changed how 1.13 works.  Even trying to install on the vanilla launcher isn't exactly easy.

Until there is a stable json feed trying to get forge on 1.13 to work on launchers other then vanilla will have to wait - unless you want to work out some way to "hack" the way which other launcher is attempting to do from what I read on their discord.

**Comment by i9hdkill** [comment]
The vanilla installation works now. Even though mods will skip 1.13 pretty much, I would like to add Forge for Optifine for consistency for users. Any ideas?

**Comment by spannerman79** [comment]
> Also the number of current mods on 1.13 - a total of 12

Since 2019-03-16 its only gone up to 18 - an increase of a massive _sic_ 6 more...
Yeah 1.13 will be more or less skipped by the looks of things.

**Comment by miiichael** [comment]
Unfortunately 1.14 doesn't work either, as (naturally) the install_profile.json/version.json changes in 1.13 exist in 1.14 too. :stuck_out_tongue: The java.lang.NullPointerException is the result of code assuming install_profile.json always contains an "install" section.

(Of course, it remains to be seen whether Fabric displaces Forge entirely in the 1.14+ world, rendering this entire bug report moot :sweat_smile:)

**Comment by budgej** [comment]
I don't see any concrete process but this appears to be relevant https://github.com/SKCraft/Launcher/pull/299

**Comment by H4Mm3r** [comment]
No progress. This project is stuck to forge for 1.12. So sad as it's the only similar launcher in the world :(

**Comment by spannerman79** [comment]
Resolved - see latest commit

https://github.com/SKCraft/Launcher/issues/235#issuecomment-750944382

**Comment by hedgehog1029** [comment]
Forge 1.13+ is now supported.
