### ISSUE TITLE
Invalid creditentials

### ISSUE THREAD

**Issue by DarkScientist** [SKCraft/Launcher#288]
Hi,
When i try to launch Minecraft with the default upload folder, it tells me "Invalid creditentials".
The only error i get is "Task Failed".
Any way to get this solved ?
Thanks !!

**Comment by spannerman79** [comment]
https://help.mojang.com/customer/en/portal/articles/781529-login-failed

**Comment by DarkScientist** [comment]
Hi,
I solved it by changing the session name into the launcher properties file. 
Is there any way to keep a custom session name with right authentication?

**Comment by spannerman79** [comment]
> Is there any way to keep a custom session name with right authentication?

Implement your own Yggdrasil auth, which is outside the scope of this issue tracker.

**Comment by DarkScientist** [comment]
Fixed with a yggdrasil server from MineWeb!
