### ISSUE TITLE
Custom Minecraft Version

### ISSUE THREAD

**Issue by jazzy348** [SKCraft/Launcher#289]
I've been trying to setup this launcher to use the ViveCraft custom Minecraft version. I have even gone as far as to host the .jar on my webserver and point the launcher at it. I can see it downloading from my webserver in the logs but for some reason it is still not using this Jar. Any ideas?

**Comment by DarkScientist** [comment]
Hi,
Have you followed what it written there : https://github.com/SKCraft/Launcher/wiki/Custom-JAR ?

**Comment by jazzy348** [comment]
I have. I created a "_CLIENT" folder and named the jar custom_jar.jar inside the _CLIENT folder.

**Comment by DarkScientist** [comment]
It looks like your jar file is invalid to launch.
Try to launch it from your launcher, to see if the error comes from the jar or the launcher.

**Comment by jazzy348** [comment]
I've manually edited the manifest to include the missing libraries, now I'm just fighting with FML stating that my jar is has a different checksum. I tried the launch parameter to bypass this but that didn't work

**Comment by DarkScientist** [comment]
Strange.... Let me know if you fixed it...

**Comment by jazzy348** [comment]
I havnt. I've opened a thread on the Vivecraft forum and they seem as stuck as I am

**Comment by DarkScientist** [comment]
Always stuck?

**Comment by jazzy348** [comment]
Seems we have made progress, just a few more missing libs

http://www.vivecraft.org/forum/viewtopic.php?f=3&t=3482&p=4324#p4324

**Comment by DarkScientist** [comment]
Maybe that you can set up your own libraries download server?

**Comment by jcc10** [comment]
did you ever get past the log4j issue, I'm hitting it now. (Trying to make a non-vr mod-pack and later a vr mod-pack. Can't even get the base jar to launch.)

No download issues. (Just copied the libraries folder to the webserver from my .minecraft directory.)

Full Error:

```
The game is running. Please wait.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
Process ended with code: 1
```

**Comment by spannerman79** [comment]
You need to work/contact ViveCraft for support.  If it cannot be done with a [Custom Version Manifest](https://github.com/SKCraft/Launcher/wiki/Custom-Version-Manifest) then more then likley their installer is doing something stupid - like using absolute paths.

**Comment by jcc10** [comment]
So the reason I was posting was because @jazzy348 seemed to have found the solution and had moved on to a different problem.

The solution is to manually copy the library's that are to be copied from the parent version to the vivecraft version.

After adding the two tags `-Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true` (The first was already there?) it now launches.

I also had to host the library files on the modpack server.

Just to ensure I am clear, Both Vivecraft VR and Vivecraft Non-VR now load. I believe that this should be closed now as both are functional.

I'm going to see about adding to the wiki about what I learned through this.

**Comment by spannerman79** [comment]
Please do.

Do note:  Don't use youtube to "show" as it will be removed.  To add images follow something like [this](http://mikehadlow.blogspot.com/2014/03/how-to-add-images-to-github-wiki.html) and don't use imgur.

Both Youtube and imgur can have resources removed at any moment without notice.  With Github if something is removed or changed its logged as to who did it.

**Comment by jcc10** [comment]
Already done:
https://github.com/SKCraft/Launcher/wiki/Vivecraft-Issues

No images since it's mostly just stuff that isn't documented anywhere I found but I intuited over the last few days.

Feel free to rename the article, I just don't know what the article name should really be.

**Comment by hedgehog1029** [comment]
Vivecraft now supports just running as a Forge mod (at least on 1.16.4); I actually have it in my test 1.16.4 instance. Also, that wiki article is good, just needs a little cleanup, I'll do that at some point.

**Comment by hedgehog1029** [comment]
Also might look into supporting the Vivecraft installer in the "loaders" folder, it's a little bit of a mess though.
