### ISSUE TITLE
Add an api 

### ISSUE THREAD

**Issue by DarkScientist** [SKCraft/Launcher#290]
Hi,
Is there any way to add something like an api that allow us to know who have the launcher,....?

**Comment by spannerman79** [comment]
Change https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/java/com/skcraft/launcher/util/HttpRequest.java#L113 and just parse your http logs

**Comment by DarkScientist** [comment]
Hi,
What does this line do?

**Comment by spannerman79** [comment]
> Hi,
> What does this line do?

Well usually good coders split their code into specific files set for a specific job.  IF you look at the file name `HttpRequest.java` you should be able to surmise that specific files has something to do with [creating http requests](https://www.quora.com/What-is-an-HTTP-request). 

And if you look at the specific line i referenced, being `conn.setRequestProperty("User-Agent", "Mozilla/5.0 (Java) SKMCLauncher");` and then do some digging/google/duckduckgo-ing around with how apache/nginx logs user agents you would be pleased to learn that you found out something all by yourself and feel more satisfied with your own initiative

**Comment by DarkScientist** [comment]
Thank you! 
It'll be very useful! 
I make this change and close this issue.

**Comment by spannerman79** [comment]
> I make this change and close this issue.

..?

**Comment by DarkScientist** [comment]
Done! I close that.
And thanks for your help @spannerman79!
