### ISSUE TITLE
12 files can't be downloaded

### ISSUE THREAD

**Issue by LTXmine** [SKCraft/Launcher#292]
Some files can't be downloaded, I'm not sure but I think it's Maven

Files that can't be downloaded:

net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10
com.typesafe.akka:akka-actor_2.11:2.3.3
com.typesafe:config:1.2.1
org.scala-lang:scala-actors-migration_2.11:1.1.0
org.scala-lang:scala-compiler:2.11.1
org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
org.scala-lang:scala-library:2.11.1
org.scala-lang:scala-parser-combinators_2.11:1.0.1
org.scala-lang:scala-reflect:2.11.1
org.scala-lang:scala-swing_2.11:1.0.1
org.scala-lang:scala-xml_2.11:1.0.2

[Logs:](https://pastebin.com/3npeZJnc)

**Comment by spannerman79** [comment]
`dropboxusercontent.com`
https://github.com/SKCraft/Launcher/wiki/Website-Hosting

**Comment by LTXmine** [comment]
I don't understand, that file have to be downloaded from Forge servers no ?

**Comment by LTXmine** [comment]
And if I have to host them, where have I to put links ?
