### ISSUE TITLE
./instances/monster modpack/manifest.json (The System cannot find the path specified)

### ISSUE THREAD

**Issue by ToyPower** [SKCraft/Launcher#293]
./instances/monster modpack/manifest.json (The System cannot find the path specified). This is the error I am getting. I am using xampp to host my own server for the launcher. I Checked to make sure each of the newsurl, packagelisturl, and the selfupdateurl work. They all work, so then I launched the launcher and tried it, but it gave me the ./instances/monster modpack/manifest.json (The System cannot find the path specified) error. Anyone have any idea of how to fix? newsUrl=http://%IP%/zlife/news.html?version=%s
packageListUrl=http://%IP%/zlife/packages.json?key=%s
selfUpdateUrl=http://%IP%/zlife/launcher/latest.json
I do not want to put my ip in here so instead I replaced my public ip address with %IP%.

**Comment by spannerman79** [comment]
Not a launcher issue.

http://bfy.tw/NIKn

**Comment by ToyPower** [comment]
Its not a xampp issue either cause it works with everything else. Also its a manifest problem which I could only think that problem is with launcher.

**Comment by ToyPower** [comment]
I do not know why its doing this so I wrote this to try to figure it out, but I know its not xampp issue because it loads prop in the launcher.properties the only thing that doesn't seems to be the ./instances/monster mudpack/manifest.json which is why I thought it was launcher

**Comment by ToyPower** [comment]
ok so after looking at console it looks like this part might be the problem [warning] Failed to save class com.skcraft.launcher.auth.AccountList: com.skcraft.launcher.auth.AccountList@31e24ec3
java.io.FileNotFoundException: .\accounts.dat (Access is denied)

**Comment by ToyPower** [comment]
so after further looking it didn't even generate the instances folder anywhere

**Comment by spannerman79** [comment]
Again, not a launcher issue.
This is an issue unrelated to the launcher
If you actually used a search engine and searched for "access is denied files <your os>" you would get your answer.

This issue tracker is for specific launcher issues, not for file permission issues which are caused by yourself drectly, or for an incorrectly configured web server.

**Comment by ToyPower** [comment]
thing is I did do that and no solution and it only happens when I click to launch the mudpack on launcher

**Comment by ToyPower** [comment]
i understand now that this may not be a launcher problem so ill try to solve this elsewhere
