### ISSUE TITLE
Problem with build.bat

### ISSUE THREAD

**Issue by PetrusTryb** [SKCraft/Launcher#294]
Here are logs:
https://pastebin.com/MpwmJHTf

**Comment by spannerman79** [comment]
`gradlew -v` output?

**Comment by PetrusTryb** [comment]
C:\Users\Ptryb\Documents\Launcher-master\Launcher-master>gradlew -v
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Ptryb/.gradle/wrapper/dists/gradle-4.8.1-bin/e8p42vx1m7a3mz9ydmjagn6wn/gradle-4.8.1/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9-LTS)
OS:           Windows 10 10.0 amd64

**Comment by spannerman79** [comment]
> JVM: 11.0.2 (Oracle Corporation 11.0.2+9-LTS)

Read https://github.com/SKCraft/Launcher/wiki/Initial-Steps#compiling-the-launcher

**Comment by PetrusTryb** [comment]
Ok, I used older JVM and it worked, thanks.
