### ISSUE TITLE
Did you have Discord for better help?

### ISSUE THREAD

**Issue by Silverrain2004** [SKCraft/Launcher#296]
Hello Guys, can you help me? i have a Webserver (Paid) , but i dont get latest.json and .pack from my bootstrap and i dont know why, becouse i can download them via Browser without a problem. So i thought maybe you have a discord where i can get help a little faster without to wait for days and weeks maybe....i would appreciate your help.

**Comment by spannerman79** [comment]
If you have followed the wiki carefully you shouldn't have any issues.

Most, if not all of us, run our own communities so we are busy.  But we do offer help if the person asking help has given all required info beforehand and at least done and shown some diagnostics they have done themselves.

How I read your OP;
_Hi, I'm too lazy to read through my own log files on the launcher and my httpd logs.  I haven't checked for any existing issues and I'm a support vampire.  I **demand** help and I do not want to wait_

https://sol.gfxile.net/dontask.html
https://stackoverflow.com/help/dont-ask

**Comment by Silverrain2004** [comment]
I would give you all the Information you need. But i have many Software. And Discord is just a direct and faster way. And just becouse i prefer it, dousnt mean i am a lazy person, just becouse i am used to it ?. Its was just a kind question, if there exist a Discord Server, so i can DM with someone who is willing to help , thats all i wanted to ask. Of course if there isnt any sort of Discord for help.... then i will do it the usual way.

**Comment by Silverrain2004** [comment]
I managed to run my portable Version. It loads all Mods from my (Paid) Webspace and all is fine. But i wanted to build a bootstrap , but he keep telling me: 

Um diesen Fehler zu melden, berichte:

java.io.IOException: Did not get expected response code, got 404 for https://xxx/versions/launcher.jar.pack
	at com.skcraft.launcher.bootstrap.HttpRequest.expectResponseCode(HttpRequest.java:154)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:101)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

The Thing is, i have Uploaded it in Binary Mode with Filezilla, there was no Problem with that. Should i build a new bootstrap? it is it ok that way?

**Comment by sk89q** [comment]
Well... you need to figure out why that file doesn't exist on your web server. Sounds like it isn't even there

**Comment by Silverrain2004** [comment]
Hi there @sk89q thank you for your kind help, i managed to solve many things. My Modpacks are loading correct ... but the Bootstrap give me Problems....

Um diesen Fehler zu melden, berichte:

java.io.IOException: Failed to find launchable .jar
	at com.skcraft.launcher.Bootstrap.launchExisting(Bootstrap.java:140)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:119)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)

I have build the bootstrap and pack it. But i saw some strange errors... can it be this problem?

\launcher2\Launcher EXE>C:\Programme\Java\jdk1.8.0_172\bin\pack200 --no-gzip launcher.jar.pack launcher-bootstrap-1.0.0.0-all.jar
Apr 27, 2019 6:09:27 AM com.sun.java.util.jar.pack.Utils$Pack200Logger warning
WARNING: Passing class file uncompressed due to unrecognized attribute: META-INF/versions/9/javax/xml/bind/ModuleUtil.class
Apr 27, 2019 6:09:27 AM com.sun.java.util.jar.pack.Utils$Pack200Logger warning
WARNING: Passing class file uncompressed due to unrecognized attribute: module-info.class

**Comment by JohnyMuffin** [comment]
This may be similar to the problem i had which was Java not support Lets Encrypt certs. Maybe try getting the launcher over HTTP and if it works then that means it most likely that issue. Another issue could be a CDN blocking the default user agent of Java, i believe cloudflare does this by default.

**Comment by darealHeroBrine** [comment]
you will need to edit the src in the bootstrap files here is the link to this section
https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update

**Comment by hedgehog1029** [comment]
All the available methods for contacting us are detailed [on the wiki](https://github.com/SKCraft/Launcher/wiki/Getting-Help).
