### ISSUE TITLE
Need help/advice (fabricloader working with skcraft)

### ISSUE THREAD

**Issue by SDUBZ** [SKCraft/Launcher#300]
A can confimr https://github.com/SKCraft/Launcher/pull/299 is working beautifully with vanilla but cant get it to load frabric modloader it wont read installer from loader folder https://fabricmc.net/use/ even tried same methods that technic uses aswell with no luck

if anyone has any ideas how to get it to load please let me know 
Thanks in advanced

**Comment by SDUBZ** [comment]
did get this To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.model.minecraft.VersionManifest.getClientDownloadURL(VersionManifest.java:78)
	at com.skcraft.launcher.update.Updater.update(Updater.java:142)
	at com.skcraft.launcher.update.Updater.call(Updater.java:92)
	at com.skcraft.launcher.update.Updater.call(Updater.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
when adding versions.json in main modpack folder used for technic lancher

**Comment by spannerman79** [comment]
Try Vanilla and download installer (universal/jar) and put it as you would with forge https://github.com/SKCraft/Launcher/wiki/Creating-Modpacks#adding-mods

**Comment by SDUBZ** [comment]
yeah i did it that way too no luck :(

**Comment by spannerman79** [comment]
You'll need to do some changes to the launcher in order to pull the required files for 1.13+
https://github.com/SKCraft/Launcher/issues/235
Do that and try what I said https://github.com/SKCraft/Launcher/issues/300#issuecomment-493342622

**Comment by SDUBZ** [comment]
@spannerman79 I done both of them how do you think i got vanilla 1.14.1 loading as seen here http://puu.sh/DtoIy/b921d35ea8.png  in the modpack maker to begin with also i tried alot of methods and some that most of other launchers do to get fabric working

**Comment by spannerman79** [comment]
Then you'll need to setup and use a custom version manifest (by the looks of it).
https://github.com/SKCraft/Launcher/wiki/Custom-Version-Manifest

**Comment by SDUBZ** [comment]
i do have a version manifest in modpacks root dir 
[version.json.txt](https://github.com/SKCraft/Launcher/files/3194796/version.json.txt)
should be all correct from what i asked the fabric devs

**Comment by SDUBZ** [comment]
but all i get is this output To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.model.minecraft.VersionManifest.getClientDownloadURL(VersionManifest.java:78)
	at com.skcraft.launcher.update.Updater.update(Updater.java:142)
	at com.skcraft.launcher.update.Updater.call(Updater.java:92)
	at com.skcraft.launcher.update.Updater.call(Updater.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by SDUBZ** [comment]
have to re try doing this again since fabric is more stable and on its feet 💯

**Comment by LoneDev6** [comment]
I have the same problem, any news?

**Comment by sk89q** [comment]
You might be able to get the Technic bin/version.json file and put it in the installer .jar as install_profile.json, but that's a wild guess.

**Comment by LoneDev6** [comment]
Strange, is there any official answer oever this problem? 

I think I'll just endup using Forge, hoping that Forge 1.14.4 is supported by launcher

**Comment by sk89q** [comment]
There isn’t a standard way to install mod loaders so basically every launcher needs its own custom way to install one. 

For LiteLoader and Forge they happen to just release their installers with a certain file they both include in their .jar, and it was great because it was the right amount of info the launcher needed to install them. Fabric doesn't do that.

**Comment by LoneDev6** [comment]
I'll use forge then, fabric seems too "out of the standards"
Thanks a lot!

Il mer 25 set 2019, 02:11 Albert Pham <notifications@github.com> ha scritto:

**Comment by SDUBZ** [comment]
forge 1.14 doesnt even work with skcraft launcher

**Comment by LoneDev6** [comment]
Sad
I hope they'll make Fabric official compatibility a thing, since I have no
time to research and implement this feature

Il sab 28 set 2019, 13:32 SDUBZ <notifications@github.com> ha scritto:

**Comment by SDUBZ** [comment]
okay lil update 
To report this error, please provide:

java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
@sk89q any ideas

**Comment by mecwerks** [comment]
Hello, I was able to get newest version of fabric working with some modifications on 1.15.2

Basically, I had to use the PR with 1.13+ manifest support, edit the hardcoded version_manifest url to my own custom one. This had an entry for a custom profile that i had as well that was copied from the 1.15.2 official mojang profile, but manually added in the fabric libs. Also changed the mainClass path.

I also hosted all libraries on my own webserver.

Example of version_manifest.json: https://pastebin.com/gb07gPWV
Example of fabric-loader-0.7.8+build.184-1.15.2.json: https://pastebin.com/GA71fWVC

Im sure there are better ways to handle this stuff, but this worked for my own purposes.

**Comment by SDUBZ** [comment]
@mecwerks do you think you could write a lil guide how you did this so others could follow ?

**Comment by mecwerks** [comment]
I dont really plan on it, as its a very hacky way to do it. You really shouldn't need to rehost all the minecraft libraries and such. I may eventually look into making a pull request to patch it a better way.

**Comment by mecwerks** [comment]
Ignore my previous post. There is a far easier way to do this. 

Using #270 and I made an `install_profile.json`, and put it into a zip file. Then renamed it `fabric-1.15.2+build.14-0.7.8+build.184.jar` (note, the name of this jar does not matter). And put this 'fake' jar into the loaders directory and everything worked.

Example install_profile.json: https://pastebin.com/WYbzhR1t

**Comment by SDUBZ** [comment]
everything works but when it comes to the launcher it doesnt show anything new
is there a step im probably missing just forgot over the years after not working with the project
my urls point back and it wont read the new modpacks added lately after i made changes to the launcher 🤔

**Comment by spannerman79** [comment]
Resolved - see latest commit

https://github.com/SKCraft/Launcher/issues/235#issuecomment-750944382

**Comment by hedgehog1029** [comment]
Fabric is now supported.
