### ISSUE TITLE
Germany Dictionary

### ISSUE THREAD

**Issue by AngelGamerZ** [SKCraft/Launcher#304]
Hey there,

Im trying to use the Localization for the German Dictionary. 

I saw, that the German Dictionary isn't implemented yet.

Is there an Option for that to do that by manually without waiting for an Update?

Greetings,

**Comment by spannerman79** [comment]
Edit https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/resources/com/skcraft/launcher/lang/Launcher.properties to suit you on your build

**Comment by hedgehog1029** [comment]
You can localize the launcher yourself, or see if you can find any community localizations. I might start a list of known localization forks in the future.
