### ISSUE TITLE
Forge 1.14.3

### ISSUE THREAD

**Issue by Pigmen36** [SKCraft/Launcher#311]
Im using fixed version of Launcher all working fine Minecraft 1.14.3 start but when add Forge modpack maker say error :(
How to fix it

**Comment by JohnyMuffin** [comment]
Forge changed a lot of its installation process most likely making Skcraft incompatible for now. Other launchers have also been having issues such as MultiMC to which forge has refused to help. Might take some time to get support in Skcraft.

**Comment by spannerman79** [comment]
The real issue is that forge (1.14) wants to display ads when it installs - so for now it will **only** support the vanilla launcher.

This will prob kill forge as there is also now fabric and fabric follows a maven type deployment system.

**Comment by hedgehog1029** [comment]
This is now fixed.
