### ISSUE TITLE
I don't understand this step.

### ISSUE THREAD

**Issue by JustStanix** [SKCraft/Launcher#314]
https://github.com/SKCraft/Launcher/wiki/Configuring-Self-Update#creating-the-jarpack
How do I run the launcher with pack200?
Where do I run this command?

**Comment by LFGSaito** [comment]
It’s where your java jdk is on your OS. Should be in the bin.

**Comment by JustStanix** [comment]
I found it but when I try to run it it instantly closes.

**Comment by JustStanix** [comment]
Ok so for anyone who is stuck on this step you need to go to the folder that contains the launcher-4.3-SNAPSHOT-all.jar
Run command prompt in that directory.
We need to set the path of our JDK.
For example I am using 1.8.0 Build 221. It is located in C then Program Files and then Java and you will see all the JDK and JRE you have installed in my case is is 1.8.0 Build 221.
Open your version then go in the bin folder and copy that whole directory.
Now go back to the command prompt you opened earlier and type in.
```path=(Paste Directory Here);```
It wont return anything.
Now you need to do this command.
```pack200 --no-gzip launcher.jar.pack launcher-X.Y.Z-all.jar```
And that's it. You have the launcher.jar.pack
