### ISSUE TITLE
I'm having a problem after compiling I've done nothing but download and compiled.

### ISSUE THREAD

**Issue by DyoungGFX** [SKCraft/Launcher#32]
So, I downloaded the source, And I ran it in maven... 

I haven't touched the source at all

but I get no errors.

and upon the maven my stuff says

c:\Users\Parent\Downloads\Launcher-master\skcraft>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building launcher 4.2.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ launcher ---
[INFO] Deleting c:\Users\Parent\Downloads\Launcher-master\skcraft\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ launcher -
--
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 6 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ launcher ---
[INFO] Compiling 114 source files to c:\Users\Parent\Downloads\Launcher-master\s
kcraft\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ la
uncher ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\Parent\Downloads\Launcher-ma
ster\skcraft\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ launc
her ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ launcher ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ launcher ---
[INFO] Building jar: c:\Users\Parent\Downloads\Launcher-master\skcraft\target\SK
CraftLauncher.jar
[INFO]
[INFO] --- maven-shade-plugin:2.1:shade (default) @ launcher ---
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.3.0 in the sh
aded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0 in the
 shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.3.0 in the shaded
 jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:1.2 in the shaded jar.
[INFO] Excluding org.projectlombok:lombok:jar:1.12.2 from the shaded jar.
[INFO] Including com.google.guava:guava:jar:15.0 in the shaded jar.
[INFO] Including com.beust:jcommander:jar:1.32 in the shaded jar.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing c:\Users\Parent\Downloads\Launcher-master\skcraft\target\SKCraf
tLauncher.jar with c:\Users\Parent\Downloads\Launcher-master\skcraft\target\laun
cher-4.2.3-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: c:\Users\Parent\Downloads\Launcher-mas
ter\skcraft\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.556 s
[INFO] Finished at: 2014-11-22T10:06:37-08:00
[INFO] Final Memory: 19M/85M
[INFO] ------------------------------------------------------------------------
c:\Users\Parent\Downloads\Launcher-master\skcraft>

but when I run the launcher in the target folder, it tells me
"Could not find the main class" and exits.

**Comment by sk89q** [comment]
Closing due to age.
