### ISSUE TITLE
All my launcher and modpack files are being saved in the same folder as the launcher file

### ISSUE THREAD

**Issue by ShonP40** [SKCraft/Launcher#320]
All my launcher and modpack files are being saved in the same folder as the launcher file no matter what I do.

**Comment by spannerman79** [comment]
This is intended behaviour as this Launcher is designed to be portable.

**Comment by ShonP40** [comment]
I don't want it to be portable.
I am using the fancy launcher and there is no portable.txt file in the same folder as the launcher.

**Comment by ShonP40** [comment]
nvm, I forgot that I have to launch the bootstrap-all.jar file...
