### ISSUE TITLE
Use a url.txt file without the related jar?

### ISSUE THREAD

**Issue by WorkInProgress-Development** [SKCraft/Launcher#322]
Is there any workaround to allow putting only a link to the mod download and not having to mirror a copy onto our own server?

Sorry if this is completely unclear.

**Comment by spannerman79** [comment]
There is a PR that should cover that for you

**Comment by WorkInProgress-Development** [comment]
I assume you mean this one: https://github.com/SKCraft/Launcher/pull/273
It's a little unclear how I should use it in practice. Do I need to edit the source code file at launcher-builder/src/main/java/com/skcraft/launcher/builder/ClientFileCollector.java, or just used the linked creator-tools-2.0.2-SNAPSHOT-all.jar.zip file?

Again, apologies if I'm missing something obvious.

**Comment by spannerman79** [comment]
> Do I need to edit the source code

Yes.

**Comment by hedgehog1029** [comment]
Implemented by 67f3fc1
