### ISSUE TITLE
Dropbox changed.

### ISSUE THREAD

**Issue by kr0wnz** [SKCraft/Launcher#325]
Hey, got some problems... Dropbox isnt working anymore so i uploaded it on github but i got over 5k files at the moment. Someone knows a web hosting site(paid/free) which i can use to?(on public) Can not find anything :/

**Comment by spannerman79** [comment]
> Dropbox isnt working anymore

Dropbox has stopped working since Sept 2017 https://help.dropbox.com/files-folders/share/public-folder

> Someone knows a web hosting site(paid/free) which i can use to?(on public) Can not find anything :/

https://github.com/SKCraft/Launcher/wiki/Website-Hosting#well-known-trusted-companies

Read the wiki
