### ISSUE TITLE
Pack200 depreciated

### ISSUE THREAD

**Issue by Nydid-ForcedDev** [SKCraft/Launcher#328]
I can't seem to work out how to use pack200, can't find any help online and the command doesnt lead me very far:

pack200 --no-gzip launcher.jar.pack launcher-X.Y.Z-all.jar

Could I get some help on how to use this command?
Is there another program for when the command will be depreciated?
is there an alternative?
Thanks

**Comment by LFGSaito** [comment]
Hi, Pack2000 is locate in the java bin folder.

**Comment by Nydid-ForcedDev** [comment]
> Hi, Pack2000 is locate in the java bin folder.

Yes, I do know it is in the bin folder, I opened a CMD in the bin folder and entered the command, but still does not work, i'm at a loss.

**Comment by spannerman79** [comment]
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/pack200.html

In what way is pack200 [depreciated](https://techterms.com/definition/deprecated)?

**Comment by Nydid-ForcedDev** [comment]
@spannerman79 The API, the pack200 and unpack tool are going to be removed

**Comment by spannerman79** [comment]
> The API, the pack200 and unpack tool are going to be removed, at least thats what the command always shows me when im trying to use it.

On my Win10 VM, with JDK8 from https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html installed gives the following;

```
pack200 --help
Usage:  pack200 [-opt... | --option=value]... x.pack[.gz] y.jar

Packing Options
  -g, --no-gzip                   output a plain *.pack file with no zipping
  --gzip                          (default) post-process the pack output with gzip
  -G, --strip-debug               remove debugging attributes while packing
  -O, --no-keep-file-order        do not transmit file ordering information
  --keep-file-order               (default) preserve input file ordering
  -S{N}, --segment-limit={N}      output segment limit (default N=1Mb)
  -E{N}, --effort={N}             packing effort (default N=5)
  -H{h}, --deflate-hint={h}       transmit deflate hint: true, false, or keep (default)
  -m{V}, --modification-time={V}  transmit modtimes: latest or keep (default)
  -P{F}, --pass-file={F}          transmit the given input element(s) uncompressed
  -U{a}, --unknown-attribute={a}  unknown attribute action: error, strip, or pass (default)
  -C{N}={L}, --class-attribute={N}={L}  (user-defined attribute)
  -F{N}={L}, --field-attribute={N}={L}  (user-defined attribute)
  -M{N}={L}, --method-attribute={N}={L} (user-defined attribute)
  -D{N}={L}, --code-attribute={N}={L}   (user-defined attribute)
  -f{F}, --config-file={F}        read file F for Pack200.Packer properties
  -v, --verbose                   increase program verbosity
  -q, --quiet                     set verbosity to lowest level
  -l{F}, --log-file={F}           output to the given log file, or '-' for System.out
  -?, -h, --help                  print this message
  -V, --version                   print program version
  -J{X}                           pass option X to underlying Java VM

Notes:
  The -P, -C, -F, -M, and -D options accumulate.
  Example attribute definition:  -C SourceFile=RUH .
  Config. file properties are defined by the Pack200 API.
  For meaning of -S, -E, -H-, -m, -U values, see Pack200 API.
  Layout definitions (like RUH) are defined by JSR 200.

Repacking mode updates the JAR file with a pack/unpack cycle:
    pack200 [-r|--repack] [-opt | --option=value]... [repackedy.jar] y.jar
```
When I actually use `pack200` to pack I get no exit or error message, just the end result done.

To test with OpenJDK, grabbing https://adoptopenjdk.net/ changing my `JAVA_HOME` and updating my path I get the **exact** same result. Even 

So either;
You're using something other than JDK8 or you got a fubar JDK install.
I don't see a depreciation warning with either oracle's licence or with OpenJDK.

PEBCAK

**Comment by Nydid-ForcedDev** [comment]
@spannerman79 

After looking around a bit, I found out my JAVA_HOME was somehow changed from JDK 8 to JDK 11. After retrying the command, I am no longer getting any warnings or errors, sorry about that. But I still don't understand how the tool works, nor how I'm supposed to link it to the .Jar file I'm trying to convert. (Never used the command before and I did not find any help online)

**Comment by sk89q** [comment]
Did you figure it out?
