### ISSUE TITLE
MaxPermSize support removed

### ISSUE THREAD

**Issue by Nydid-ForcedDev** [SKCraft/Launcher#329]
Hello, as the title says, MaxPermSize was removed on 8.0
https://pastebin.com/xQaFNF5V

**Comment by spannerman79** [comment]
Not an issue.  This launcher is used by people that use Java versions <8.  See https://github.com/SKCraft/Launcher/issues/144#issuecomment-219617761

**Comment by sk89q** [comment]
it's a warning, not a death sentence 

and it's there in case they're not using Java 8+, although they shouldn't be

**Comment by spannerman79** [comment]
In fact create a branch on your own fork @Nydid-ForcedDev and edit https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/java/com/skcraft/launcher/launch/JavaProcessBuilder.java#L105..L107 if it bothers you so much.

**Comment by Nydid-ForcedDev** [comment]
Ok, thanks for the input!
