### ISSUE TITLE
[bootsrap] Error 503 with my jar after transfer my website to an other hoster

### ISSUE THREAD

**Issue by Namentis** [SKCraft/Launcher#330]
I created a minecraft launcher with SKCraft and everything was hosted on 000webhost.com. Then I transferred my site to hostinger.com and changed all the links to point to my new host.

Except that since, I get this error:

```
java.io.IOException: Did not get expected response code, got 503 for https://ragnaguys.hostingerapp.com/latest.json
    at com.skcraft.launcher.bootstrap.HttpRequest.expectResponseCode(HttpRequest.java:154)
    at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:74)
    at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
    at java.lang.Thread.run(Unknown Source)
```

Only the URL of the file has changed in my code and the link is functional from a browser.

Is there anything I need to change in the server configuration? Since on the program side nothing changed except the link.

Everything works fine if I put the links back to 000wewhost.com

Thanks!

**Comment by spannerman79** [comment]
https://httpstatuses.com/503

Not a launcher issue - sort out your hosting first.

**Comment by darealHeroBrine** [comment]
did you change where the strapper and or launcher to get these infos (link to said url) for mine its tnz

**Comment by hedgehog1029** [comment]
Webserver misconfiguration of some kind - closing since this is quite old.
