### ISSUE TITLE
Getting new Button in Launcher?

### ISSUE THREAD

**Issue by AngelGamerZ** [SKCraft/Launcher#342]
Im new to Java and so on i searched thru the .java files for Buttons that are shown in the Launcher. I only find the lang folder but where can i find the file to add an optional button? for example If I want to add a Website button or a Button for Support etc.

Is this possible with this Launcher? Where can I find it?

**Comment by sk89q** [comment]
https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/java/com/skcraft/launcher/dialog/LauncherFrame.java

Look for optionsButton in that file.
