### ISSUE TITLE
SkCraft Lauch Lib

### ISSUE THREAD

**Issue by BarryV94** [SKCraft/Launcher#343]
Hey i was wondering if there is something line Launch Lib to create our own launchers from the scratch but with skcraft launch lib? I was inspired by jMCLaunchLib but it is not updated anymore and for versions line 1.15.2 it is not working :/

This launcher is one of the best for now

**Comment by sk89q** [comment]
You can use it as a lib but I don't have docs on it. Everything is in a reusable class.
