### ISSUE TITLE
How to add JVM params to minecraft instance

### ISSUE THREAD

**Issue by evanlegamer** [SKCraft/Launcher#345]
Hi, i made a mod and i need to add in minecraft JVM instance 2 params
-Duuid=(uuid of the player)
-Dtoken=(accessToken)

uuid and accessToken should be get from the response of the login to the yggdrasil server.

Do you know if it's possible to do that and if it is, do you have an hint to help me ?
Thank you in advance for your help.

**Comment by spannerman79** [comment]
> -Duuid=(uuid of the player)

https://www.minecraftforge.net/forum/topic/64903-1122-get-player-by-uuid-on-server/?tab=comments#comment-307918

> -Dtoken=(accessToken)

https://wiki.vg/Authentication#Response

Pull that info yourself directly.

**Comment by evanlegamer** [comment]
that's not exactly what i mean, i already have the info uuid and accessToken, i just want to give those params to the minecraft JVM at launch. I saw in the sourcecode (https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/java/com/skcraft/launcher/launch/Runner.java) that some args are given here but not to sure about that

**Comment by spannerman79** [comment]
For what purpose does that serve?

If this is to get around Mojangs auth then this is not supported by this launcher (ie cracked clients)

**Comment by evanlegamer** [comment]
This is for a mod in my modpack that require those JVM arguments

**Comment by spannerman79** [comment]
> This is for a mod in my modpack that require those JVM arguments

Then whatever concept you have for your mod/modpack is flawed.

The players accessToken will change the moment that they log into another server, change IP or access their account via https://account.mojang.com/

Also access to the user/s accessToken can open the users account up to abuse and why that is handled to first auth the user to verify a legit paid MC account and later session.mojang.com for the server end.  Its not for a mod and/or modpack to have access to.

**Comment by sk89q** [comment]
Yeah, that sounds like a seriously sketch mod...

**Comment by evanlegamer** [comment]
So if someone need this later, in Runner.java, i added to the addLegacyArgs those 2 params

> 

    private void addLegacyArgs() {
        builder.getFlags().add("-Dminecraft.applet.TargetDirectory=" + instance.getContentDir());
        builder.getFlags().add("-Duuid=" + session.getUuid());
        builder.getFlags().add("-Dtoken=" + session.getAccessToken());
    }

Thanks for your help guys ;)
