### ISSUE TITLE
Unable to create Modpack - 3 Files Missing

### ISSUE THREAD

**Issue by DrewSin-4** [SKCraft/Launcher#348]
Heyo,

I am trying to create a test modpack as I work on the Launcher but it won't let me start it as it has 3 missing files. This is what the error says.

```
To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I have tried both #299 #235 and these don't seem to be working.

I was wondering if anyone has a working fork?

This is for 1.12.2 Forge.

Oh yeah, here's what the log says also although I doubt it is much help. - https://hastebin.com/suqokozake.rb

**Comment by Erafle** [comment]
I fixed this by taking all the librairies needed and uploaded them on my hosting (like yoursite.com/librairies).

You can grab them by installing Forge 1.12.2 on your Minecraft and then copy the librairies folder (in your %appdata%) on your hosting.

Then you need to change "launcher.properties" in the "launcher\build\resources\main\com\skcraft\launcher" and change the line "librariesSource=XXX" by your URL on your server (like "librariesSource=http://yoursite.com/libraries/").

**Comment by DrewSin-4** [comment]
> I fixed this by taking all the librairies needed and uploaded them on my hosting (like yoursite.com/libraries).
> 
> You can grab them by installing Forge 1.12.2 on your Minecraft and then copy the librairies folder (in your .minecraft) on your hosting.
> 
> Then you need to change "launcher.properties" in the "launcher\build\resources\main\com\skcraft\launcher" and change the line "librariesSource=XXX" by your URL on your server (like "librariesSource=http://yoursite.com/libraries/").

I tried that but the file keeps reverting back to libraries.minecraft.net

**Comment by Erafle** [comment]
Are you sure you are modifying in the resources folder? Don't forget to re-build after.

You can try to use a [modified manifest](https://github.com/SKCraft/Launcher/wiki/Custom-Version-Manifest), maybe it could fix the thing.

**Comment by DrewSin-4** [comment]
> Are you sure you are modifying in the resources folder? Don't forget to re-build after.
> 
> You can try to use a [modified manifest](https://github.com/SKCraft/Launcher/wiki/Custom-Version-Manifest), maybe it could fix the thing.

I'm pretty sure I am.

I shot you a PM on Twitter.

**Comment by hedgehog1029** [comment]
Should be fixed.
