### ISSUE TITLE
Updating/Support

### ISSUE THREAD

**Issue by Gizmo0320** [SKCraft/Launcher#368]
Is this going to be updated or can someone point me to a working repo. I have been trying get it to work with newer versions of minecraft with no luck, Any help would be awesome.

**Comment by FulI-Name** [comment]
I can help you if you still need help!

**Comment by Gizmo0320** [comment]
That would be awesome

**Comment by sylphio** [comment]
#372

**Comment by hedgehog1029** [comment]
I've been working on my own fork and was just recently added as a maintainer for this repo; an updated version is now merged into master.
