### ISSUE TITLE
Everybody having problem at 1.13+, follow this link!

### ISSUE THREAD

**Issue by sylphio** [SKCraft/Launcher#372]
Look at https://github.com/hedgehog1029/Launcher

Not mine, but i tested it with a old 1.7.10 package and a 1.16.3+forge and everything work.
Thank hedgehog1029

Not really a bug but will really help to clear the amount of issue  here until somebody take over the depot :)

**Comment by hedgehog1029** [comment]
cheers for the shoutout - I've now merged my fork into this repository, so development can move here :)
