### ISSUE TITLE
I am getting this Error when try to launch into the game.

### ISSUE THREAD

**Issue by Gizmo0320** [SKCraft/Launcher#377]
### **I am getting this Error when trying to launch into the game. Not sure how to fix it.**

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[19:55:47] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:55:47] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Gizmo0320** [comment]
I am using Forge Version 1.12.2 - 14.23.5.2854

If I use 1.12.2 - 14.23.5.2847 it launches just fine

**Comment by hedgehog1029** [comment]
sounds like the tweak class has gone missing - can you provide full logs, and maybe also attach the pack build log.

**Comment by Gizmo0320** [comment]
Game Launcher https://pastebin.com/dNJQbaQ9

Build Log https://pastebin.com/HNbAst3Q

**Comment by Gizmo0320** [comment]
I have also tried this on different computers with the same outcome.

**Comment by hedgehog1029** [comment]
nothing unusual in the log files. it sounds like the forge library jar is missing that class, or perhaps it's missing from the classpath for some reason? I'm gonna have to check where it's getting that library from, hang on

**Comment by hedgehog1029** [comment]
OK, it looks like that library is likely to be extracted from the installer jar itself, and it does have that class.

This is a bit of a fun edge case, as it's a 1.12 distribution that uses the 1.13+ install profile format. I have tested the specific installer myself and it seems to work fine for me.

When you launch packs via the creator tools, the main creator tools log window has some useful debugging information in it - specifically a dump of the parameters used to launch the game, which includes the classpath. If you could locate those extra logs (they specifically come from the launcher - if you're in the launcher you can open the options and click Console in the bottom left to open the correct console window) that would be super helpful.

**Comment by Gizmo0320** [comment]
Creator Tools Console https://pastebin.com/v1BZhn2A

Creator Tools Game Launch Log https://pastebin.com/23DAax5L

**Comment by hedgehog1029** [comment]
wait, so it works fine in the creator tools? :facepalm: 

you can get the equivalent log from the launcher by clicking on "Options" then "Console" after launching

**Comment by Gizmo0320** [comment]
Yes I am able to launch the game from Creator Tools just fine
Java Arguments are exactly the same

**Comment by hedgehog1029** [comment]
I would definitely be interested in seeing a launcher log (options -> console as described above) for a failed launch.

**Comment by Gizmo0320** [comment]
Game Launcher Console https://pastebin.com/ahywuJF9

**Comment by hedgehog1029** [comment]
Useful log, I just noticed your access token is in there, so I've snipped it, you should invalidate that session by logging in with a different launcher.

**Comment by Gizmo0320** [comment]
Ok I did that

**Comment by Gizmo0320** [comment]
I got it to work, I deleted the libraries folder and had the Launcher redownload them again and it worked this time.

Looks like a fresh install works fine, but if the libraries are already download it doesn't seem to work, until you delete the folder and have it redownload them.

**Comment by hedgehog1029** [comment]
Possibly just because the old files aren't valid (old? corrupt? no idea), but glad that the issue is solved.

I'm looking through the launcher library download path right now and there's definitely some improvements to be made. I don't think we verify hashes right now, for example, so I'll look into rectifying that.
