### ISSUE TITLE
How do I manually add libraries?

### ISSUE THREAD

**Issue by MrZomka** [SKCraft/Launcher#378]
Hello!
I'm making a modpack and Forge is trying to download old libraries that don't exist on the servers it's trying to download from.
Is there a way to manually add the libraries or put another path for downloading the libraries it needs?
Thanks!

**Comment by hedgehog1029** [comment]
There's a list of maven repositories in `launcher/src/main/resources/com/skcraft/launcher/maven_repos.json` which you can edit (need to recompile the launcher afterwards)
