### ISSUE TITLE
Launcher in Portable Mode puts assets, accounts.dat and config.json into the wrong folder

### ISSUE THREAD

**Issue by Dumdidldum** [SKCraft/Launcher#379]
Using the Launcher in portable mode (distributing the .jar directly from the build/libs folder) puts the assets folder, accounts.dat and jonfig.json into the wrong path.

This was almost fixed in  #335

To fix this the[ followoing lines](https://github.com/SKCraft/Launcher/blob/f53ee9b6faf5af222b38da3c1d89b2bbedf4f785/launcher/src/main/java/com/skcraft/launcher/Launcher.java#L97):
```
        this.assets = new AssetsRoot(new File(baseDir, "assets"));
        this.config = Persistence.load(new File(configDir, "config.json"), Configuration.class);
        this.accounts = Persistence.load(new File(configDir, "accounts.dat"), AccountList.class);
```
should be changed to (or something like that):
```
        this.assets = new AssetsRoot(new File(this.baseDir, "assets"));
        this.config = Persistence.load(new File(configDir.getAbsoluteFile(), "config.json"), Configuration.class);
        this.accounts = Persistence.load(new File(configDir.getAbsoluteFile(), "accounts.dat"), AccountList.class);
```
This causes the files to be generated in the same folder as the launcher.jar

**Comment by Dumdidldum** [comment]
in my case (windows 10) they were put into the base directory of the drive the .jar was on (D:)

**Comment by hedgehog1029** [comment]
A note for running the launcher completely standalone: it works off of the current directory, and I'm not sure what "double click to open" will set that to.
