### ISSUE TITLE
Fabric not load

### ISSUE THREAD

**Issue by ClemFR** [SKCraft/Launcher#380]
When I put the fabric installer into the /src folder (like with forge) and press the test button, fabric doesn't load and the vanilla version of Minecraft is launched

**Comment by hedgehog1029** [comment]
It needs to go in the "loaders" folder, and check the build log for any warnings or errors printed.

**Comment by ClemFR** [comment]
Yes sorry, I put it into the /loaders folder, but it don't load when I test the modpack.
When I build the modpack, this error appears :
```
[infos] Installing fabric-installer-0.6.1.51.jar...
[avertissement] Loader fabric-installer-0.6.1.51.jar was skipped due to missing metadata. Is it really a loader JAR?
```

**Comment by hedgehog1029** [comment]
ah yeah - you need to use a Fabric Loader jar, not Fabric Installer

installer isn't version-specific so I can't actually extract any metadata from installer jars

**Comment by ClemFR** [comment]
I have tried to install fabric on the official minecraft launcher and take the fabric loader.jar file but it did the same error. How can I get the fabric loader file ?

**Comment by hedgehog1029** [comment]
here's the latest loader jar: https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.10.8/fabric-loader-0.10.8.jar

I think I'll go ask the Fabric team if they can add this to the "use" page, so it's easy to find

**Comment by ClemFR** [comment]
Yes that an good idea, thank you for your help !
