### ISSUE TITLE
Server returned HTTP response code: 403 for URL

### ISSUE THREAD

**Issue by Fleisar** [SKCraft/Launcher#381]
I tried to change the news URL for the launcher, but the web server was returning a 403 code. Installing the User-Agent (in com.skcraft.launcher.swing.webpagePanel.java) solved my problem.
```java
conn = (HttpURLConnection) url.openConnection();
conn.setRequestMethod("GET");
conn.addRequestProperty("User-Agent", "Mozilla/4.76"); // there can be any user-agent
conn.setUseCaches(false);
conn.setDoInput(true);
conn.setDoOutput(false);
conn.setReadTimeout(5000);
```
[WebpagePanel.java](https://github.com/SKCraft/Launcher/files/5824069/WebpagePanel.zip)

**Comment by hedgehog1029** [comment]
I suspect this is Cloudflare's user-agent filtering, tends to cause issues like this. Will happily add a user-agent to the webpage panel...
