### ISSUE TITLE
Seemingly Random Library Corruption

### ISSUE THREAD

**Issue by ChloeDawn** [SKCraft/Launcher#385]
**Launcher version:** 3907158274fe9b688b1c3ece35a56d2ffc33d9e4

Libraries exported from the creator tools for upload seem to result in arbitrary corruption when the launcher downloads them. Replacing these libraries with the ones created for the creator tools test launcher resolved the issue for me, but my friend on MacOS is still experiencing these problems. Here are some of the random failures:

![0](https://cdn.discordapp.com/attachments/545358859535908894/803436644635639858/unknown.png)
![1](https://cdn.discordapp.com/attachments/545358859535908894/803437175512498176/unknown.png)
![2](https://cdn.discordapp.com/attachments/545358859535908894/803434823188348958/unknown.png)

**Comment by hedgehog1029** [comment]
those three libraries look like the mac-specific lwjgl distributions, so you probably need to reupload those as well

files from libraries.minecraft.net seem to be ok. gonna have a look into what's up with the upload ones

```
~ ➥ curl https://libraries.minecraft.net/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar | sha1sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  310k  100  310k    0     0  1903k      0 --:--:-- --:--:-- --:--:-- 1903k
2bb514e444994c6fece99a21f76e0c90438e377f  -
```

**Comment by ChloeDawn** [comment]
On a second review, it seems my `_upload` libraries directory is *missing* libraries that exist in my test launcher directory. Is it possible this error is a misinterpretation and it is that the file is actually missing rather than corrupt? Unsure where it would get the hash from then though. My test launcher libraries do not include these 3 libraries which may explain my friend's issues then too. (Specifically, my test launcher libraries only include these lwjgl libraries for 3.2.2 not 3.2.1)

**Comment by hedgehog1029** [comment]
Determined out-of-band (discord) that this is actually a webserver issue thanks to some real weird Apache configuration, closing
