### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by TheBozzz34** [SKCraft/Launcher#388]
I have tried building on both windows and Linux(build.sh and gradlew clean build) I get an outdated gradle error on windows, ./build.sh just says command not found and gradlew clean build gives the below error
[error log.txt](https://github.com/SKCraft/Launcher/files/5876933/error.log.txt)

**Comment by hedgehog1029** [comment]
I think your JDK is too new - the Lombok plugin is failing to run, which messes up the rest of the compile.

I'll see if I can fix the gradle configuration to work with newer JDKs but as a hotfix you can downgrade to JDK 8

**Comment by TheBozzz34** [comment]
Okay thank you!
