### ISSUE TITLE
Minecraft crashes when I try to launch it

### ISSUE THREAD

**Issue by CrazyGamer312** [SKCraft/Launcher#39]
Everytime I try to launch Minecraft i get this error message:
http://pastebin.com/AZKj7quw

Thanks in advance :)

**Comment by James137137** [comment]
This paste has been removed!

Could you extend the period

**Comment by CrazyGamer312** [comment]
http://pastebin.com/BsxGveuJ
Sorry for the late response.

**Comment by James137137** [comment]
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker

This is a forge error not SKcraftLauncher

**Comment by sk89q** [comment]
Did you upload the correct libraries?

**Comment by CrazyGamer312** [comment]
Yes i did

**Comment by sk89q** [comment]
New way to install Forge that's easier:
http://wiki.sk89q.com/wiki/Launcher/Package_creation#Installing_Forge_and_LiteLoader

Need latest launcher version.

**Comment by CrazyGamer312** [comment]
Ok i'll try it

**Comment by Longshotpro2** [comment]
I hope this isn't bumping too much, but I am having almost the same exact error. http://pastebin.com/KXgtM7Fr
Could it be caused by the launcher being built with jdk 1.8 instead of 1.7? Just throwing out an idea.

**Comment by sk89q** [comment]
Make a new issue.

Take a picture of your main modpack folder (containing src), your loaders/ folder and the command that you use to build the modpack.

**Comment by halvors** [comment]
I've built it successfully with jdk 8. So don't think thats the problem.

**Comment by Longshotpro2** [comment]
Did you have forge in the pack?
