### ISSUE TITLE
Launcher build fails on modern JDKs

### ISSUE THREAD

**Issue by Swapnil282002** [SKCraft/Launcher#391]
> Configure project :

*******************************************
 You are building SKCraft Launcher!

 Output files will be in [subproject]/build/libs
*******************************************

> Task :launcher:compileJava FAILED
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
8 actionable tasks: 2 executed, 6 up-to-date
Press any key to continue . . .

**Comment by hedgehog1029** [comment]
Too new JDK - current master branch is still targeting Java 6 and support has been dropped for that from newer Java versions.

The [`feat/new-authentication`](https://github.com/SKCraft/Launcher/tree/feat/new-authentication) branch is targeting Java 8 which you should be able to successfully build. Until that branch is merged back into master, you can download that branch [from here](https://github.com/SKCraft/Launcher/archive/feat/new-authentication.zip) and use it.

**Comment by Swapnil282002** [comment]
> Configure project :

*******************************************
 You are building SKCraft Launcher!

 Output files will be in [subproject]/build/libs
*******************************************


> Task :launcher:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :launcher-builder:compileJava
Note: C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\launcher-builder\src\main\java\com\skcraft\launcher\builder\PackageBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :creator-tools:compileJava
Note: C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\creator-tools\src\main\java\com\skcraft\launcher\creator\dialog\PackManagerFrame.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :launcher-bootstrap:compileJava FAILED
C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\launcher-bootstrap\src\main\java\com\skcraft\launcher\bootstrap\LauncherBinary.java:14: error: cannot find symbol
import java.util.jar.Pack200;
                    ^
  symbol:   class Pack200
  location: package java.util.jar
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher-bootstrap:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 6s
26 actionable tasks: 21 executed, 5 up-to-date
Press any key to continue . . .

**Comment by hedgehog1029** [comment]
ah,, well pack200 is gonna scupper that up. at the moment your only option is to downgrade your JDK (JDK 8 should still be actively available) and make sure gradle is using it (JAVA_HOME can help with that). but that's getting kind of complicated.

I already started removing pack200 like a week ago, but I was hoping it could be a slightly more gradual process. If you can't figure out how to downgrade your JDK you'll just have to wait until I can remove pack200 completely

**Comment by Swapnil282002** [comment]
i got JDK8
and 

> Configure project :

*******************************************
 You are building SKCraft Launcher!

 Output files will be in [subproject]/build/libs
*******************************************


> Task :launcher:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :launcher-builder:compileJava
Note: C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\launcher-builder\src\main\java\com\skcraft\launcher\builder\PackageBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :creator-tools:compileJava
Note: C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\creator-tools\src\main\java\com\skcraft\launcher\creator\dialog\PackManagerFrame.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :launcher-bootstrap:compileJava
C:\Users\MNTPHS\Desktop\Launcher-feat-new-authentication\launcher-bootstrap\src\main\java\com\skcraft\launcher\bootstrap\LauncherBinary.java:14: error: cannot find symbol
import java.util.jar.Pack200;
                    ^
  symbol:   class Pack200
  location: package java.util.jar
1 error

> Task :launcher-bootstrap:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher-bootstrap:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 53s
26 actionable tasks: 21 executed, 5 up-to-date
Press any key to continue . . .

**Comment by Swapnil282002** [comment]
any idea how long its gonna take

**Comment by hedgehog1029** [comment]
Should be fixed as of 571d1769a217519934d699b0c3d28c0612563681.

**Comment by hedgehog1029** [comment]
oh, but it's still set to java 6... easy enough fix on that front though. gimme a minute

**Comment by hedgehog1029** [comment]
here: https://github.com/SKCraft/Launcher/archive/fix/new-jdks.zip

**Comment by Proplex** [comment]
Thanks -- everything is now working for me and I was able to build.
