### ISSUE TITLE
Cant detect file changes that retain the same file name.

### ISSUE THREAD

**Issue by joshricker** [SKCraft/Launcher#393]
In my instance we have zen script files under src\scripts and the launcher only seem to looks for new file names or if a file has been deleted, never if it has been changed. In order to push changes to a file in this folder I must change its name. This seems to be the case for all folders except configs. Is there a flag I can put on the folder for the pack builder to take a closer look at the file in here like the config dir?

**Comment by hedgehog1029** [comment]
Theoretically the launcher makes no particular decisions based on subfolders of `src/`, everything is scanned the exact same way (with special handling for `_CLIENT`/`_SERVER`/etc. folders).

Files are scanned fresh every time the builder is run, and hashes calculated for each included file. So as long as the hashes differ the file should always be marked for update.

If you look in the manifests generated before and after a change - do you see a hash difference for that file? Are you sure the updated version is being pulled into the build folder?

**Comment by joshricker** [comment]
I just looked at the .json that is made when I rebuild the pack and the hashes are different for the file I updated, but the client will not download/update them.

`
{"type":"file","hash":"5c9a3aefcdad74ba92df713158497ee35524c00b","location":"5c/9a/5c9a3aefcdad74ba92df713158497ee35524c00b","to":"scripts/ZZZZZZ_AI.zs","size":2787,"userFile":true}
{"type":"file","hash":"e0c1f7e0764f9d2fe7e4632a3abe31b891e5a6a5","location":"e0/c1/e0c1f7e0764f9d2fe7e4632a3abe31b891e5a6a5","to":"scripts/ZZZZZZ_AI.zs","size":2765,"userFile":true}
`

At this point I just wan to make sure I'm not doing anything wrong. To update a pack I already have on the launcher I just update the necessary files in the \src\scripts run the pack builder on it again (launcher-builder-4.4) and use this bash script to run it and handle where everything goes. Then ill just use the the shortcut to packages I put in there and update the version.

`
LAST=`cat last`
echo "Version? Last update was "$LAST"."
read VER
echo $VER > last
java -jar launcher-builder-4.4-SNAPSHOT.jar --version $VER --input . --output "/var/www/html/Launcher/" --manifest-dest "/var/www/html/Launcher/stacia.json" 
echo "Goto packages?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) nano /var/www/html/Launcher/packages.json; break;;
        No ) exit;;
    esac
done
`

**Comment by hedgehog1029** [comment]
ah - it looks like you've marked them as user files? user files are meant to be used for user-editable files (like options.txt which is modified by the client) to prevent overwriting personal settings - as such, user files will not be downloaded if they already exist.

I will have a check through the documentation to make sure this is adequately communicated.

**Comment by joshricker** [comment]
That looks to be the case, I thought that was how I specified new folders. Does the launcher just grab all the folding in src? Also i have a paste bin to the clients updating and i see a lot of errors and don't know if there were relevant or not. Looks like it may have just been me lol. 

errors
https://pastebin.com/VfWe4qNi

my modpack.json
https://pastebin.com/rPf8ky94

**Comment by hedgehog1029** [comment]
Everything in `src/` is automatically included, yes.

That errors paste is private (or pending moderation?) but if the launcher is generally functioning it's probably ok.

**Comment by joshricker** [comment]
Ok, thank you. This has been a problem for me as long as I have used the launcher and only to find out its PEBCAK Lol.
