### ISSUE TITLE
No error code nothing : But build.bat won't generate de -all launcher (only the non -all one)

### ISSUE THREAD

**Issue by ValentinJD-Pro** [SKCraft/Launcher#399]
Everything is in the title :/

**Comment by sylphio** [comment]
The non -all is now the equivalent of the previous -all.

**Comment by ValentinJD-Pro** [comment]
ooh okay i'll have to try that again because i thought it was the resean why after building the modpack et re building the launcher, when starting the game i had :
-Some errors at the end of downloads with files like guava (but relaunching like 3 times the game ended up by downloading everything)
-A fatal error while starting the game which i didn't had when testing the modpack with the creator tools

**Comment by sylphio** [comment]
I don't know the source of your problem but i can say that the non-all work on my side.

**Comment by ValentinJD-Pro** [comment]
okay good to know
thx

**Comment by hedgehog1029** [comment]
I thought I removed all references to the `-all` jars from the wiki since they don't generate anymore. But it looks like there is still a couple of leftover references.

I will update the documentation.
