### ISSUE TITLE
Build failed - https://maven.offbeatwit.ch/ certificate error

### ISSUE THREAD

**Issue by thisischrys** [SKCraft/Launcher#408]
After initial git clone:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher-fancy:shadowJar'.
> Could not resolve all dependencies for configuration ':launcher-fancy:runtimeClasspath'.
   > Could not resolve io.github.cottonmc.insubstantial:substance:7.3.1-SNAPSHOT.
     Required by:
         project :launcher-fancy
      > Could not resolve io.github.cottonmc.insubstantial:substance:7.3.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.offbeatwit.ch/repository/snapshots/io/github/cottonmc/insubstantial/substance/7.3.1-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://maven.offbeatwit.ch/repository/snapshots/io/github/cottonmc/insubstantial/substance/7.3.1-SNAPSHOT/maven-metadata.xml'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.8/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Edit: Looks like something is wrong with their certificate, guess all we can do is wait?

**Comment by hedgehog1029** [comment]
My server provider had a bit of an oopsie yesterday and my server forgot everything that happened after march 2020 (lesson: keep your own backups!) - I've just put the Maven back up and republished a bunch of things, so this should work again.
