### ISSUE TITLE
Can't change java version in Test Launcher options (Modpack creator)

### ISSUE THREAD

**Issue by RedGaming98** [SKCraft/Launcher#438]
So i'm getting this error:
```
The game is running. Please wait.
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

```
And after a quick search i realised it was because it was using the wrong version of java which is fair because I have multiple Java version including Java 16.
So i went to the Test Launcher options to change the version it uses but
![image](https://user-images.githubusercontent.com/51047087/136706557-fe010378-6fda-4d69-ab80-b35a742aa62d.png)
The field is completely empty! Unless i'm supposed to find it somewhere else?

**Comment by RedGaming98** [comment]
Thanks for clearing things up! I will try and delete java 16 and see if it will use java 8

**Comment by RedGaming98** [comment]
So what can i do?

**Comment by RedGaming98** [comment]
Thanks! This allowed me to actually test the pack and right after i built the modpack but now i'm running in a small issue, tell me if I have to make a new ticket. So the launcher succesfully downloaded the modpack from my website but it launches without any mods, just with forge even tho the mods are in the "mods" folder as they should be! So that's a small problem.

**Comment by RedGaming98** [comment]
Update: Sooo in the logs it says it literraly can't read any of the jar files of the mods so i guess the got corrupted or something.

**Comment by RedGaming98** [comment]
Update 2: Just tried in multimc and same issue so there's 2 possible culprit. Modpack creator/Launcher that wrote/read the encrypted(?) files wrong or my website that corrupt stuff.

**Comment by srnyx** [comment]
@RedGaming98 open a separate issue
