### ISSUE TITLE
Java runtime searching is broken on Windows

### ISSUE THREAD

**Issue by hedgehog1029** [SKCraft/Launcher#443]
Java runtime searching appears to be broken on Windows. Find out why.

**Comment by hedgehog1029** [comment]
Registry reading is broken in Java 9+, both because of Jigsaw and because the internal API changed.

**Comment by hedgehog1029** [comment]
With 8612b95, the issue should hopefully be mitigated; however this is currently untested.

**Comment by srnyx** [comment]
@hedgehog1029 Windows 100% fixed?

**Comment by hedgehog1029** [comment]
more fixes in #451 plus mac support

**Comment by hedgehog1029** [comment]
With 08335637f9a1a7eb65443a5f6e40f2d93ac51f2d I think this should be completely fixed, though there may be a few edge cases remaining. Regardless, this can be closed as fixed now.
