### ISSUE TITLE
Issues with boostrap updating.

### ISSUE THREAD

**Issue by halvors** [SKCraft/Launcher#45]
When i launch the bootstrap ut is supposed to update right? It does that, saves the jar to the launcher folder under my documents, but it is unable to launch the updated .jar.

Getting this error:
![UfnSRKH.png](http://i.imgur.com/UfnSRKH.png)

**Comment by halvors** [comment]
Figured this out, was silly me that was actually pack200'ing the boostrap itself :D

**Comment by ablyss** [comment]
@halvors which jar files did you end up packing? My bootstrapper doesn't like any jars. :cry:

**Comment by halvors** [comment]
@ablyss I packed the jar file found in the launcher-fancy/build folder that ends with "-all.jar". But the one in launcher/build should also work, just i that prefer the fancy one. Also make sure to specify in the bootstraper configuration if you end up with the fancy instead of the normal one.

**Comment by ablyss** [comment]
@halvors For some reason, my bootstrapper isn't accepting any .pack files; fancy -all.jars and regular ones. It's been defined in the bootstrap config file, as well...

**Comment by halvors** [comment]
@ablyss You've uploaded the file to a CDN right? Did you update the latest.json file too?

**Comment by ablyss** [comment]
@halvors yes.  Everything checks out. I don't understand why this isn't working. I'm going to fiddle around with the launcher updater classes, to find a workaround. But thank you for your assistance :D

**Comment by halvors** [comment]
@ablyss It's working on my end, so maybe looking at my customized fork will help you out? https://github.com/VoltzPlay/Launcher

**Comment by halvors** [comment]
@ablyss I recall i had some issues with something similar. Are you sure that you don't habe any funny characters in the folder path? Maybe you could post a screenshot of the error you're getting?

**Comment by ablyss** [comment]
@halvors I figured it out. Apparently, my launcher wasn't unpacking the .pack file. Adding in a unpack200.bat file with the path to unpack200.exe into the package seems to have fixed it. I think the launcher was calling the unpack200 command from cmd, but it doesn't exist. Thanks for your time and help!

**Comment by sk89q** [comment]
The launcher doesn't call any commands. The unpack code is written in Java and comes with Java so the launcher just reuses that code.

So I'm not sure what the problem is/was.

**Comment by ablyss** [comment]
@sk89q yes, but unpack200 and pack200 can't be called without direct execution from their respective exes (in my environment). Meaning, it won't run unpack200 even through runtime or commandline. What I did was change around the update class so that it

**Comment by sk89q** [comment]
My point is that the launcher doesn't use unpack200.exe at all. I'm not exactly sure what your'e referring to -- the unpack200 code [calls the Pack200 class](It uses the [Pack200 class](https://github.com/SKCraft/Launcher/blob/master/launcher-bootstrap/src/main/java/com/skcraft/launcher/bootstrap/LauncherBinary.java#L64).).

**Comment by ablyss** [comment]
@sk89q what I'm saying is that the unpack code doesn't unpack, in my case. But letting the bootstrapper use the unpack200.exe does work in my instance. But, I digress. I've fixed my problems. Sorry for wasting your time. :sob:

**Comment by sk89q** [comment]
Did you change the code linked to run the unpack200 executable then?
