### ISSUE TITLE
Mc1.18 : Maxpermsize is not supported with openjdk 17

### ISSUE THREAD

**Issue by sylphio** [SKCraft/Launcher#450]
Minecraft 1.18 required java 17 and the launcher add a maxpermsize parameter in the jvm command line that not supported in java 17.

Because of that the launch fail. It can be workaround if each user change the maxpermsize value to 0 but it is far from practical.

**Comment by hedgehog1029** [comment]
i went back in time to 30 minutes ago and fixed this in cd88effb595cc86790628741bbd836b86c6236cc

**Comment by sylphio** [comment]
Wow... that was way faster that light...

Thank
