### ISSUE TITLE
Libraries corrupt?

### ISSUE THREAD

**Issue by Keridos** [SKCraft/Launcher#458]
Tried building a 1.16.5 modpack. Seems to download fine but the launcher seems to think the java libraries of minecraft/forge seem to be corrupt, expecting different hashes. If continuing to start the instance for about 20 times it finally starts but promptly crashes due to "java.lang.NoClassDefFoundError: com/google/common/base/Preconditions"

It also happens on 1.12.2 modpacks. 

I tried downloading a few of these libraries by the urls in the modpacks json and it their hashes matched what the json specified.

So there seems to be something broken in the launcher instead.

It seems to have downloaded a different file which seem to be no jar at all, I cannot open in with 7-zip as jars usually do. 

/edit: the file seems to be a php info html page.

**Comment by hedgehog1029** [comment]
these sorts of issues are usually caused by your web server - in this case it appears your web server is occasionally serving a HTML page instead of the file it should be serving. possibly some incomplete jars as well, somehow

**Comment by Keridos** [comment]
> these sorts of issues are usually caused by your web server - in this case it appears your web server is occasionally serving a HTML page instead of the file it should be serving. possibly some incomplete jars as well, somehow

Yeah seemed to have been that. What was weird is that the libraries afaik where never supposed to be downloaded from the minecraft modpacks distribution server.

Since their hashes are stored in the json of the modpacks they should actually not be hosted on the same (web)server as the json for better security against malware/hacks.
