### ISSUE TITLE
Error with launcher and forge

### ISSUE THREAD

**Issue by AustinCasteel** [SKCraft/Launcher#46]
Having the same problem as a few other people.

Error Log: http://pastebin.com/KXgtM7Fr

Picture of the contents of the modpack folder:
![Image of folder](http://i.gyazo.com/162603e43c6885da0a790def6aa360eb.png)

Picture of the loaders folder:
![Image of folder](http://i.gyazo.com/c782c89563ad19bf133c93f134dfc95a.png)

and the command that I used to build the pack:

```
java -jar launcher-builder-4.2.3-SNAPSHOT-all.jar --version "1.0" --input . --output upload --manifest-dest "upload/longshotlppack.json"
```

**Comment by Frodgy** [comment]
The launcher seens doesn't support Java 8. I solved this problem by downloading the 7th version.
https://www.java.com/ru/download/manual_java7.jsp

**Comment by sk89q** [comment]
It works fine on Java 8.

launchwrapper/Forge, however, does/did not support Java 8.

**Comment by sk89q** [comment]
As for the error, I need a copy of your files.

**Comment by sk89q** [comment]
Actually I probably don't. Will check this out sometime.

**Comment by Longshotpro2** [comment]
So I need to revert back to 7 and everything will work fine?

**Comment by sk89q** [comment]
Well I use 8 without problem, but I haven't really had time to test your particular Forge combination.

Post your modpack.json.

**Comment by WORMSTweaker** [comment]
Actually,FyberOptic from the minecraftforum have made a patch for forge,so he can work with Java 8.Just replace the normal forge jar with the patched one in your modpack.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2206446-forge-1-6-4-1-7-2-java-8-compatibility-patch

**Comment by hedgehog1029** [comment]
Ancient issue, closing
