### ISSUE TITLE
mojang libraries corrupt

### ISSUE THREAD

**Issue by TheCherry** [SKCraft/Launcher#462]
I get the error that mojang libraries are corrupted ... 

Minecraft Version: 1.18.1

This happens only by the launcher, the creator-tools starts minecraft correctly. 

![grafik](https://user-images.githubusercontent.com/1090782/165345521-d00c76b2-ac36-4751-b9f8-cac82fd40dc1.png)

Then I try the `launcher-bootstrap` its working. But its seems that minecraft data is downloaded from the skcraft web server and not from mojang?

**Comment by hedgehog1029** [comment]
Duplicate/similar to #458

Launcher checks both your website and libraries.minecraft.net for libraries; it expects to receive a HTTP 404 for missing files. If your web server is returning 200 and a HTML page instead, it will assume it has received a real JAR file.

**Comment by TheCherry** [comment]
ah that will be the reason for sure! My webserver returning always redirect to the main website. thx, that will help, have just to create a new rule.
