### ISSUE TITLE
Creating Microsoft Client ID

### ISSUE THREAD

**Issue by Escartem** [SKCraft/Launcher#466]
Is there any documentation about creating a custom Microsoft Client ID ?

I've tried doing some stuff and register an application in Azure but it says unauthorized client so I'm asking if anyone could help me on this because I don't really know how to do that.

**Comment by hedgehog1029** [comment]
I've been meaning to write up a wiki page for this so I just did: https://github.com/SKCraft/Launcher/wiki/Custom-Microsoft-OAuth-application

**Comment by Escartem** [comment]
It worked, thank you!
