### ISSUE TITLE
Enforce Java requirements on newer Minecraft versions

### ISSUE THREAD

**Issue by shinji257** [SKCraft/Launcher#472]
Is there a way to enforce Java 16+ is used for Minecraft 1.17 and Java 17+ is used for Minecraft 1.18?

Basically if a user tries to load a newer Minecraft release with an old one for some reason (fallback fails, user picks Java 8 manually in instance settings, etc) that it would bail in the logger indicating that a newer Java version is required?  Currently it will likely try to launch the pack on Java 9 or newer and on Java 8 it actually fails stating that the `-p` option is unrecognized (it was added in Java 9).

**Comment by hedgehog1029** [comment]
isn't this related to the change you made in #471?

The normal priority order for Java instance is:
1. instance override
2. `javaVersion` in the Minecraft version manifest, if available on the user's system
3. launcher global setting
4. as a last resort, whatever java binary is on the `$PATH`

This way, you can override the version if necessary, but the launcher by default picks the version that works with your pack.

The launcher does not currently bail itself when the game is launched with an incorrect Java. I could potentially do this if `javaVersion` is in the manifest.

**Comment by shinji257** [comment]
Well you are giving me pointers and teaching me the logic that was originally in the launcher.

Even then in the event that someone chose (this is assuming your original logic... not my modified one) a version of java that didn't meet the javaVersion in the manifest how would the launcher handle it?  Would it try to launch anyways or would it exit saying it didn't meet the minimum java version defined in the manifest?

Side note - javaVersion does exist in the generated pack manifest.  I checked it there.  The "tree" location is object.versionManifest.javaVersion then it has a majorVersion entry that would be perfect.  It might be the one that the launcher is checking already so I'll have to dig when I get a moment.

**Comment by hedgehog1029** [comment]
yep, that's what the launcher uses already.

It will try and launch with whatever Java it picks. Some vanilla versions will launch with basically any Java, but modded has a harder time; which is why I left it like that. But I don't think it'd be amiss to at least warn the user, and have a "Try Anyway" button for weird configurations.

**Comment by shinji257** [comment]
Thank you for this.  I put back the code that had it look for the best version to use (when not defined elsewhere) so that this whole thing can work the way it is expected to.

;)
