### ISSUE TITLE
Quilt loader support

### ISSUE THREAD

**Issue by tambry** [SKCraft/Launcher#481]
Alternative to Fabric that's beginning to take off. Would be nice to have support.

https://quiltmc.org/

**Comment by hedgehog1029** [comment]
I have a local branch with support, was pending an upstream fix, will see if it works now and get it merged in if so.

**Comment by hedgehog1029** [comment]
Support added with the caveat that the metadata API is *still* somewhat broken, documented for future me [in an extensive comment](https://github.com/SKCraft/Launcher/blob/master/launcher-builder/src/main/java/com/skcraft/launcher/builder/loaders/FabricLoaderProcessor.java#L59).
