### ISSUE TITLE
WinRegistry does not support Java 17 (Broken Runtime selection)

### ISSUE THREAD

**Issue by johnfriedrich** [SKCraft/Launcher#494]
Runtime selection does not work under Java 17.

See: https://stackoverflow.com/questions/65630568/java-error-java-util-prefs-windowspreferences-windowsregopenkey

One replacement could be Advapi32Util
see here:
https://stackoverflow.com/questions/68815962/java-error-with-java16-java-lang-reflect-inaccessibleobjectexception

**Comment by hedgehog1029** [comment]
Since #443 we've used JNA for registry access; so you likely need to update your launcher fork.

**Comment by johnfriedrich** [comment]
Did git pull and thought I was pulling upstream, but pulled my fork. Works now. Thanks for your work!
