### ISSUE TITLE
Cannot download Minecraft 1.19.3

### ISSUE THREAD

**Issue by GoudronViande24** [SKCraft/Launcher#498]
The Mojang download server gives a http 400 response code:
![image](https://user-images.githubusercontent.com/42936037/223642445-b9705f61-c473-42f3-82a8-a7bb1e00aef9.png)
Anyone knows how to fix this?

**Comment by omskj** [comment]
Is your launcher repository up to date? Because it shouldn't be http anymore. Instead its https.

**Comment by GoudronViande24** [comment]
Yep, I manually applied the change to the config file and it worked. I should have search a little bit more before posting. Thank you!
