### ISSUE TITLE
Version Type set to the wrong value ?

### ISSUE THREAD

**Issue by oxodao** [SKCraft/Launcher#507]
I was writing the `Launching the game` [page on the wiki.vg](https://wiki.vg/Launching_the_game) the other day and I found that the versionType set in the game launch args seems to be wrong.

Here's where its found in the source: https://github.com/SKCraft/Launcher/blob/f45033e4fa81534a75c2802ec1116afe7f6df8cd/launcher/src/main/java/com/skcraft/launcher/launch/Runner.java#L440

I am not doing a PR since I'm not sure what is the real value that should be put here but I'd like to gather info if someone knows about it.

MultiMC seems to be setting it to snapshot/release, I'm guessing the value set by SKCraft launcher is there because it's a modpack launcher but it could also just be a misunderstanding / an oversight

What's the deal with this variable ?

**Comment by hedgehog1029** [comment]
The vanilla launcher sets it to "release" or "snapshot", but it's basically unused in game code - only places it's used are for the version string on the main menu and in the debug menu.

(More specifically, as far as I know, the vanilla launcher just reads the "type" key from the version manifest, and uses that. For example in the [1.19 manifest](https://launchermeta.mojang.com/v1/packages/76839fc33609dfd354b9c519f46bbea2afac9e06/1.19.json) it's set to "release")

**Comment by oxodao** [comment]
Ok, so not that important. Thanks !
