### ISSUE TITLE
Allow Users to Manage optional features After initial choice

### ISSUE THREAD

**Issue by Vortron-96** [SKCraft/Launcher#519]
After a user selects the features they want, the menu never pops up again, even if the users want to change their choice there is no way to open the window again to install/uninstall features, except for the initial choice. Is it possible to make the menu open from the right-click dropdown on instances or make it a part of instance settings?

**Comment by Magi1053** [comment]
Right clicking on the instance and selecting Force Update brings up the dialog to reselect optional features.

**Comment by Vortron-96** [comment]
> Right clicking on the instance and selecting Force Update brings up the dialog to reselect optional features.

Is it possible to change just the optional features without redoing the whole download?

**Comment by Magi1053** [comment]
Force Update does not redo the whole download. It forces the client to check with the server to see if any of the files need to be updated, as well as opens the optional features dialog. It only redownloads mods or config files if they have been changed or removed from the local install.

**Comment by Vortron-96** [comment]
Ok, thank you. Sorry for taking your time.
