### ISSUE TITLE
Modpack Status

### ISSUE THREAD

**Issue by Slind14** [SKCraft/Launcher#52]
Hey,

I was wondering why the modpack status was removed. I have no idea what exactly is meant with "causes wrapping".
https://github.com/SKCraft/Launcher/commit/d6e7c021744ec19ac56b53d3657ec7af041acc24

**Comment by sk89q** [comment]
If the name of the modpack is too long so the entire text doesn't fit, it doesn't cut off and show "..." -- instead, it becomes two lines but the row height doesn't change.

It's particularly bad on Linux with custom UI themes.
