### ISSUE TITLE
Chat disabled due to missing profile public key. please try reconnecting.

### ISSUE THREAD

**Issue by shinji257** [SKCraft/Launcher#528]
When launching Uncharted Expeditions using SKCraft I find I'm unable to chat in a multiplayer server.  It throws the error "Chat disabled due to missing profile public key. please try reconnecting.".  If I use any other launcher it works fine.  We have our own split code but for sanity I compiled a clean copy from this repository and only updated the urls to point to our host so that it gets the same files and was able to reproduce the issue.

Currently we do not know the cause.  Are you able to give any advice or know what the cause is?

Uncharted Expeditions is a 1.20.1 based pack using Forge 47.2.20

**Comment by hedgehog1029** [comment]
this is related to the chat reporting feature - sometimes the game fails to fetch the profile key from Minecraft's servers. I have also seen this happen on Prism Launcher.

There should be an error message in the game log related to this.

From a quick glance it doesn't look like there's any new launch parameters that we're missing.

**Comment by shinji257** [comment]
Hmm.... This was the log.

https://gist.github.com/shinji257/57d8bf6ccc7ce163b73c430fa9036f30

**Comment by johnfriedrich** [comment]
> Hmm.... This was the log.
> 
> https://gist.github.com/shinji257/57d8bf6ccc7ce163b73c430fa9036f30

Did you manage to solve it? Getting that on 1.20.2 Forge aswell using the Launcher

**Comment by shinji257** [comment]
We "solved" it by installing NoChatReports on the server side.  Doesn't have to be on the client to work.  This happened to be the first pack we used that didn't include this mod by default so we didn't know the issue existed until now.

**Comment by hedgehog1029** [comment]
> > Hmm.... This was the log.
> > https://gist.github.com/shinji257/57d8bf6ccc7ce163b73c430fa9036f30
> 
> Did you manage to solve it? Getting that on 1.20.2 Forge aswell using the Launcher. No error related to that in the log.
> 
> Update: @hedgehog1029 UserType needs to be "msa" instead of "microsoft". Changing this solves it

cheers, i'll get that fixed

**Comment by hedgehog1029** [comment]
I had this commit locally for ages but apparently never pushed it; fixed in d27c74688ac500e30740a0f9a41d122c1e051eb9
