### ISSUE TITLE
Add support for optional mods defined in "info.json" depend on library that is automatically installed.

### ISSUE THREAD

**Issue by halvors** [SKCraft/Launcher#53]
Add support for optional mods defined in "info.json" depend on library that is automatically installed.

I want this library to be hidden, and only installed if user selects a optional mod that depends on it.

**Comment by sk89q** [comment]
If the library is only used by one optional feature, specify the optional feature using this:
https://github.com/SKCraft/Launcher/wiki/Optional-Features
