### ISSUE TITLE
Wrong License in AboutDialog?

### ISSUE THREAD

**Issue by Nevio67** [SKCraft/Launcher#532]
We have noticed that the license “GNU General Public License, version 3” is displayed in the launcher. However, everywhere else the “GNU **Lesser** General Public License, version 3” is mentioned. Which license applies, or does it have to be updated in the dialog?

Path: launcher/src/main/java/com/skcraft/launcher/dialog/AboutDialog.java

**Comment by hedgehog1029** [comment]
oh wow, good spot! looks like the about dialog was added a few days before the license switch, and never updated...

The canonical license is and always will be in [LICENSE.txt](https://github.com/SKCraft/Launcher/blob/master/LICENSE.txt). I will fix the About dialog though.
