### ISSUE TITLE
Missing Mods

### ISSUE THREAD

**Issue by OptimusDonut** [SKCraft/Launcher#59]
So I did everything right it downloads every right, but when you go to launch it will say Missing {mod nam} and I check to see if the mod is there and it is. So then I remove the mod totally and re-launch it and it comes up saying another mod is missing. Also it seems to only do it with like IChunUtil and Aroma1997core. Core mods pretty much.

**Comment by sk89q** [comment]
If you could, please post/privately send me your package listing JSON file URL.

**Comment by smoldercraft** [comment]
I have also been experiencing this issue. It seems that something goes wrong with the mod files when they are downloaded - something similar to the following appears for each mod which fails to load in the FML log:

http://pastebin.com/VUGqY3nG

**Comment by OptimusDonut** [comment]
I couldnt figure out how to private message you so here http://pastebin.com/ffH1mmNj and here are the files https://drive.google.com/file/d/0B_4E27puDiEfV1pOUW5iWDUxcXc/view?usp=sharing

**Comment by sk89q** [comment]
Is this still a problem? Sorry, been busy.

**Comment by OptimusDonut** [comment]
I actually figured it out. In Filezilla you need to to switch the uploading
style to binary for it to work.

**Comment by sk89q** [comment]
Thanks -- I'll make sure to mention it in the docs.

**Comment by OptimusDonut** [comment]
No problem always here to help.
