### ISSUE TITLE
Problems with Forge1.8

### ISSUE THREAD

**Issue by m3gg3r** [SKCraft/Launcher#60]
Hi

I updated the Launcher from an old version to the 'new' skinned version! My old existing Modpacks working fine with the launcher, but with forge 1.8 I always get an error
http://pastebin.com/hHggczc6

The only thing in the modpack is forge1.8-11.14.1.1350 (but i also tried older versions) no other mods

**Comment by Slind14** [comment]
you are missing libs in the libraries directory.

**Comment by m3gg3r** [comment]
But with the Vanilla Launcher it also works and the libraries are also not available

**Comment by Slind14** [comment]
the vanilla launcher autodownloads them.

**Comment by m3gg3r** [comment]
But where does the vanilla launcher stores them? I checked the %appdata% .minecraft folder and the Game Directory

**Comment by Slind14** [comment]
C:\Users\<user>\AppData\Roaming\.minecraft\libraries

**Comment by m3gg3r** [comment]
Yeah i checked them, but there is not the library he wants

**Comment by Slind14** [comment]
it is for me
``C:\Users\<user>\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j``

**Comment by m3gg3r** [comment]
http://i.imgur.com/9Uv8W69.png

This are the contents of the folder

**Comment by Slind14** [comment]
all there then.

**Comment by m3gg3r** [comment]
But the game still doesn't start

**Comment by Slind14** [comment]
you probably need to provide more information. configurations, file structure..
Also try to go through the entire documentation again and verify all the steps.

**Comment by m3gg3r** [comment]
The Modpack Folder
http://i.imgur.com/GMX7Ab9.png

the loaders folder
http://i.imgur.com/1i1GiEi.png

the src folder (empty)
http://i.imgur.com/Z5YjTA3.png

the modpack.json
http://pastebin.com/pZqn82XC

the version.json
http://pastebin.com/u3YAZRfw

Creating the modpack with
java -jar "launcher-builder-4.2.3-SNAPSHOT-all.jar" --version "v0.0.1" --input . --output dist --manifest-dest "dist/ggmod.json"

Uploading the dist to my webspace and the packages.json
http://pastebin.com/Q7Y7dkhG

I build the entire launcher + the modpacks two or three times new by reading the documentation

The 'GGTest' folder on the webspace
http://i.imgur.com/R4rrYxv.png
In this libaries folder there is only MinecraftForge, in the libraries folder of the root dir there are all other libraries
http://i.imgur.com/bYPWKm7.png

**Comment by Slind14** [comment]
the libraries should be in the directory where the instance is being put for download.

**Comment by m3gg3r** [comment]
still the same error

**Comment by m3gg3r** [comment]
Runs Forge 1.8 if you start it with the SKLauncher?

**Comment by sk89q** [comment]
Where is that version.json from?

**Comment by sk89q** [comment]
Is there a reason why you're providing a custom version.json?

**Comment by m3gg3r** [comment]
Thanks that was the problem! It is working now! Thanks for your help
