### ISSUE TITLE
Mod jars are empty on pack download

### ISSUE THREAD

**Issue by spideynn** [SKCraft/Launcher#62]
I set up a custom pack, and it downloads all the files sucessfully, but it never loads the mods.
I looked into a few of the jar files and it was empty! Some of them don't even have all the files, only one or two class files.

![7f950d983feec6e01c2eeacbcdfc882e](https://cloud.githubusercontent.com/assets/1433970/7237143/9c13bb6e-e767-11e4-846a-49584ee9b381.png)

What would be causing this?

**Comment by sk89q** [comment]
Are you sure you are uploading the files to your web host correctly?

**Comment by spideynn** [comment]
http://blazelauncher.x10.mx/ if you want to have a look at it.
I'm pretty sure I did...

**Comment by sk89q** [comment]
For AnimationAPI, looking at http://blazelauncher.x10.mx/your_modpack.json

shows that it links to http://blazelauncher.x10.mx/bc/16/bc1698fbce79e6769d6c5f395fe692de3ce642b4

which is a corrupt file.

**Comment by spideynn** [comment]
If you look at the files itself (ex. https://www.dropbox.com/s/a89iohvvjigwg7s/BetterPvP_1.4.1.2_1.7.10_Forge.jar from the downloaded mod jars from the launcher) in 7zip or winzip, it only has a meta-inf folder.

**Comment by spideynn** [comment]
Here is my modpack.json: http://pastebin.com/t20d0n4p
and here is my modpack file tree: http://pastebin.com/PnTDsXSm
and here is my bat file to compile the pack: http://pastebin.com/yBYzz9BH

**Comment by sk89q** [comment]
The files on your web host are already corrupted.

Did you upload the files via FTP in ASCII mode?

**Comment by spideynn** [comment]
Apparently when I upload via FTP in ASCII mode, the files get corrupted. When I upload with the files in a zip, and unzip it with cPanel file manager, it works. Thanks for the help!

**Comment by sk89q** [comment]
You can also switch your FTP client to binary mode.

**Comment by spideynn** [comment]
I tried that as well, and the files were still corrupted. Zipping them and extracting them on cPanel is faster as well, so I'm going to stick with that.
