### ISSUE TITLE
Add Support For HTTPS For Launcher HTML

### ISSUE THREAD

**Issue by Katelyn-SN** [SKCraft/Launcher#69]
Subject say it all

**Comment by DunklerPhoenix** [comment]
The Launcher does Support https. 
I use it with a https connection. Is your Certificate valid?

**Comment by Katelyn-SN** [comment]
It will not load any https page in its internal browser

**Comment by ItsAGeekThing** [comment]
@Katelyn-SN It is loading my server's https page in its internal browser just fine.

**Comment by Slind14** [comment]
Works fine for me, too. Maybe the cert isn't trusted.

**Comment by sk89q** [comment]
Link?
