### ISSUE TITLE
change homeFolderWindows directory

### ISSUE THREAD

**Issue by smenes** [SKCraft/Launcher#70]
it is possible to change the directory of homeFolderWindows to %HOMEPATH% instead of My Documents ?

it's more convenient like that. you can continue to use My Documents or appdata or whatever you want

**Comment by sk89q** [comment]
Well, the code for getting the home path is here:
https://github.com/SKCraft/Launcher/blob/master/launcher-bootstrap/src/main/java/com/skcraft/launcher/Bootstrap.java#L193

```java
String path = System.getenv("HOMEPATH");
if (path == null) path = getFileChooseDefaultDir();
```

**Comment by smenes** [comment]
thanks for your answer and your awesome launcher.
unfortunately I'm not a dev and I don't know what to do with this.
I just want to be able to change the directory via bootstrap.properties for windows and continue with the actual default directory for linux.

sorry for my english

**Comment by sk89q** [comment]
I haven't tested this, but try changing:

```java
    private File getUserLauncherDir() {
        String osName = System.getProperty("os.name").toLowerCase();
        if (osName.contains("win")) {
            String homeDir = System.getenv("HOMEPATH");
            if (homeDir == null || homeDir.isEmpty()) path = getFileChooseDefaultDir();
            return new File(homeDir, getProperties().getProperty("homeFolderWindows"));
        } else {
            return new File(System.getProperty("user.home"), getProperties().getProperty("homeFolder"));
        }
```

to

```java
    private File getUserLauncherDir() {
        String osName = System.getProperty("os.name").toLowerCase();
        if (osName.contains("win")) {
            return new File(getFileChooseDefaultDir(), getProperties().getProperty("homeFolderWindows"));
        } else {
            return new File(System.getProperty("user.home"), getProperties().getProperty("homeFolder"));
        }
```

**Comment by smenes** [comment]
ok thanks it's more comprehensive for me like that :)

here https://github.com/oxguy3/craftboot/commit/e79d4561993a0942fb49882067ccd7203eefe0ed he use USERPROFILE instead of HOMEPATH, maybe it's better.

I gonna try both

thanks

**Comment by sk89q** [comment]
See https://technet.microsoft.com/en-us/library/cc749104(v=ws.10).aspx
