### ISSUE TITLE
Few remarks about the localization

### ISSUE THREAD

**Issue by Leeo97one** [SKCraft/Launcher#72]
Hello,

The "Install" and "Launch" strings (when right-click a modpack in the modpacks list) are not translatable in the *Launcher.properties* file.

I don't see the following strings in the launcher:

login.forgetUser=Forget selected user
login.forgetPassword=Forget password
login.forgetAllPasswords=Forget all passwords...
login.confirmForgetAllPasswords=Are you sure that you want to forget all saved passwords?
login.forgetAllPasswordsTitle=Forget passwords

I plan to share my French translation with a pull request thereafter.

**Comment by Leeo97one** [comment]
So?

**Comment by sk89q** [comment]
You can't translate it at the moment apparently. I'll have to fix it.

**Comment by Leeo97one** [comment]
Okay ^_^

**Comment by Slind14** [comment]
about the second part. right click on the login text field

**Comment by Leeo97one** [comment]
Oh okay :-O Thanks !

**Comment by Leeo97one** [comment]
Great !
