### ISSUE TITLE
PHP script for hidden modpacks

### ISSUE THREAD

**Issue by Leeo97one** [SKCraft/Launcher#73]
Hello,

I've followed the instructions on the [wiki page for making hidden modpacks](https://github.com/SKCraft/Launcher/wiki/Hidden-Modpacks) but the PHP script which is given is not functional at all. And for a PHP-noob like me, it's pretty hard to find out what is wrong.

**Comment by TheTakenFox** [comment]
What is your script?
Share it on pastebin.com

**Comment by Leeo97one** [comment]
"the PHP script which is given" (on the wiki page). Read again what I wrote above, and you'll understand.

**Comment by TheTakenFox** [comment]
I mean the script you have and what are you hosting through

**Comment by Nincodedo** [comment]
Also what version of PHP are you running? I had issues with the script when running PHP 5.3 but upgraded to 5.6 and it's been running fine.

**Comment by halvors** [comment]
The language features used in this script is only compatible with 5.6+. But it is possible to backport this.

**Comment by Slind14** [comment]
I remember there being some typos in the script but I don't have the corrected version anymore

**Comment by sk89q** [comment]
Good news: I added a GUI (in creator-tools) that now generates everything for you:

![gen](https://cloud.githubusercontent.com/assets/38949/8869295/d9014252-3196-11e5-8ab0-465b250b6276.png)

**Comment by Leeo97one** [comment]
Oh my god, there's so much new stuff!
Excellent work :smile:

**Comment by vonflynee** [comment]
Nice,Thanks a lot!

Sent via Outlook




On Fri, Jul 24, 2015 at 2:31 AM -0700, "Léo" <notifications@github.com> wrote:












Oh my god, there's so much new stuff!

Excellent work
