### ISSUE TITLE
1 time push feature?

### ISSUE THREAD

**Issue by gatekeeper258** [SKCraft/Launcher#79]
I'm trying to do:
 incorp a homegrown resourcepack to the modpack (done)
 add the resourcepack to the options.txt (done)
 add options.txt to the modpack (done)

But... the problem is that I'd like to only push the options.txt at first download. so that when players change settings/resourcepacks it doesnt revert them back to the modpack options.txt.

Is this already possible to accomplish? or should I just not force my players to use an options.txt file?

**Comment by sk89q** [comment]
Place options.txt into "User Files" in the modpack's properties.

However, if you used the creator, I think it already puts options.txt in there for you when you first create the pack.

![modpack_properties_2015-07-27_14-23-40](https://cloud.githubusercontent.com/assets/38949/8918150/20bef41e-346b-11e5-9667-1a0875075f58.png)
