### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by prodkid** [SKCraft/Launcher#80]
Does the launcher allow to ability to define mods with a url to download and maybe a drag and drop to install for mods who do not allow distributing.

**Comment by sk89q** [comment]
URL: yes, drag and drop: no (have to manually install).

**Comment by prodkid** [comment]
Drag and drop would be nice to have in the future :+1:

**Comment by sk89q** [comment]
Are you thinking of a box that would appear during install that would ask people to drop in certain mods (with perhaps link to downloads)?

**Comment by prodkid** [comment]
Yes, my thoughts exactly. Something simple enough for users to able to do it with no complications.

**Comment by sk89q** [comment]
Would it attempt to verify that the right file was added?

**Comment by prodkid** [comment]
Checking their md5 hash would be nice to have to make sure players do install the correct file.
