### ISSUE TITLE
Java gpu problem.

### ISSUE THREAD

**Issue by abrazuze** [SKCraft/Launcher#86]
The problem with this launcher is if you dont set the dedicated GPU as default for all programs, he use the integrated graphic card in every case.

Can you solve this problem?

ps: in NVIDIA control panel i have defined java (32-64bit) default with my dedicated card.

pps: no, i cant set nvidia gpu as default for all programs.

**Comment by sk89q** [comment]
Have you tried setting the Java path in the launcher?

**Comment by abrazuze** [comment]
Yes, but it does not work.

**Comment by sk89q** [comment]
And you don't have this problem with the MC launcher?

**Comment by abrazuze** [comment]
No, this is the problem.

**Comment by abrazuze** [comment]
I do not know what java uses.

In Java path must be: C:\Program Files\Java\jre1.8.0_51 without \bin ? If yes, not work and i have tried to add \bin but nothing.

**Comment by abrazuze** [comment]
How you can see in this screen http://prntscr.com/83hb2g, in game uses java 1.8 64Bit (see the graphic card) but in NVIDIA control panel there aren't events of java...

**Comment by sk89q** [comment]
The launcher adds/remove `bin/` for you so it doesn't matter.

When you add java, do you add it from the list or with "Browse" (or whatever it is in Italian)?

And have you added "javaw.exe" or "java.exe"?

**Comment by abrazuze** [comment]
With "Browse", but if i start a game that use java, it appears in the list. I added "javaw.exe"

**Comment by abrazuze** [comment]
Do you already have a theory?

**Comment by sk89q** [comment]
Do you have the launcher's source code?

If yes, try replacing the contents of src/main/java/com/skcraft/launcher/launch/JavaProcessBuilder.java with this:
http://www.hastebin.com/raw/pilonemuri

Recompile and see if it works. I changed it to run jawaw.exe instead of java.exe.

**Comment by abrazuze** [comment]
Its perfect. Thank you (:

**Comment by Envel-Nikita-Gutsenkov** [comment]
> Do you have the launcher's source code?
> 
> If yes, try replacing the contents of src/main/java/com/skcraft/launcher/launch/JavaProcessBuilder.java with this: http://www.hastebin.com/raw/pilonemuri
> 
> Recompile and see if it works. I changed it to run jawaw.exe instead of java.exe.

can you repeat plz xD
