### ISSUE TITLE
Latest recommended Forge/LiteLoader 1.7.10 pull 403 HTTP errors when used in custom SK modpack.

### ISSUE THREAD

**Issue by JohnLahr** [SKCraft/Launcher#90]
When using the latest recommended builds of both Forge and LiteLoader 1.7.10, custom modpacks are unable to access the right libraries from libraries.minecraft.net. PasteBin post here: http://pastebin.com/ESNSej4z

I should add that using these files without the custom launcher seems to be working fine.

**Comment by sk89q** [comment]
10.13.4.1492? I haven't actually noticed this problem, and I downloaded them a few days ago.

What are you making the modpack with? From the modpack creator? Command line?

**Comment by JohnLahr** [comment]
Made it with the modpack creator and used gradle to pack the launchers. It wasn't a new build that caused issues; an old, stable build suddenly stopped working. Tried making a clean build with only Forge and LiteLoader and still had issues. I'm not sure how those libraries are accessed, but I tried grabbing them directly in my browser and got the same 403 errors.

**Comment by JohnLahr** [comment]
I'm an idiot. I forgot to change URLScan's AllowDotInPath attribute back to 1 after updating it.

Issue was entirely user error.
