### ISSUE TITLE
Support for redirects in HttpRequest

### ISSUE THREAD

**Issue by octylFractal** [SKCraft/Launcher#93]
Currently servers returning 3xx make requests fail.

**Comment by dscso** [comment]
I had the same issue too.

**Comment by kayila** [comment]
I'm also having this issue, and now it seems like a bit of a problem as curseforge has started issuing temporary redirects to their files. This is an issue when mods require that you don't rehost their file.  The issue stems from the fact that the launcher is looking for an exact code of 200, and doesn't know how to handle anything else.

**Comment by spannerman79** [comment]
> This is an issue when mods require that you don't rehost their file

One such mod I know for a **fact** is JourneyMap.  It **must** be downloaded via Curse in order to be able to offer it within a modpack via a launch system other then whats been [pre-approved](http://journeymap.info/Modpack_FAQ)

**Comment by hedgehog1029** [comment]
Fixed in 7707e5e45ebb9d433ab789a69941dfde6f243d38
