### ISSUE TITLE
Build problems (characters)

### ISSUE THREAD

**Issue by Leeo97one** [SKCraft/Launcher#95]
Hello,

I've got some problem with building the project on Linux (Ubuntu).
I've created a Launcher_fr.properties file in the lang folder using the ISO-8859-1 of course (Launcher_fr.properties: text/html; charset=iso-8859-1). But special characters like "é" or "À" don't display correctly.
And if I build the same project on Windows (with the exactly same files), there are no problems.

Ubuntu 15.04 64 bits
Java OpenJDK 8

**Comment by sk89q** [comment]
How do they display?

**Comment by Leeo97one** [comment]
![capture du 2015-10-19 19 21 49](https://cloud.githubusercontent.com/assets/1344241/10585274/b5048e46-7696-11e5-8ec4-25782d77797c.png) = À propos

**Comment by sk89q** [comment]
I don't think you're saving the file as ISO-8859-1. Each character in ISO-8859-1 takes up 1 byte, but in that screenshot, À has become 3 characters (which most likely means 3 bytes).

So I'm thinking you're saving the file as UTF-8 or something.

**Comment by Leeo97one** [comment]
But how can you explain that there is no problem on Windows with this same file?
I mean, if I build the same project on Windows, special characters display properly.

**Comment by Leeo97one** [comment]
I've checked again to build the exactly same project on Linux and Windows for be sure.

Linux: problem
Windows: no problem

Launcher_fr.properties: https://drive.google.com/open?id=0BxsFHiStZClpdlN0UzFyZU5SSlE

**Comment by Leeo97one** [comment]
So?

**Comment by XakepSDK** [comment]
Rewrite bundle loader to use utf-8(in java fx you need to add utf8control to the resource bundle loader). I have no time to do this.

**Comment by sk89q** [comment]
You need to do the same here too.

However, I don't have time right now either, so you may have to wait a few days.

**Comment by Leeo97one** [comment]
I don't know how to do that x)
I'll just wait few days ^_^

**Comment by Leeo97one** [comment]
So?

**Comment by ajthemacboy** [comment]
sk's a busy man, I'm sure he'll implement this when he has time :)

You could also ask one of the people who's forked this launcher to try to implement it for you, but that's a little iffy.

**Comment by MJRamon** [comment]
I hope this will be decoded soon, because I can't release the launcher until translation will work. Came here from https://github.com/SKCraft/Launcher/issues/123
