### ISSUE TITLE
selfupdate doesn't work

### ISSUE THREAD

**Issue by dscso** [SKCraft/Launcher#96]
If I want to update the launcher, I change the version in latest.json to an higher version.
the launcher shows a 'update launcher' button.
if I press on it, the launcher downloads the .jar.pack file, and puts it in launcher/1445320747826.jar.pack, and says: please restart the launcher. but it neither extract the .pack file nor exchanges the launcher file.

you can also try youself with the example skcraft launcher.
http://update.skcraft.com/quark/launcher/versions/4.2.1.jar.pack

**Comment by ajthemacboy** [comment]
I've had this problem too but I always attributed it to my own user error.

**Comment by dscso** [comment]
I think it's better if the launcher automatically updates it self. without asking the client (like the regular minecraft launcher)

**Comment by ajthemacboy** [comment]
Pretty sure that's what the bootstrap does.

**Comment by Leeo97one** [comment]
I've that problem too ^^

**Comment by sk89q** [comment]
Are you sure you're using the bootstrap? The launcher is only able to download the update; it's the boostrap that does the actual update.

The MC launcher actually works the same way. However, my bootstrap doesn't force you to wait as it checks for an update. You could make my bootstrap always update just like the MC update, but that means you get forced to wait before you can play, even if there isn't even an update available.

**Comment by dscso** [comment]
oh I am sorry; next time I try to read the docs completely :)
thank you
