### ISSUE TITLE
Auth trouble

### ISSUE THREAD

**Issue by VeryMuche** [SKCraft/Launcher#97]
I can't login with my MC account, I get the "Sorry, Minecraft is not owned on that account" error. I tried with my username and my email address. What can I do to solve the problem ?

Thanks for reading,

VeryMuche

**Comment by ajthemacboy** [comment]
This is almost certainly not a launcher issue. Try logging in from the vanilla launcher.

**Comment by sk89q** [comment]
I get this report once in a blue moon, but so far I haven't reproduced it. Plus every time I ask what their account name is, I never get a response.

Are you sure you're typing in the right information?

**Comment by VeryMuche** [comment]
I can use my account to log into the vanilla launcher, without troubles.
I use my email address and the right password, so I think I use good credentials

**Comment by sk89q** [comment]
What's your MC name?

**Comment by VeryMuche** [comment]
VeryMuche

**Comment by sk89q** [comment]
Are you using your own custom launcher to test?

**Comment by VeryMuche** [comment]
I didn't change your code, I changed the config files in resources folder (news file for example)

**Comment by sk89q** [comment]
Did you change launcher.properties?

**Comment by VeryMuche** [comment]
Yes only the last 3 lines

**Comment by sk89q** [comment]
What's your operating system?

**Comment by VeryMuche** [comment]
Debian x64 but it doesn't work on my windows 8.1 computer too

**Comment by sk89q** [comment]
Can you run this code in shell:
````sh
curl -H "Content-Type: application/json" -X POST -d "{\"agent\":{\"name\":\"Minecraft\",\"version\":1},\"clientToken\":\"`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`\",\"username\":\"`read t; echo $t`\",\"password\":\"`read t; echo $t`\"}" https://authserver.mojang.com/authenticate 
````

Type your username, press ENTER, then your password, the ENTER.

Post the result here, but strip the output of your accessToken and clientToken.

**Comment by VeryMuche** [comment]
Ok I've just extracted the launcher.properties file again, and it works now.
Thank you very much for the help, have a nice day.
