### ISSUE TITLE
Help - How Do I?

### ISSUE THREAD

**Issue by jtrent238** [SKCraft/Launcher#99]
How Do I Get My Mod Pack To Launch From This
![image](https://cloud.githubusercontent.com/assets/10227394/11024170/78da9448-8658-11e5-89a3-401787979ef9.png)

**Comment by dj3520** [comment]
Explain what you mean by launch. Start the client or provide the pack to
the launcher.

**Comment by sk89q** [comment]
Have you followed the tutorial? https://github.com/SKCraft/Launcher/wiki/Initial-Steps

**Comment by 1n5aN1aC** [comment]
Sorry for the off-topic, but how did you get the semi-transparent background for the news?

Every css or similar method I use isn't supported by java's html renderer.

**Comment by dj3520** [comment]
Explained in the tutorial. You'll need a semi-transparent picture.

**Comment by 1n5aN1aC** [comment]
@dj3520 Thanks.  Unsure how I missed that.

**Comment by jtrent238** [comment]
Ok Thanks I Figured It Out It Was In "C:\Users\trent\Desktop\Launcher-master\launcher-fancy\build\libs"
